# -*- coding: utf-8 -*-
"""
全量中文名补录词典 —— 覆盖历史数据库中所有缺失中文名的球员（1434 人）
调用链: ZH_HIST(精确) → zh_names_extra.compose_zh(组件组合) → 本模块 compose_zh_full
原则:
  - 音译遵循国内媒体通行译法（虎扑/新华社惯例）
  - 中国/亚洲球员直接使用真实中文名
  - 带后缀(II/III/IV/Jr)的球员译作 "X世/小X"
"""

# ============ 特殊全名（精确匹配，优先级最高） ============
# 中国/亚洲球员：直接使用真实中文名
FULL_CN = {
    "Wang Zhi-zhi": "王治郅", "Mengke Bateer": "巴特尔",
    "Yi Jianlian": "易建联", "Zhou Qi": "周琦", "Cui Yongxi": "崔永熙",
    "Yuta Tabuse": "田卧勇太", "Seung-Jin Ha": "河升镇",
    "Yuki Kawamura": "河村勇辉",
    # 知名球员（常见译法与组件组合不一致者）
    "Mahmoud Abdul-Rauf": "马哈茂德·阿卜杜勒-拉乌夫",
    "Sarunas Marciulionis": "沙鲁纳斯·马丘利奥尼斯",
    "Arvydas Sabonis": "阿维达斯·萨博尼斯",
    "Toni Kukoc": "托尼·库科奇",
    "Drazen Petrovic": "德拉赞·彼得洛维奇",
    "Vlade Divac": "弗拉德·迪瓦茨",
    "Peja Stojakovic": "佩贾·斯托贾科维奇",
    "Hedo Turkoglu": "希度·特科格鲁",
    "Andrei Kirilenko": "安德烈·基里连科",
    "Manu Ginobili": "马努·吉诺比利",
    "Leandro Barbosa": "莱昂德罗·巴博萨",
    "Anderson Varejao": "安德森·瓦莱乔",
    "Nene": "内内", "Zaza Pachulia": "扎扎·帕楚里亚",
    "Goran Dragic": "戈兰·德拉季奇", "Luka Doncic": "卢卡·东契奇",
    "Kristaps Porzingis": "克里斯塔普斯·波尔津吉斯",
    "Giannis Antetokounmpo": "扬尼斯·阿德托昆博",
    "Thanasis Antetokounmpo": "萨纳西斯·阿德托昆博",
    "Kostas Antetokounmpo": "科斯塔斯·阿德托昆博",
    "Nikola Jokic": "尼古拉·约基奇",
    "Boban Marjanovic": "博班·马里亚诺维奇",
    "Bogdan Bogdanovic": "博格丹·博格达诺维奇",
    "Bojan Bogdanovic": "博扬·博格达诺维奇",
    "Nikola Vucevic": "尼古拉·武切维奇",
    "Jonas Valanciunas": "约纳斯·瓦兰丘纳斯",
    "Domantas Sabonis": "多曼塔斯·萨博尼斯",
    "Evan Fournier": "埃文·富尼耶", "Rudy Gobert": "鲁迪·戈贝尔",
    "Nicolas Batum": "尼古拉斯·巴图姆", "Tony Parker": "托尼·帕克",
    "Boris Diaw": "鲍里斯·迪奥", "Ricky Rubio": "里基·卢比奥",
    "Serge Ibaka": "塞尔吉·伊巴卡", "Victor Oladipo": "维克托·奥拉迪波",
    "Pascal Siakam": "帕斯卡尔·西亚卡姆",
    "Andre Drummond": "安德烈·德拉蒙德",
    "Joel Embiid": "乔尔·恩比德", "Josh Okogie": "约什·奥科吉",
    "Emeka Okafor": "埃梅卡·奥卡福", "Victor Azubuike": "维克托·阿祖布克",
    # II/III/IV/Jr 后缀球员（父辈已在词典中，子辈加"二世/三世/小"）
    "John Lucas III": "约翰·卢卡斯三世", "Perry Jones III": "佩里·琼斯三世",
    "James Ennis III": "詹姆斯·恩尼斯三世", "Larry Drew II": "拉里·德鲁二世",
    "Johnny O'Bryant III": "约翰尼·奥布赖恩特三世",
    "Michael Frazier II": "迈克尔·弗雷泽二世",
    "Walt Lemon Jr.": "小沃尔特·莱蒙", "Wade Baldwin IV": "韦德·鲍德温四世",
    "James Webb III": "詹姆斯·韦伯三世", "Danuel House Jr.": "小达纽尔·豪斯",
    "Harry Giles III": "哈里·贾尔斯三世", "Frank Mason III": "弗兰克·梅森三世",
    "Matt Williams Jr.": "小马特·威廉姆斯", "Derrick Walton Jr.": "小德里克·沃尔顿",
    "Andrew White III": "安德鲁·怀特三世", "Brian Bowen II": "布莱恩·鲍恩二世",
    "Melvin Frazier Jr.": "小梅尔文·弗雷泽", "Kevin Knox II": "凯文·诺克斯二世",
    "Zach Norvell Jr.": "小扎克·诺维尔", "Robert Woodard II": "罗伯特·伍达德二世",
    "Kenyon Martin Jr.": "小肯扬·马丁", "Jeff Dowtin Jr.": "小杰夫·多廷",
    "Lindy Waters III": "林迪·沃特斯三世", "Brandon Boston Jr.": "小布兰登·波士顿",
    "Greg Brown III": "格雷格·布朗三世", "David Duke Jr.": "小大卫·杜克",
    "McKinley Wright IV": "麦金利·赖特四世", "Chaundee Brown Jr.": "小昌迪·布朗",
    "RJ Nembhard Jr.": "小RJ·内姆哈德", "Michael Foster Jr.": "小迈克尔·福斯特",
    "TyTy Washington Jr.": "小泰泰·华盛顿", "Wendell Moore Jr.": "小温德尔·摩尔",
    "Patrick Baldwin Jr.": "小帕特里克·鲍德温", "Ron Harper Jr.": "小罗恩·哈珀",
    "John Butler Jr.": "小约翰·巴特勒", "Keion Brooks Jr.": "小基翁·布鲁克斯",
    "Kenneth Lofton Jr.": "小肯尼斯·洛夫顿", "Jermaine Samuels Jr.": "小杰梅因·塞缪尔斯",
    "Nick Smith Jr.": "小尼克·史密斯", "Ricky Council IV": "里基·康塞尔四世",
    "DaRon Holmes II": "达伦·霍姆斯二世", "Andre Jackson Jr.": "小安德烈·杰克逊",
    "Kevin McCullar Jr.": "小凯文·麦卡勒", "Walter Clayton Jr.": "小沃尔特·克莱顿",
    "Darius Brown II": "达柳斯·布朗二世",
}

# ============ 名字组件补录（663 个） ============
FIRST_EXTRA = {
    "AJ": "AJ", "Ace": "埃斯", "Acie": "阿西", "Adama": "阿达马", "Ade": "阿德",
    "Admiral": "阿德米尔", "Adonis": "阿多尼斯", "Adou": "阿杜", "Adreian": "阿德里安",
    "Adrian": "阿德里安", "Ahmad": "艾哈迈德", "Alando": "阿兰多", "Aleem": "阿利姆",
    "Aleksandar": "亚历山大", "Aleksej": "阿列克谢", "Alexey": "阿列克谢",
    "Alijah": "阿利亚", "Alize": "阿利泽", "Allonzo": "阿隆佐", "Alondes": "阿隆德斯",
    "Alton": "奥尔顿", "Alvin": "阿尔文", "Amal": "阿迈勒", "Amari": "阿马利",
    "Amida": "阿米达", "Andersson": "安德森", "Andrae": "安德烈", "Andreas": "安德烈亚斯",
    "Andy": "安迪", "Angel": "安赫尔", "Ansu": "安苏", "Ante": "安特", "Anton": "安东",
    "Antonis": "安东尼", "Antonius": "安东尼乌斯", "Anzejs": "安泽伊斯",
    "Arinze": "阿里泽", "Armel": "阿尔梅勒", "Armon": "阿蒙", "Arnett": "阿内特",
    "Arnoldas": "阿诺尔达斯", "Aron": "阿龙", "Arvydas": "阿维达斯", "Asa": "阿萨",
    "Ashton": "阿什顿", "Awvee": "阿维", "Axel": "阿克塞尔", "BJ": "BJ",
    "Baylor": "贝勒", "Ben": "本", "Bez": "贝兹", "Bobi": "博比", "Bones": "博恩斯",
    "Boniface": "博尼费斯", "Bonzie": "邦齐", "Bostjan": "博斯蒂安",
    "Bracey": "布雷西", "Branden": "布兰登", "Brandin": "布兰丁",
    "Braxton": "布拉克斯顿", "Brett": "布雷特", "Briante": "布里安特",
    "Brice": "布莱斯", "Britton": "布里顿", "Brodric": "布罗德里克",
    "Bronny": "布朗尼", "Brooks": "布鲁克斯", "Bruno": "布鲁诺", "Bubba": "布巴",
    "CJ": "CJ", "Cal": "卡尔", "Caleb": "卡莱布", "Cam": "卡姆",
    "Carldell": "卡尔德尔", "Carlik": "卡利克", "Carrick": "卡里克",
    "Carter": "卡特", "Casey": "凯西", "Cason": "卡森", "Casper": "卡斯珀",
    "Cassius": "卡修斯", "Cat": "卡特", "Cedi": "杰迪", "Cezary": "切扎里",
    "Chance": "钱斯", "Chaney": "钱尼", "Chasson": "查森", "Chaundee": "昌迪",
    "Chaz": "查兹", "Cheick": "谢克", "Cheikh": "谢赫", "Cherokee": "切罗基",
    "Chima": "奇马", "Chimezie": "奇梅齐", "Chinanu": "奇纳努", "Chucky": "查基",
    "Cleanthony": "克利安东尼", "Coby": "科比", "Cole": "科尔", "Colin": "科林",
    "Collin": "科林", "Cormac": "科马克", "Corsley": "科斯利", "Cory": "科里",
    "Coty": "科蒂", "Courtney": "考特尼", "Cui": "崔", "Cuonzo": "昆佐",
    "Curtis": "柯蒂斯", "D'Moi": "德莫伊", "DJ": "DJ", "DaJuan": "达胡安",
    "DaQuan": "达坎", "DaRon": "达伦", "Dairis": "戴里斯", "Daishen": "戴申",
    "Dajuan": "达胡安", "Dakari": "达卡里", "Dakota": "达科他", "Dalen": "达伦",
    "Damien": "达米安", "Damion": "达米恩", "Damir": "达米尔", "Damjan": "达米扬",
    "Damone": "达莫内", "Damyean": "达米扬", "Daniss": "达尼斯",
    "Danuel": "达纽尔", "Darington": "达林顿", "Dariq": "达里克",
    "Darnell": "达内尔", "Darrin": "达林", "Darrun": "达伦", "Darvin": "达文",
    "Daryl": "达里尔", "Davion": "达维翁", "Davon": "达文", "DeJon": "德琼",
    "DeJuan": "德胡安", "DeMarco": "德马科", "DeQuan": "德坎",
    "DeVaughn": "德沃恩", "Dedric": "德里克", "Demetris": "德米特里斯",
    "Deng": "登", "Deonte": "德昂特", "DerMarr": "德马尔", "Dereon": "德里昂",
    "Derrick": "德里克", "Desmon": "德斯蒙", "Desmond": "德斯蒙德",
    "Devean": "德文", "Devon": "德文", "Devontae": "德文泰",
    "Devyn": "德文", "Dewan": "德万", "Dexter": "德克斯特",
    "Deyonta": "德永塔", "Diamond": "戴蒙德", "Diante": "迪安特",
    "Didi": "迪迪", "Dijon": "第戎", "Dionte": "迪昂特", "Dmytro": "德米特罗",
    "Dominick": "多米尼克", "Donatas": "多纳塔斯", "Donell": "唐奈尔",
    "Donnie": "唐尼", "Donny": "唐尼", "Donta": "唐塔", "Dontae'": "唐泰",
    "Donte": "唐特", "Dontell": "唐特尔", "Doron": "多伦", "Dragan": "德拉甘",
    "Drake": "德雷克", "Dru": "德鲁", "Duje": "杜耶", "Duop": "杜奥普",
    "Dusty": "达斯蒂", "Dwayne": "德韦恩", "Dylan": "迪伦",
    "Dzanan": "贾南", "EJ": "EJ", "Edmond": "埃德蒙", "Eduardo": "爱德华多",
    "Edwin": "埃德温", "Edy": "埃迪", "Efthimios": "埃夫蒂米奥斯",
    "Egor": "叶戈尔", "Eldridge": "埃尔德里奇", "Elias": "伊莱亚斯",
    "Elie": "埃利", "Elijah": "伊莱贾", "Elliot": "埃利奥特", "Elmer": "埃尔默",
    "Elmore": "埃尔莫尔", "Emanual": "伊曼纽尔", "Emanuel": "伊曼纽尔",
    "Emoni": "埃莫尼", "Ennis": "恩尼斯", "Enrique": "恩里克",
    "Erick": "埃里克", "Erik": "埃里克", "Ernest": "欧内斯特",
    "Esteban": "埃斯特万", "Etdrick": "埃特德里克", "Evric": "埃夫里克",
    "Fab": "法布", "Fabricio": "法布里西奥", "Facundo": "法昆多",
    "Felipe": "费利佩", "Feron": "费龙", "Filip": "菲利普",
    "Francisco": "弗朗西斯科", "Frankie": "弗兰基", "Gabe": "加布",
    "Gabriel": "加布里埃尔", "Gal": "加尔", "Gani": "加尼", "Garret": "加勒特",
    "Garrison": "加里森", "Garth": "加思", "Gaylon": "盖伦", "Geno": "吉诺",
    "Georgios": "乔治斯", "Gerard": "杰拉德", "Gian": "吉安", "Gigi": "吉吉",
    "God": "戈德", "Gui": "吉", "Guillermo": "吉列尔莫", "Gustavo": "古斯塔沃",
    "Guy": "盖伊", "Hamady": "哈马迪", "Hanno": "汉诺", "Hassan": "哈桑",
    "Hassani": "哈萨尼", "Hayden": "海登", "Haywoode": "海伍德",
    "Henri": "亨利", "Herb": "赫布", "Hiram": "海勒姆", "Hollis": "霍利斯",
    "Horacio": "奥拉西奥", "Hugo": "雨果", "Hunter": "亨特", "Ibou": "伊布",
    "Ibrahim": "易卜拉欣", "Ignas": "伊格纳斯", "Igor": "伊戈尔",
    "Iman": "伊曼", "Ime": "伊梅", "Ira": "艾拉", "Isaac": "艾萨克",
    "Ish": "伊什", "Ivano": "伊万诺", "Izaiah": "伊扎亚",
    "JD": "JD", "JP": "JP", "JR": "JR", "JaJuan": "贾胡安",
    "JaKarr": "贾卡尔", "JaQuori": "贾夸里", "Jack": "杰克",
    "Jackie": "杰基", "Jackson": "杰克逊", "Jacob": "雅各布",
    "Jaden": "杰登", "Jahmai": "贾迈", "Jahmi'us": "贾米乌斯",
    "Jahmir": "贾米尔", "Jahmyl": "贾米尔", "Jaime": "海梅", "Jake": "杰克",
    "Jamaree": "贾马里", "Jameel": "贾米尔", "Jamel": "贾梅尔",
    "JamesOn": "詹姆斯昂", "Jamil": "贾米尔", "Jamir": "贾米尔",
    "Jamison": "贾米森", "Jamorko": "贾莫科", "Jarell": "贾雷尔",
    "Jarnell": "贾内尔", "Jarrett": "贾勒特", "Jarrod": "贾罗德",
    "Jarron": "贾伦", "Jarvis": "贾维斯", "Jase": "杰斯", "Javin": "贾文",
    "Javon": "贾文", "Javonte": "贾文特", "Jawad": "贾瓦德", "Jawun": "贾温",
    "Jaysean": "杰肖恩", "Jazian": "贾齐安", "Jeenathan": "吉纳坦",
    "Jelani": "杰拉尼", "Jemerrio": "杰梅里奥", "Jerel": "杰雷尔",
    "Jeremiah": "耶利米", "Jeremy": "杰里米", "Jericho": "耶利哥",
    "Jermareo": "杰马雷奥", "Jerrelle": "杰雷尔", "Jevon": "杰文",
    "Jimmer": "吉默", "Joan": "乔安", "Jock": "乔克", "Joffrey": "若弗雷",
    "Johan": "约翰", "Johnathan": "乔纳森", "Johni": "约翰尼", "Jon": "乔恩",
    "Jonah": "约拿", "Jonas": "约纳斯", "Jonathon": "乔纳森",
    "Jontay": "贾泰", "Joseph": "约瑟夫", "Juan": "胡安",
    "Juancho": "胡安乔", "Juaquin": "华金", "Jules": "朱尔斯",
    "Julian": "朱利安", "Julius": "朱利叶斯", "Julyan": "朱利安",
    "Jumaine": "朱梅因", "Junior": "朱尼奥", "Justin": "贾斯汀",
    "KJ": "KJ", "Kadary": "卡达里", "Kaiser": "凯泽", "Kalin": "卡林",
    "Kam": "卡姆", "Kaniel": "卡尼尔", "Kareem": "卡里姆",
    "Karim": "卡里姆", "Kasib": "卡西布", "Kay": "凯", "Keaton": "基顿",
    "Kebu": "凯布", "Kedrick": "凯德里克", "Keifer": "基弗", "Keion": "基翁",
    "Keita": "凯塔", "Kelan": "凯兰", "Keljin": "凯尔金",
    "Kendrick": "肯德里克", "Kennedy": "肯尼迪", "Kenneth": "肯尼斯",
    "Kenrich": "肯里奇", "Keon": "基翁", "Keshon": "凯肖恩",
    "Kessler": "凯斯勒", "Kevinn": "凯文", "Kevon": "凯文",
    "Keyontae": "基翁泰", "Khaman": "卡曼", "Khyri": "凯里",
    "Killian": "基利安", "Kim": "金", "Kiwane": "基万", "Kobi": "科比",
    "Koby": "科比", "Korleone": "科尔莱昂内", "Kornel": "科尔内尔",
    "Kosta": "科斯塔", "Kostas": "科斯塔斯", "Kylor": "凯洛",
    "LJ": "LJ", "Lachlan": "拉克伦", "Landry": "兰德里",
    "Langston": "兰斯顿", "Lari": "拉里", "Laron": "拉龙", "Lavor": "拉沃",
    "Lavoy": "拉沃伊", "Lawson": "劳森", "Lazaro": "拉萨罗",
    "Leaky": "利基", "Leandro": "莱安德罗", "Lester": "莱斯特",
    "Liam": "利亚姆", "Linas": "利纳斯", "Lindell": "林德尔",
    "Lindy": "林迪", "Linton": "林顿", "London": "伦敦", "Lonny": "朗尼",
    "Lucious": "卢修斯", "Luis": "路易斯", "MJ": "MJ", "Maalik": "马利克",
    "Mac": "麦克", "Maceo": "马塞奥", "Mahmoud": "马哈茂德",
    "Makhtar": "马赫塔尔", "Malachi": "马拉基", "Malcolm": "马尔科姆",
    "Malevy": "马莱维", "Mamadi": "马马迪", "Mamadou": "马马杜",
    "Mangok": "曼戈克", "Manny": "曼尼", "MarJon": "马尔琼",
    "MarShon": "马肖恩", "Marcelo": "马塞洛", "Mardy": "马迪",
    "Marial": "马里亚尔", "Markel": "马克尔", "Marko": "马尔科",
    "Markquis": "马克奎斯", "Markus": "马库斯", "Marlon": "马龙",
    "Martell": "马特尔", "Marty": "马蒂", "Martynas": "马丁纳斯",
    "Mason": "梅森", "Maxwell": "麦克斯韦尔", "McKinley": "麦金利",
    "Mengke": "孟克", "Meyers": "迈耶斯", "Mfiondu": "姆菲翁杜",
    "Micah": "迈卡", "Mickael": "米凯尔", "Mickell": "米克尔",
    "Mile": "米莱", "Milos": "米洛什", "Milton": "米尔顿",
    "Mindaugas": "明道加斯", "Miroslav": "米罗斯拉夫", "Mirsad": "米尔萨德",
    "Mirza": "米尔扎", "Moochie": "穆奇", "Mouhamadou": "穆罕默杜",
    "Mouhamed": "穆罕默德", "Moussa": "穆萨", "Mustafa": "穆斯塔法",
    "Mychel": "米切尔", "Myke": "迈克", "Myles": "迈尔斯", "Mãozinha": "毛西尼亚",
    "N'Faly": "恩法利", "Nae'Qwan": "奈奎万", "Nando": "南多",
    "Naz": "纳兹", "Ndudi": "恩杜迪", "Negele": "尼格尔",
    "Nemanja": "内马尼亚", "Nicolas": "尼古拉斯", "Nicolo": "尼科洛",
    "Nik": "尼克", "Nikoloz": "尼科洛兹", "Nique": "尼克", "Noa": "诺阿",
    "Noel": "诺埃尔", "Nolan": "诺兰", "Norchad": "诺查德",
    "Norman": "诺曼", "Norvel": "诺维尔", "Obinna": "奥宾纳",
    "Ochai": "奥柴", "Ognjen": "奥格涅", "Okaro": "奥卡罗",
    "Oleksiy": "奥列克西", "Olivier": "奥利维尔",
    "Olivier-Maxence": "奥利维尔-马克桑斯", "Olumide": "奥卢米德",
    "Omari": "奥马里", "Omer": "奥梅尔", "Omri": "奥姆里",
    "Onuralp": "奥努拉尔普", "Orien": "奥里恩", "Oscar": "奥斯卡",
    "Oshae": "奥谢", "Othello": "奥赛罗", "Ousmane": "乌斯曼",
    "PJ": "PJ", "Pacôme": "帕科姆", "Pape": "帕佩", "Paris": "帕里斯",
    "Patricio": "帕特里西奥", "Pavel": "帕维尔", "Payton": "佩顿",
    "Pelle": "佩勒", "Pepe": "佩佩", "Pero": "佩罗", "Pervis": "佩维斯",
    "Petr": "彼得", "Peyton": "佩顿", "Phillip": "菲利普", "Pooh": "普",
    "Popeye": "波派", "Pops": "波普斯", "Priest": "普里斯特",
    "Quenton": "昆顿", "Quinn": "奎因", "Quinndary": "昆达里",
    "Quinton": "昆顿", "RJ": "RJ", "RaiQuan": "拉奎恩", "Raja": "拉贾",
    "Rakeem": "拉基姆", "Randell": "兰德尔", "Randolph": "伦道夫",
    "Rashad": "拉沙德", "Rasheer": "拉希尔", "Rasual": "拉苏尔",
    "Ratko": "拉特科", "Raul": "劳尔", "Rawle": "罗尔", "RayJ": "雷J",
    "Rayjon": "雷琼", "Reece": "里斯", "Renaldo": "雷纳尔多",
    "Richie": "里奇", "Riley": "莱利", "Rob": "罗布", "Robbie": "罗比",
    "Rocco": "罗科", "Rodions": "罗季翁斯", "Rodrick": "罗德里克",
    "Roko": "罗科", "Roshown": "罗肖恩", "Royal": "罗亚尔",
    "Royce": "罗伊斯", "Russ": "拉斯", "Salah": "萨拉赫",
    "Samaki": "萨马基", "Sarunas": "沙鲁纳斯", "Scotty": "斯科蒂",
    "Sekou": "塞古", "Semaj": "塞马杰", "Semih": "塞米赫",
    "Sergei": "谢尔盖", "Sergey": "谢尔盖", "Seung-Jin": "升镇",
    "Shabazz": "沙巴兹", "Shammond": "沙蒙德", "Shamorie": "沙莫里",
    "Shaq": "沙克", "Sharife": "沙里夫", "Sharone": "沙罗内",
    "Sharrod": "沙罗德", "Shavlik": "沙夫利克", "Shawne": "肖恩",
    "Shawnelle": "肖内勒", "Shayne": "谢恩", "Shea": "谢伊",
    "Sherron": "谢伦", "Sidy": "西迪", "Sim": "西姆", "Simone": "西蒙内",
    "Sindarius": "辛达里乌斯", "Sion": "赛恩", "Skal": "斯卡尔",
    "Slavko": "斯拉夫科", "Solomon": "所罗门", "Sonny": "桑尼",
    "Soumaila": "苏马伊拉", "Spencer": "斯宾塞", "Spud": "斯帕德",
    "Stanley": "斯坦利", "Stanton": "斯坦顿", "Stéphane": "斯特凡", "Stephane": "斯特凡",
    "Sterling": "斯特林", "Steven": "史蒂文", "Stevin": "斯特文",
    "Stojko": "斯托伊科", "Sundiata": "孙迪亚塔", "Svi": "斯维",
    "Tacko": "塔科", "Taelon": "泰隆", "Tahjere": "塔杰尔",
    "Talen": "塔伦", "Tamar": "塔马尔", "Tang": "唐", "Tarik": "塔里克",
    "Tariq": "塔里克", "Taylor": "泰勒", "Tazé": "塔泽",
    "Terence": "特伦斯", "Terquavion": "特夸维翁", "Terrance": "特伦斯",
    "Terrel": "特雷尔", "Thabo": "塔博", "Thanasis": "萨纳西斯",
    "Theron": "塞伦", "Thon": "桑", "Tibor": "蒂博尔", "Tierre": "蒂埃尔",
    "Timmy": "蒂米", "Timothe": "蒂莫泰", "Tito": "蒂托", "Toby": "托比",
    "Tolu": "托卢", "Toney": "托尼", "Tornike": "托尔尼克",
    "Torraye": "托雷", "Tosan": "托桑", "Toure'": "图雷",
    "Trajan": "特拉詹", "Trayvon": "特雷冯", "Tre": "特雷",
    "Trendon": "特伦登", "Trent": "特伦特", "Trentyn": "特伦廷",
    "Trevelin": "特雷夫林", "Treveon": "特雷文", "Trevon": "特雷冯",
    "Trevor": "特雷弗", "Tristen": "特里斯坦", "Ty-Shon": "泰-肖恩",
    "TyTy": "泰泰", "Tyrell": "特雷尔", "Tyrese": "泰里斯",
    "Tyshawn": "泰肖恩", "Tyson": "泰森", "Tyus": "泰厄斯",
    "Udoka": "乌多卡", "Ulrich": "乌尔里希", "Usman": "乌斯曼",
    "Vander": "范德", "Vasilije": "瓦西里耶", "Vassilis": "瓦西利斯",
    "Vernon": "弗农", "Viacheslav": "维亚切斯拉夫", "Vic": "维克",
    "Victor": "维克托", "Viktor": "维克托", "Vinny": "维尼",
    "Vit": "维特", "Vitor": "维托", "Vladislav": "弗拉季斯拉夫",
    "Vlatko": "弗拉特科", "Voshon": "沃申", "Wade": "韦德",
    "Walker": "沃克", "Wang": "王", "Wendell": "温德尔", "Yang": "杨",
    "Yanic": "亚尼克", "Yante": "扬特", "Yaroslav": "雅罗斯拉夫",
    "Yi": "易", "Yinka": "因卡", "Yogi": "约吉", "Yue": "悦",
    "Yuki": "勇辉", "Yuri": "尤里", "Yuta": "勇太", "Yves": "伊夫",
    "Zabian": "扎比安", "Zan": "赞", "Zarko": "扎尔科", "Zavier": "扎维尔",
    "Zeke": "泽克", "Zendon": "赞登", "Zhaire": "扎伊尔", "Zhou": "周",
    "Zylan": "泽兰", "Zyon": "扎伊翁",
}

# ============ 姓氏组件补录（950 个） ============
LAST_EXTRA = {
    "Abdul-Rauf": "阿卜杜勒-拉乌夫", "Abdul-Wahad": "阿卜杜勒-瓦哈德",
    "Abrines": "阿夫里内斯", "Acy": "阿西", "Addison": "阿迪森",
    "Adel": "阿德尔", "Adrien": "阿德里安", "Agbaji": "阿格巴吉",
    "Ager": "阿格", "Ahearn": "阿赫恩", "Akognon": "阿科格农",
    "Akoon-Purcell": "阿库恩-珀塞尔", "Alabi": "阿拉比",
    "Aldemir": "阿尔德米尔", "Alkins": "阿尔金斯", "Allred": "奥尔雷德",
    "Almond": "阿尔蒙德", "Aluma": "阿卢马", "Amaechi": "阿马奇",
    "Amundson": "阿蒙德森", "Andersen": "安德森",
    "Andriuskevicius": "安德里乌什凯维丘斯", "Anigbogu": "阿尼格博古",
    "Anstey": "安斯泰", "Antetokounmpo": "阿德托昆博", "Antic": "安蒂奇",
    "Appling": "阿普林", "Araujo": "阿劳霍", "Archibald": "阿奇博尔德",
    "Artis": "阿蒂斯", "Augustine": "奥古斯丁", "Ayayi": "阿亚伊",
    "Ayon": "阿永", "Ayres": "艾尔斯", "Babb": "巴布", "Babbitt": "巴比特",
    "Bacon": "培根", "Badji": "巴吉", "Bairstow": "贝尔斯托",
    "Bal": "巴尔", "Balkman": "巴尔克曼", "Barber": "巴伯",
    "Barkley": "巴克利", "Barnhizer": "巴恩海泽", "Barron": "巴伦",
    "Basden": "巴斯登", "Baston": "巴斯顿", "Bateer": "巴特尔",
    "Bates-Diop": "贝茨-迪奥普", "Batista": "巴蒂斯塔",
    "Batiste": "巴蒂斯特", "Battle": "巴特尔", "Baugh": "鲍",
    "Baynes": "贝恩斯", "Bazley": "巴兹利", "Beauchamp": "博尚",
    "Beekman": "比克曼", "Benimon": "贝尼蒙", "Bentil": "本蒂尔",
    "Beringer": "贝林格", "Bernard": "伯纳德", "Bertans": "贝尔坦斯",
    "Bey": "贝", "Bhullar": "布勒", "Bitim": "比蒂姆",
    "Blakeney": "布莱克尼", "Blalock": "布拉洛克",
    "Blossomgame": "布洛瑟姆盖姆", "Blue": "布鲁", "Bobbitt": "博比特",
    "Boeheim": "贝海姆", "Bolden": "博尔登", "Bolmaro": "博尔马罗",
    "Bolomboy": "博隆博伊", "Bone": "博恩", "Boney": "博尼",
    "Bonga": "邦加", "Bonner": "邦纳", "Booker": "布克",
    "Borchardt": "博查特", "Borrell": "博雷尔",
    "Boumtje-Boumtje": "布姆特耶-布姆特耶", "Bouyea": "布耶",
    "Bowen": "鲍恩", "Bowman": "鲍曼", "Boyce": "博伊斯",
    "Bozeman": "博兹曼", "Brackins": "布拉金斯", "Bradtke": "布拉特克",
    "Braggs": "布拉格斯", "Bramlett": "布拉姆利特",
    "Brazdeikis": "布劳泽季基斯", "Brea": "布雷亚", "Bremer": "布雷默",
    "Brewer": "布鲁尔", "Brimah": "布里马", "Briscoe": "布里斯科",
    "Brissett": "布里塞特", "Brockington": "布罗金顿",
    "Brockman": "布罗克曼", "Broekhoff": "布勒克霍夫", "Broome": "布鲁姆",
    "Brussino": "布鲁西诺", "Buchanan": "布坎南", "Budinger": "布丁格",
    "Bullock": "布洛克", "Burrell": "伯勒尔", "Buycks": "拜克斯",
    "Bynum": "拜纳姆", "Cacok": "卡科克", "Calathes": "卡拉塞斯",
    "Caldwell": "考德威尔", "Campazzo": "坎帕佐", "Canaan": "卡南",
    "Cancar": "坎卡尔", "Cannady": "坎纳迪", "Caracter": "卡拉科特",
    "Cardwell": "卡德维尔", "Carney": "卡尼", "Carruth": "卡鲁思",
    "Carton": "卡尔顿", "Castleton": "卡斯尔顿", "Causwell": "考斯维尔",
    "Cavanaugh": "卡瓦诺", "Caver": "卡弗", "Celestand": "塞莱斯坦德",
    "Champagnie": "香皮尼", "Chealey": "奇利", "Cheatham": "奇塔姆",
    "Cherry": "切里", "Chomche": "乔姆切", "Christmas": "克里斯马斯",
    "Christon": "克里斯坦", "Christopher": "克里斯托弗",
    "Cisse": "西塞", "Cissoko": "西索科", "Clarke": "克拉克",
    "Clavell": "克拉维尔", "Claver": "克拉维尔", "Cleveland": "克利夫兰",
    "Closs": "克洛斯", "Coker": "科克", "Collier": "科利尔",
    "Colo": "科洛", "Comanche": "科曼奇", "Conlon": "康伦",
    "Connaughton": "康诺顿", "Conroy": "康罗伊", "Cooke": "库克",
    "Cooks": "库克斯", "Cooley": "库利", "Cornelie": "科内利",
    "Costello": "科斯特洛", "Courtney": "考特尼", "Cousin": "库辛",
    "Creek": "克里克", "Crispin": "克里斯平", "Crotty": "克罗蒂",
    "Crutcher": "克拉彻", "Cryer": "克拉耶", "Culver": "卡尔弗",
    "Cumberland": "坎伯兰", "Cureton": "柯尔顿", "Dadiet": "达迪耶",
    "Danilovic": "达尼洛维奇", "Dante": "丹特", "Dare": "达雷",
    "Darling": "达林", "Datome": "达托梅", "David": "大卫",
    "Davies": "戴维斯", "Davison": "戴维森", "Days": "戴斯",
    "DeLaurier": "德劳里尔", "Deck": "德克", "Dehere": "德海尔",
    "Dejean-Jones": "德让-琼斯", "Dekker": "德克尔", "Delaney": "德莱尼",
    "Delfino": "德尔菲诺", "Delgado": "德尔加多",
    "Dellavedova": "德拉维多瓦", "Demps": "德姆普斯",
    "Dentmon": "登特蒙", "Derrickson": "德里克森", "Diabaté": "迪亚巴特",
    "Diakite": "迪亚基特", "Dial": "迪亚尔", "Diallo": "迪亚洛",
    "Diawara": "迪亚瓦拉", "Diaz": "迪亚兹", "Dickens": "迪肯斯",
    "Dickinson": "迪金森", "Dieng": "迪昂", "Dotson": "多特森",
    "Douby": "杜比", "Doumbouya": "敦布亚", "Dowdell": "多德尔",
    "Doyle": "多伊尔", "Dozier": "多齐尔", "Dragić": "德拉季奇",
    "Drell": "德雷尔", "Driggers": "德里格斯", "Drobnjak": "德罗布尼亚克",
    "Duarte": "杜阿尔特", "Ducas": "杜卡斯", "Duckworth": "达克沃思",
    "Dukan": "杜坎", "Dëmin": "德明", "Early": "厄利",
    "Echenique": "埃切尼克", "Eddie": "埃迪", "Edney": "埃德尼",
    "Ekezie": "埃克泽", "El-Amin": "埃尔-阿明", "Elleby": "埃勒比",
    "Ellenson": "埃伦森", "Ellington": "埃灵顿", "Elson": "埃尔森",
    "Emmett": "埃米特", "Enaruna": "埃纳鲁纳", "Ennis": "恩尼斯",
    "Erden": "埃尔登", "Eschmeyer": "埃施迈尔", "Essengue": "埃森盖",
    "Etienne": "艾蒂安", "Evbuomwan": "埃夫布姆万", "Eyenga": "耶恩加",
    "Fall": "法尔", "Faverani": "法韦拉尼", "Fazekas": "法泽卡斯",
    "Feick": "菲克", "Felder": "费尔德", "Felix": "费利克斯",
    "Fish": "菲什", "Fitts": "菲茨", "Flagler": "弗拉格勒",
    "Flores": "弗洛雷斯", "Flowers": "弗劳尔斯",
    "Fontaine": "方丹", "Fontecchio": "丰泰基奥", "Foote": "富特",
    "Forbes": "福布斯", "Forrest": "福雷斯特", "Fortson": "福特森",
    "Fotsis": "福齐斯", "Frahm": "弗拉姆", "Franks": "弗兰克斯",
    "Fredette": "弗雷戴特", "Freeland": "弗里兰",
    "Freeman-Liberty": "弗里曼-利伯蒂", "Freije": "弗雷耶",
    "Fudge": "福吉", "Fuller": "富勒", "Funk": "丰克",
    "Furphy": "弗菲", "Gai": "盖", "Gamble": "甘布尔",
    "Garbajosa": "加尔巴霍萨", "Garces": "加塞斯", "Garcia": "加西亚",
    "Gardner": "加德纳", "Garino": "加里诺", "Garnett": "加内特",
    "Garris": "加里斯", "Garuba": "加鲁巴", "Garza": "加尔扎",
    "Gates": "盖茨", "Gaze": "盖兹", "Gbinije": "格比尼耶",
    "Geary": "吉尔里", "Gee": "吉", "Gelabale": "热拉巴勒",
    "George": "乔治", "Georges-Hunt": "乔治斯-亨特",
    "Giddens": "吉登斯", "Gilbert": "吉尔伯特", "Gilder": "吉尔德",
    "Gladness": "格拉德尼斯", "Glover": "格洛弗",
    "Glyniadakis": "格利尼达基斯", "Goldin": "戈尔丁",
    "González": "冈萨雷斯", "Goodwin": "古德温", "Gortman": "戈特曼",
    "Grantham": "格兰瑟姆", "Gravett": "格拉维特", "Greer": "格里尔",
    "Grundy": "格伦迪", "Gudurić": "古杜里奇", "Gueye": "盖耶",
    "Guy": "盖伊", "Ha": "河", "Hairston": "海尔斯顿",
    "Haislip": "海斯利普", "Haley": "黑利", "Hamer": "哈默",
    "Hammonds": "哈蒙兹", "Hammons": "哈蒙斯",
    "Handlogten": "汉德洛格滕", "Hannahs": "汉纳斯",
    "Hansbrough": "汉斯布鲁", "Harkless": "哈克莱斯",
    "Harrellson": "哈雷尔森", "Haston": "哈斯顿", "Hauser": "豪泽",
    "Hayward": "海沃德", "Heal": "希尔", "Hearn": "赫恩",
    "Hendrickson": "亨德里克森", "Henson": "亨森", "Hepburn": "赫本",
    "Hernangomez": "埃尔南戈麦斯", "Herrmann": "赫尔曼",
    "Hervey": "赫维", "Hinson": "辛森", "Hoard": "霍德",
    "Hobson": "霍布森", "Hodge": "霍奇", "Holcomb": "霍尔科姆",
    "Holland": "霍兰德", "Hood": "胡德", "Horner": "霍纳",
    "Horton-Tucker": "霍顿-塔克", "Hudgins": "赫金斯",
    "Huertas": "韦尔塔斯", "Huestis": "休斯蒂斯", "Hukporti": "胡克波尔蒂",
    "Hurt": "赫特", "Inglis": "英格利斯", "Iwundu": "伊温杜",
    "Jarreau": "贾罗", "Jawai": "贾瓦伊", "Jefferies": "杰弗里斯",
    "Jerebko": "杰雷布科", "Jerrett": "杰瑞特", "Jianlian": "建联",
    "Johnsen": "约翰森", "Johnson-Odom": "约翰逊-奥多姆",
    "Juzang": "朱赞", "Kabengele": "卡本盖莱",
    "Kalaitzakis": "卡拉伊察基斯", "Kalkbrenner": "卡尔克布伦纳",
    "Kaun": "考恩", "Kawamura": "河村", "Keels": "基尔斯",
    "Kempton": "肯普顿", "Kennedy": "肯尼迪", "Ketner": "凯特纳",
    "Khryapa": "赫里亚帕", "Kidd": "基德", "Kidd-Gilchrist": "基德-吉尔克里斯特",
    "Kirk": "柯克", "Kispert": "基斯珀特", "Kleiza": "克雷扎",
    "Klintman": "克林特曼", "Kolek": "科莱克", "Koloko": "科洛科",
    "Kornet": "科内特", "Korolev": "科罗廖夫", "Kravtsov": "克拉夫佐夫",
    "Krystkowiak": "克里斯蒂科维亚克", "Kulboka": "库尔博卡",
    "Kurucs": "库鲁茨", "Kurz": "库尔茨", "Kutluay": "库特鲁艾",
    "Kuzminskas": "库兹明斯卡斯", "LaRavia": "拉拉维亚",
    "Labissiere": "拉比西埃", "Lafayette": "拉法耶特",
    "Landale": "兰代尔", "Lang": "朗", "Langhi": "兰吉",
    "Lanier": "拉尼尔", "Laprovittola": "拉普罗维托拉",
    "Lasme": "拉斯梅", "Lauvergne": "劳韦尔涅", "Law": "劳",
    "Lawal": "拉瓦尔", "Leaf": "利夫", "Leckner": "莱克纳",
    "Lecque": "莱克", "Ledo": "莱多", "Legler": "莱格勒",
    "Lenard": "莱纳德", "Leonard": "伦纳德", "Leons": "莱昂斯",
    "Liggins": "利金斯", "Livers": "利弗斯", "Llamas": "利亚马斯",
    "Lopez": "洛佩兹", "Louzada": "卢扎达", "Love": "乐福",
    "Lovering": "洛夫林", "Loyd": "洛伊德", "Lue": "卢",
    "Lundberg": "伦德伯格", "Luwawu-Cabarrot": "卢瓦乌-卡巴罗",
    "Mac": "麦克", "Machado": "马查多", "Macijauskas": "马丘斯卡斯",
    "Mack": "麦克", "Macklin": "麦克林", "Macon": "梅肯",
    "Macura": "马库拉", "Maddox": "马多克斯", "Madkins": "马德金斯",
    "Magette": "马杰特", "Magnay": "马格奈", "Major": "梅杰",
    "Maker": "马凯尔", "Maledon": "马勒东", "Maluach": "马卢阿奇",
    "Mane": "马内", "Mann": "曼恩", "Manning": "曼宁",
    "Marble": "马布尔", "Marciulionis": "马丘利奥尼斯",
    "Markota": "马尔科塔", "Marks": "马克斯", "Marshall": "马歇尔",
    "Martin": "马丁", "Mashack": "马沙克", "Maten": "马滕",
    "Mathews": "马修斯", "Mathiang": "马蒂昂", "Mathias": "马蒂亚斯",
    "Maxiell": "马克西尔", "Mayberry": "梅贝里", "Maynor": "梅诺",
    "Mañón": "马尼翁", "Mbeng": "姆本格", "Mbenga": "姆本加",
    "McCall": "麦考尔", "McCallum": "麦卡勒姆", "McCann": "麦卡恩",
    "McCarty": "麦卡蒂", "McCaskill": "麦卡斯基尔",
    "McClintock": "麦克林托克", "McClung": "麦克朗",
    "McCoy": "麦科伊", "McCray": "麦克雷", "McCree": "麦克里",
    "McCullough": "麦卡洛", "McDaniels": "麦克丹尼尔斯",
    "McDermott": "麦克德莫特", "McDonald": "麦克唐纳",
    "McFarlin": "麦克法林", "McGary": "麦加里", "McGriff": "麦格里夫",
    "McGruder": "麦格鲁德", "McIlvaine": "麦克尔文",
    "McKinney-Jones": "麦金尼-琼斯", "McKinnie": "麦金尼",
    "McLaughlin": "麦克劳林", "McLemore": "麦克勒莫",
    "McLeod": "麦克劳德", "McMillan": "麦克米兰", "McNeal": "麦克尼尔",
    "McNeeley": "麦克尼利", "McPherson": "麦克弗森",
    "McVeigh": "麦克维", "Medvedenko": "梅德维登科", "Mejri": "梅杰里",
    "Mekel": "梅克尔", "Melli": "梅利", "Melo": "梅洛",
    "Mensah": "门萨", "Mensah-Bonsu": "门萨-邦苏", "Merrill": "梅里尔",
    "Metu": "梅图", "Meyer": "迈耶", "Micić": "米西奇",
    "Mika": "米卡", "Miles": "迈尔斯", "Milić": "米利奇",
    "Miller": "米勒", "Millsap": "米尔萨普", "Minaya": "米纳亚",
    "Minix": "米尼克斯", "Miskiri": "米斯基里", "Mitchell": "米切尔",
    "Mitrou-Long": "米特鲁-朗", "Mobley": "莫布利", "Moiso": "穆瓦索",
    "Moneke": "莫内克", "Monia": "莫尼亚", "Montero": "蒙特罗",
    "Moon": "穆恩", "Mooney": "穆尼", "Moore": "摩尔",
    "Morales": "莫拉莱斯", "Moreland": "莫兰德", "Morris": "莫里斯",
    "Morrow": "莫罗", "Motiejūnas": "莫泰尤纳斯", "Motley": "莫特利",
    "Mottola": "莫托拉", "Moultrie": "莫尔特里", "Moute": "穆特",
    "Mullens": "马伦斯", "Munford": "芒福德", "Murdock": "默多克",
    "Murkey": "默基", "Murphy": "墨菲", "Murray-Boyles": "默里-博伊尔斯",
    "Murry": "默里", "Musa": "穆萨", "Muscala": "穆斯卡拉",
    "Muursepp": "穆尔塞普", "Myers": "迈尔斯",
    "Mykhailiuk": "米哈伊柳克", "N'diaye": "恩迪亚耶",
    "Nachbar": "纳克巴尔", "Nailon": "奈伦", "Najera": "纳赫拉",
    "Nance": "南斯", "Napier": "内皮尔", "Ndiaye": "恩迪亚耶",
    "Ndong": "恩东", "Ndour": "恩多尔", "Neal": "尼尔",
    "Nedović": "内多维奇", "Negro": "内格罗", "Nelson": "纳尔逊",
    "Nembhard": "内姆哈德", "Newbill": "纽比尔", "Newble": "纽布尔",
    "Newell": "纽厄尔", "Newman": "纽曼", "Newton": "牛顿",
    "Nichols": "尼科尔斯", "Nicholson": "尼科尔森",
    "Nickerson": "尼克尔森", "Niederhäuser": "尼德豪瑟", "Nix": "尼克斯",
    "Nnaji": "纳吉", "Noel": "诺埃尔", "Nogueira": "诺盖拉",
    "Nordgaard": "诺德加德", "Norman": "诺曼", "Norris": "诺里斯",
    "Novak": "诺瓦克", "Nowell": "诺威尔", "Ntilikina": "尼利基纳",
    "Nunn": "纳恩", "Nunnally": "纳纳利", "Nwaba": "恩瓦巴",
    "Nwora": "恩沃拉", "O'Bannon": "奥班农", "O'Brien": "奥布莱恩",
    "O'Bryant": "奥布赖恩特", "Oberto": "奥贝托", "Ochefu": "奥切福",
    "Oduro": "奥杜罗", "Ohlbrecht": "奥尔布雷希特", "Okani": "奥卡尼",
    "Okobo": "奥科博", "Olbrich": "奥尔布里奇", "Olivari": "奥利瓦里",
    "Oliver": "奥利弗", "Omier": "奥米尔", "Omoruyi": "奥莫鲁伊",
    "Onuaku": "奥努阿库", "Orton": "奥顿", "Osman": "奥斯曼",
    "Oturu": "奥图鲁", "Overton": "奥弗顿", "Owens": "欧文斯",
    "Owes": "奥维斯", "Oyedeji": "奥耶德吉", "Padgett": "帕吉特",
    "Paige": "佩奇", "Palacio": "帕拉西奥", "Palmer": "帕尔默",
    "Pangos": "潘戈斯", "Panko": "潘科", "Papagiannis": "帕帕扬尼斯",
    "Papanikolaou": "帕帕尼古拉乌", "Pargo": "帕戈", "Parish": "帕里什",
    "Parker": "帕克", "Parks": "帕克斯", "Pasecniks": "帕塞奇尼克斯",
    "Patterson": "帕特森", "Patton": "帕顿", "Paul": "保罗",
    "Pavlović": "帕夫洛维奇", "Payne": "佩恩", "Peavy": "皮维",
    "Pecherov": "佩切罗夫", "Pedulla": "佩杜拉", "Pelle": "佩莱",
    "Penberthy": "彭伯西", "Penda": "潘达", "Penigar": "佩尼加",
    "Penney": "彭尼", "Pereira": "佩雷拉", "Perović": "佩罗维奇",
    "Perrantes": "佩兰特斯", "Perry": "佩里", "Person": "珀森",
    "Peter": "彼得", "Peters": "彼得斯", "Peterson": "彼得森",
    "Petro": "佩特罗", "Petrusev": "彼得鲁舍夫", "Phillips": "菲利普斯",
    "Pickett": "皮克特", "Pietrus": "佩特鲁斯", "Pinckney": "平克尼",
    "Pinkney": "平克尼", "Pittman": "皮特曼", "Planinić": "普拉尼尼奇",
    "Pleiss": "普莱斯", "Plumlee": "普拉姆利", "Podkolzin": "波德科尔津",
    "Pokuševski": "波库舍夫斯基", "Pollard": "波拉德",
    "Pondexter": "庞德克斯特", "Ponds": "庞兹", "Pons": "庞斯",
    "Pope": "波普", "Porter": "波特", "Postell": "波斯特尔",
    "Potter": "波特", "Poulakidas": "普莱基达斯", "Powe": "鲍威",
    "Powell": "鲍威尔", "Poythress": "波伊思里斯",
    "Pressey": "普雷西", "Preston": "普雷斯顿", "Price": "普莱斯",
    "Prigioni": "普里吉奥尼", "Primo": "普里莫", "Proctor": "普罗克特",
    "Profit": "普罗菲特", "Prosper": "普罗斯珀", "Pruitt": "普鲁伊特",
    "Pullen": "普伦", "Pullin": "普林", "Purvis": "珀维斯",
    "Qi": "琦", "Quarterman": "夸特曼", "Queen": "奎因",
    "Quinn": "奎因", "Quinones": "基尼奥内斯", "Rabb": "拉布",
    "Radojevic": "拉多耶维奇", "Raduljica": "拉杜利察",
    "Rakocevic": "拉科切维奇", "Ramos": "拉莫斯", "Ramsey": "拉姆齐",
    "Randle": "兰德尔", "Randolph": "兰多夫",
    "Rathan-Mayes": "拉坦-梅斯", "Rautins": "劳廷斯", "Ray": "雷",
    "Reath": "里斯", "Rebraca": "雷布拉卡", "Recasner": "雷卡斯纳",
    "Reed": "里德", "Reese": "里斯", "Reeves": "里夫斯",
    "Reid": "里德", "Reiner": "赖纳", "Rentzias": "伦齐亚斯",
    "Respert": "雷斯珀特", "Reynolds": "雷诺兹", "Rhoden": "罗登",
    "Rhodes": "罗兹", "Richard": "理查德", "Richardson": "理查德森",
    "Richmond": "里士满", "Rigaudeau": "里戈多", "Riley": "莱利",
    "Riller": "里勒", "Rivers": "里弗斯", "Robbins": "罗宾斯",
    "Roberson": "罗伯森", "Roberts": "罗伯茨", "Robertson": "罗伯逊",
    "Robinson": "罗宾逊", "Roddy": "罗迪", "Rodriguez": "罗德里格斯",
    "Rogers": "罗杰斯", "Rooks": "鲁克斯", "Ross": "罗斯",
    "Rowe": "罗维", "Rozier": "罗齐尔", "Rucker": "拉克",
    "Rudež": "鲁德兹", "Ruffin": "拉芬", "Rush": "拉什",
    "Russell": "拉塞尔", "Ryan": "瑞安", "Sacre": "萨克尔",
    "Salley": "萨利", "Sallis": "萨利斯", "Salvadori": "萨尔瓦多里",
    "Samake": "萨马凯", "Samanic": "萨马尼奇", "Samb": "桑布",
    "Sampson": "桑普森", "Samuels": "塞缪尔斯", "Sanchez": "桑切斯",
    "Sanders": "桑德斯", "Sandfort": "桑德福特", "Sanogo": "萨诺戈",
    "Santiago": "圣地亚哥", "Santos": "桑托斯", "Saraf": "萨拉夫",
    "Sarr": "萨尔", "Sasser": "萨瑟", "Satoranský": "萨托兰斯基",
    "Satterfield": "萨特菲尔德", "Savović": "萨沃维奇",
    "Scalabrine": "斯卡拉布莱恩", "Scales": "斯凯尔斯",
    "Schakel": "沙克尔", "Schayes": "沙耶斯", "Scheffler": "舍夫勒",
    "Scheierman": "沙伊尔曼", "Schenscher": "申舍尔",
    "Schofield": "斯科菲尔德", "Scott": "斯科特", "Scrubb": "斯克鲁布",
    "Seabron": "西布伦", "Seals": "西尔斯", "Sears": "西尔斯",
    "Sefolosha": "塞弗罗萨", "Selby": "塞尔比", "Selden": "塞尔登",
    "Sene": "塞内", "Sesay": "塞赛", "Shackleford": "沙克尔福德",
    "Shakur": "沙库尔", "Shammgod": "沙姆戈德", "Sharpe": "夏普",
    "Shaw": "肖", "Shayok": "沙约克", "Shengelia": "申格利亚",
    "Sheppard": "谢泼德", "Shirley": "雪莉", "Shulga": "舒尔加",
    "Shumpert": "香珀特", "Shved": "什维德", "Sibert": "西伯特",
    "Silas": "赛拉斯", "Siler": "赛勒", "Silva": "席尔瓦",
    "Simien": "西米恩", "Simmons": "西蒙斯", "Simonović": "西莫诺维奇",
    "Simpson": "辛普森", "Sims": "西姆斯", "Singler": "辛格勒",
    "Singletary": "辛格尔塔里", "Singleton": "辛格尔顿",
    "Siva": "西瓦", "Skapintsev": "斯卡平采夫", "Slater": "斯莱特",
    "Slawson": "斯劳森", "Slay": "斯莱", "Sloan": "斯隆",
    "Slokar": "斯洛卡", "Small": "斯莫尔", "Smart": "斯马特",
    "Smith": "史密斯", "Sneed": "斯尼德", "Snell": "斯内尔",
    "Snyder": "斯奈德", "Solomon": "所罗门", "Songaila": "宋盖拉",
    "Southerland": "萨瑟兰", "Sow": "索", "Spalding": "斯波尔丁",
    "Spanoulis": "斯潘诺利斯", "Spencer": "斯宾塞", "Stack": "斯塔克",
    "Stanley": "斯坦利", "Stauskas": "斯塔斯卡斯",
    "Steigenga": "斯泰根加", "Stepania": "斯特潘尼亚",
    "Stephens": "斯蒂芬斯", "Stepheson": "斯蒂芬森",
    "Stevens": "史蒂文斯", "Stewart": "斯图尔特",
    "Stiemsma": "施蒂恩斯马", "Stockton": "斯托克顿",
    "Stokes": "斯托克斯", "Stone": "斯通", "Storey": "斯托里",
    "Stoudamire": "斯塔德迈尔", "Strawberry": "斯特罗贝里",
    "Strickland": "斯特里克兰", "Strong": "斯特朗",
    "Summers": "萨默斯", "Sumner": "萨姆纳", "Sun": "孙",
    "Sundov": "孙多夫", "Swanigan": "斯瓦尼根",
    "Sweetney": "斯威特尼", "Swider": "斯威德", "Swift": "斯威夫特",
    "Sword": "斯沃德", "Sy": "西", "Sykes": "赛克斯", "Szabó": "萨博",
    "Tabak": "塔巴克", "Tabuse": "田卧", "Taft": "塔夫特",
    "Tavares": "塔瓦雷斯", "Taylor": "泰勒", "Teague": "蒂格",
    "Teletović": "泰莱托维奇", "Telfort": "特尔福",
    "Teodosić": "特奥多西奇", "Terrell": "特雷尔", "Terry": "特里",
    "Teske": "特斯克", "Thiero": "蒂耶罗", "Thomas": "托马斯",
    "Thompkins": "汤普金斯", "Thompson": "汤普森",
    "Thornton": "索顿", "Thornwell": "索恩韦尔", "Tillie": "蒂利",
    "Timme": "蒂米", "Tisdale": "蒂斯代尔", "Tobey": "托比",
    "Todd": "托德", "Tolliver": "托利弗", "Tomlin": "汤姆林",
    "Tonje": "通杰", "Topić": "托皮奇", "Toppin": "托平",
    "Torres": "托雷斯", "Toupane": "图帕内", "Tower": "托维尔",
    "Traore": "特拉奥雷", "Travers": "特拉弗斯",
    "Trepagnier": "特雷帕尼耶", "Trier": "特里尔",
    "Trybanski": "特里班斯基", "Tsakalidis": "察卡利迪斯",
    "Tshiebwe": "奇布韦", "Tskitishvili": "茨基蒂什维利",
    "Tucker": "塔克", "Turkcan": "蒂尔克坎", "Turner": "特纳",
    "Tyler": "泰勒", "Tyson": "泰森", "Ubiles": "乌比莱斯",
    "Udoka": "乌多卡", "Ukić": "乌基奇", "Ulis": "尤利斯",
    "Umude": "乌穆德", "Uthoff": "尤索夫", "Uzoh": "乌佐",
    "Vanterpool": "范特普尔", "Varda": "瓦尔达", "Varnado": "瓦尔纳多",
    "Vaughn": "沃恩", "Vezenkov": "维岑科夫", "Vinicius": "维尼修斯",
    "Vinson": "文森", "Vonleh": "冯莱", "Voskuhl": "沃斯库尔",
    "Vranes": "弗拉内什", "Vranković": "弗兰科维奇",
    "Vroman": "弗罗曼", "Wagner": "瓦格纳", "Wainright": "温赖特",
    "Walker": "沃克", "Wallace": "华莱士", "Walsh": "沃尔什",
    "Walters": "沃尔特斯", "Ware": "韦尔", "Warney": "沃尼",
    "Warren": "沃伦", "Washburn": "沃什伯恩",
    "Washington": "华盛顿", "Watford": "沃特福德", "Watkins": "沃特金斯",
    "Watson": "沃森", "Wayns": "韦恩斯", "Wear": "韦尔",
    "Weatherspoon": "韦瑟斯庞", "Weaver": "韦弗", "Webb": "韦伯",
    "Weber": "韦伯", "Webster": "韦伯斯特", "Weems": "威姆斯",
    "Wells": "威尔斯", "Welsch": "韦尔施", "Welsh": "韦尔什",
    "Werdann": "沃丹", "West": "韦斯特", "Whaley": "惠利",
    "Whatley": "沃特利", "Wheat": "惠特", "Wheeler": "惠勒",
    "White": "怀特", "Whitehead": "怀特黑德",
    "Whiteside": "怀特塞德", "Whitmore": "惠特莫尔",
    "Whitney": "惠特尼", "Whittington": "惠廷顿",
    "Wieskamp": "威斯坎普", "Wigginton": "威金顿", "Wilcox": "威尔科克斯",
    "Wiley": "威利", "Wilkins": "威尔金斯", "Wilks": "威尔克斯",
    "Williams": "威廉姆斯", "Williamson": "威廉姆森",
    "Willoughby": "威洛比", "Wilson": "威尔逊", "Wiltjer": "威尔杰",
    "Windler": "温德勒", "Wingate": "温盖特", "Winston": "温斯顿",
    "Winter": "温特", "Withey": "威希", "Wolf": "沃尔夫",
    "Wolkowyski": "沃尔科夫斯基", "Wolters": "沃尔特斯",
    "Wong": "黄", "Wood": "伍德", "Woods": "伍兹",
    "Workman": "沃克曼", "Wright": "赖特", "Yarbrough": "亚伯勒",
    "Yongxi": "永熙", "York": "约克", "Young": "杨",
    "Youngblood": "扬布拉德", "Yurtseven": "尤尔特塞文",
    "Zeller": "泽勒", "Zhi-zhi": "治郅", "Zidek": "齐德克",
    "Zikarsky": "齐卡尔斯基", "Zimmerman": "齐默尔曼",
    "Zipser": "齐普瑟", "Žižić": "日日奇",
    # 变音符兼容（数据源多为无变音符形式）
    "Vrankovic": "弗兰科维奇", "Szabo": "萨博", "Milic": "米利奇",
    "Savovic": "萨沃维奇", "Pavlovic": "帕夫洛维奇", "Planinic": "普拉尼尼奇",
    "Ukic": "乌基奇", "Perovic": "佩罗维奇", "Motiejunas": "莫泰尤纳斯",
    "Satoransky": "萨托兰斯基", "Teletovic": "泰莱托维奇",
    "Nedovic": "内多维奇", "Rudez": "鲁德兹", "Dragic": "德拉季奇",
    "Zizic": "日日奇", "Teodosic": "特奥多西奇", "Guduric": "古杜里奇",
    "Pokusevski": "波库舍夫斯基", "Simonovic": "西莫诺维奇",
    "Diabate": "迪亚巴特", "Manon": "马尼翁", "Mañon": "马尼翁",
}


def compose_zh_full(full_name):
    """终极组合：FULL_CN 精确匹配 → 组件组合（合并 zh_names_extra 词典，含 II/III/Jr 后缀处理）"""
    if not full_name or not isinstance(full_name, str):
        return None
    name = full_name.strip()
    if name in FULL_CN:
        return FULL_CN[name]
    # 合并 zh_names_extra 的既有词典（跨词典组合：Dan(旧)+Schayes(新)）
    try:
        from zh_names_extra import FIRST_DICT as _F0, LAST_DICT as _L0
    except ImportError:
        _F0, _L0 = {}, {}
    def _first(k):
        return FIRST_EXTRA.get(k) or _F0.get(k)
    def _last(k):
        return LAST_EXTRA.get(k) or _L0.get(k)
    # 去掉后缀（II/III/IV/Jr/Jr./Sr）单独处理
    parts = name.replace(".", "").split()
    if not parts:
        return None
    SUFFIX_ZH = {"II": "二世", "III": "三世", "IV": "四世", "Jr": "小", "Sr": "老"}
    suffix_zh = None
    if parts[-1] in SUFFIX_ZH and len(parts) >= 3:
        suffix_zh = SUFFIX_ZH[parts[-1]]
        parts = parts[:-1]
    if len(parts) < 2:
        return None
    # 名 = 第一段（支持带撇号/连字符），姓 = 最后一段
    first = parts[0]
    last = parts[-1]
    zh_first = _first(first) or _first(first.replace("'", ""))
    zh_last = _last(last) or _last(last.replace("'", ""))
    if not zh_first or not zh_last:
        return None
    base = zh_first + "·" + zh_last
    return ("小" if suffix_zh == "小" else "") + base + (suffix_zh if suffix_zh and suffix_zh != "小" else "")
