# -*- coding: utf-8 -*-
# 历史球员中文译名扩展词典
# 策略：
#   1. FULL_EXTRA —— 知名球员全名精确映射（优先级最高）
#   2. FIRST_DICT / LAST_DICT —— 名/姓组件词典，组合生成"名·姓"
# 由 scripts/gen_history.py 引用；未匹配者保留英文名（多为冷门替补）

# ============ 知名球员全名（精确匹配） ============
FULL_EXTRA = {
    # ---- 90+ 全明星/超巨 ----
    "Jermaine O'Neal": "杰梅因·奥尼尔", "Yao Ming": "姚明", "Hassan Whiteside": "哈桑·怀特塞德",
    "David Lee": "大卫·李", "Kevin Johnson": "凯文·约翰逊", "Arvydas Sabonis": "阿维达斯·萨博尼斯",
    "DeAndre Jordan": "德安德烈·乔丹", "Clyde Drexler": "克莱德·德雷克斯勒",
    "Steve Francis": "史蒂夫·弗朗西斯", "Chris Kaman": "克里斯·卡曼",
    "Eric Bledsoe": "埃里克·布莱索", "Kendall Gill": "肯德尔·吉尔",
    "Michael Finley": "迈克尔·芬利", "Michael Redd": "迈克尔·里德",
    "Nene": "内内", "Luis Scola": "路易斯·斯科拉", "David West": "大卫·韦斯特",
    "Tyreke Evans": "泰瑞克·埃文斯", "Montrezl Harrell": "蒙特雷斯·哈雷尔",
    "Kurt Thomas": "科特·托马斯", "Drew Gooden": "德鲁·古登",
    "Roy Hibbert": "罗伊·希伯特", "George Hill": "乔治·希尔",
    "Jeremy Lin": "林书豪", "Kevin Porter Jr.": "凯文·波特二世",
    "Bison Dele": "比森·德勒", "Bryant Reeves": "布莱恩特·里夫斯",
    "Richard Jefferson": "理查德·杰弗森", "Nate Robinson": "内特·罗宾逊",
    "Nikola Pekovic": "尼古拉·佩科维奇", "Kyle Kuzma": "凯尔·库兹马",
    "Mark Jackson": "马克·杰克逊", "Kevin Willis": "凯文·威利斯",
    "Jamaal Magloire": "贾马尔·马格洛伊尔", "JR Smith": "JR·史密斯",
    "Jarrett Jack": "贾莱特·杰克", "Andris Biedrins": "安德里斯·比德林斯",
    "Raef LaFrentz": "拉夫·拉弗伦茨", "Donyell Marshall": "多尼尔·马歇尔",
    "Shawn Bradley": "肖恩·布拉德利", "Darrell Armstrong": "达雷尔·阿姆斯特朗",
    "Brevin Knight": "布雷文·奈特", "Charlie Villanueva": "查理·维拉纽瓦",
    "T.J. Ford": "TJ·福特", "Kris Humphries": "克里斯·亨弗里斯",
    "Kyle O'Quinn": "凯尔·奥奎因", "Steven Smith": "史蒂文·史密斯",
    "Lamond Murray": "拉蒙德·穆雷", "Rodney Rogers": "罗德尼·罗杰斯",
    "Danny Fortson": "丹尼·福特森", "Keon Clark": "基翁·克拉克",
    "Ruben Patterson": "鲁本·帕特森", "Rafer Alston": "拉夫·阿尔斯通",
    "Luke Ridnour": "卢克·里德诺", "Matt Geiger": "马特·盖格",
    "Joe Smith": "乔·史密斯", "Mike James": "迈克·詹姆斯",
    "David Wesley": "大卫·韦斯利", "Clar. Weatherspoon": "克拉伦斯·威瑟斯庞",
    "Larry Sanders": "拉里·桑德斯", "Byron Scott": "拜伦·斯科特",
    # ---- 80-89 档知名球员 ----
    "Detlef Schrempf": "德特雷夫·施拉姆夫", "Rik Smits": "里克·施密茨",
    "Dale Davis": "戴尔·戴维斯", "Antonio Davis": "安东尼奥·戴维斯",
    "Derrick McKey": "德里克·麦基", "Vin Baker": "文·贝克",
    "Terrell Brandon": "特雷尔·布兰登", "Bobby Phills": "鲍比·菲尔斯",
    "Glen Rice": "格伦·莱斯", "Anthony Mason": "安东尼·梅森",
    "Derrick Coleman": "德里克·科尔曼", "Kenny Anderson": "肯尼·安德森",
    "Latrell Sprewell": "拉特里尔·斯普雷维尔", "PJ Brown": "PJ·布朗",
    "Elden Campbell": "埃尔登·坎贝尔", "Brian Grant": "布莱恩·格兰特",
    "Isaiah Rider": "以赛亚·莱德", "Jamal Mashburn": "贾马尔·马什本",
    "Allan Houston": "阿兰·休斯顿", "Charlie Ward": "查理·沃德",
    "Chris Childs": "克里斯·柴尔兹", "Marcus Camby": "马库斯·坎比",
    "Shareef Abdur-Rahim": "沙里夫·阿卜杜尔-拉希姆", "Jerry Stackhouse": "杰里·斯塔克豪斯",
    "Joe Dumars": "乔·杜马斯", "Grant Hill": "格兰特·希尔",
    "Lindsey Hunter": "林赛·亨特", "Terry Mills": "特里·米尔斯",
    "Otis Thorpe": "奥蒂斯·索普", "Sean Elliott": "肖恩·埃利奥特",
    "Avery Johnson": "埃弗里·约翰逊", "Mario Elie": "马里奥·埃利",
    "Robert Horry": "罗伯特·霍里", "Sam Cassell": "萨姆·卡塞尔",
    "Mario Bennett": "马里奥·贝内特", "Walt Williams": "沃尔特·威廉姆斯",
    "Dana Barros": "达纳·巴罗斯", "Wesley Person": "韦斯利·珀森",
    "Travis Best": "特拉维斯·贝斯特", "Antoine Carr": "安托万·卡尔",
    "Olden Polynice": "奥登·波利尼斯", "Felton Spencer": "费尔顿·斯宾塞",
    "Blue Edwards": "布鲁·爱德华兹", "Todd Day": "托德·戴",
    "Cedric Ceballos": "塞德里克·塞巴洛斯", "Doug West": "道格·韦斯特",
    "Loy Vaught": "洛伊·沃特", "Terry Porter": "特里·波特",
    "Cliff Robinson": "克利福德·罗宾逊", "Rod Strickland": "罗德·斯特里克兰",
    "Calbert Cheaney": "卡尔伯特·切尼", "Bryon Russell": "布莱恩·拉塞尔",
    "Adam Keefe": "亚当·基夫", "Shandon Anderson": "香农·安德森",
    "Howard Eisley": "霍华德·艾斯利", "Jacque Vaughn": "雅克·沃恩",
    "Greg Ostertag": "格雷格·奥斯特塔格", "Shaq O'Neal": "沙奎尔·奥尼尔",
    "Bryce Drew": "布莱斯·德鲁", "Matt Maloney": "马特·马洛尼",
    "Kevin Ollie": "凯文·奥利", "Eric Snow": "埃里克·斯诺",
    "Aaron McKie": "阿隆·麦基", "George Lynch": "乔治·林奇",
    "Tyrone Hill": "泰隆·希尔", "Kukoc": "托尼·库科奇",
    "Hersey Hawkins": "赫西·霍金斯", "Don MacLean": "唐·麦克莱恩",
    "Tom Gugliotta": "汤姆·古格里奥塔", "Rex Chapman": "雷克斯·查普曼",
    "Wesley Person ": "韦斯利·珀森", "Bimbo Coles": "宾博·科尔斯",
    "Muggsy Bogues": "马格西·博格斯", "Dell Curry": "戴尔·库里",
    "Kenny Smith": "肯尼·史密斯", "Matt Bullard": "马特·布拉德",
    "Sam Perkins": "萨姆·珀金斯", "Mario Elie ": "马里奥·埃利",
    "Vernon Maxwell": "弗农·麦克斯韦尔", "Carl Herrera": "卡尔·埃雷拉",
    "Chucky Brown": "查基·布朗", "Tony Massenburg": "托尼·马森伯格",
    "Anthony Bowie": "安东尼·鲍伊", "Rumeal Robinson": "鲁米尔·罗宾逊",
    "Litterial Green": "利特里亚尔·格林", "Brook Steppe": "布鲁克·斯特普",
    "Duane Ferrell": "杜安·费雷尔", "Dyron Nix": "戴伦·尼克斯",
    "Mike Iuzzolino": "迈克·尤佐利诺", "Anthony Goldwire": "安东尼·戈德维尔",
    "Cowens": "戴夫·考恩斯", "Manute Bol": "马努特·波尔",
    "Gheorghe Muresan": "格奥尔基·穆雷桑", "Dennis Scott": "丹尼斯·斯科特",
    "Nick Anderson": "尼克·安德森", "Donald Royal": "唐纳德·罗亚尔",
    "Scott Skiles": "斯科特·斯凯尔斯", "Jeff Turner": "杰夫·特纳",
    "Greg Kite": "格雷格·凯特", "Terry Catledge": "特里·卡特利奇",
    "Jerry Reynolds": "杰里·雷诺兹", "Reggie Theus": "雷吉·修斯",
    "Steve Smith": "史蒂夫·史密斯", "Grant Long": "格兰特·朗",
    "Allan Bristow": "阿兰·布里斯托", "Frank Brickowski": "弗兰克·布里科夫斯基",
    "Ricky Pierce": "里基·皮尔斯", "Jay Humphries": "杰伊·汉弗莱斯",
    "Fred Roberts": "弗雷德·罗伯茨", "Mark Acres": "马克·埃克斯",
    "Jim Les": "吉姆·莱斯", "Danny Ainge": "丹尼·安吉",
    "Danny Schayes": "丹尼·沙耶斯", "Michael Adams": "迈克尔·亚当斯",
    "Bernard King": "伯纳德·金", "Buck Williams": "巴克·威廉姆斯",
    "Chris Morris": "克里斯·莫里斯", "Tate George": "塔特·乔治",
    "Derrick Chievous": "德里克·奇沃斯", "Roy Hinson": "罗伊·辛森",
    "Drazen Petrovic": "德拉赞·彼得洛维奇", "Rolando Blackman": "罗兰多·布莱克曼",
    "Brad Daugherty": "布拉德·多尔蒂", "Larry Nance": "拉里·南斯",
    "Mark Price": "马克·普莱斯", "Craig Ehlo": "克雷格·埃洛",
    "Hot Rod Williams": "热罗德·威廉姆斯", "Steve Kerr": "史蒂夫·科尔",
    "Willie Anderson": "威利·安德森", "Vern Fleming": "弗恩·弗莱明",
    "Michael Williams": "迈克尔·威廉姆斯", "Felton Spencer ": "费尔顿·斯宾塞",
    "Randy Wittman": "兰迪·威特曼", "Ledell Eackles": "莱德尔·伊克尔斯",
    "Tom Tolbert": "汤姆·托尔伯特", "Robert Pack": "罗伯特·帕克",
    "Lionel Simmons": "莱昂内尔·西蒙斯", "Hersey ": "赫西·霍金斯",
    "Bobby Hurley": "鲍比·赫利", "Rodney Rogers ": "罗德尼·罗杰斯",
    "Vincent Askew": "文森特·阿斯丘", "Anthony Cook": "安东尼·库克",
    "Dale Ellis": "戴尔·埃利斯", "Eddie Johnson": "埃迪·约翰逊",
    "Xavier McDaniel": "泽维尔·麦克丹尼尔", "Rickey Green": "里基·格林",
    "Thurl Bailey": "瑟尔·贝利", "Darrell Griffith": "达雷尔·格里菲斯",
    "Bob Hansen": "鲍勃·汉森", "David Benoit": "大卫·贝努瓦",
    "Blue Edwards ": "布鲁·爱德华兹", "Jay Vincent": "杰伊·文森特",
    "Sedale Threatt": "塞达尔·思雷特", "Benoit Benjamin": "贝努瓦·本杰明",
    "Kenny Battle": "肯尼·巴特尔", "Jeff Grayer": "杰夫·格雷尔",
    "Rory Sparrow": "罗里·斯帕罗", "Doc Rivers": "道格·里弗斯",
    "Danny Ferry": "丹尼·费里", "Steve Alford": "史蒂夫·阿尔福德",
    "Dan Majerle": "丹·马杰尔", "Kevin Johnson ": "凯文·约翰逊",
    "Tyrone Corbin": "泰隆·科尔宾", "Mark West": "马克·韦斯特",
    "Craig Neal": "克雷格·尼尔", "Tim Perry": "蒂姆·佩里",
    "Armon Gilliam": "阿蒙·吉利亚姆", "Rick Mahorn": "里克·马洪",
    "Lancaster Gordon": "兰卡斯特·戈登", "Fred Cofield": "弗雷德·科夫菲尔德",
    "Jerome Kersey": "杰罗姆·克西", "Terry Teagle": "特里·蒂格尔",
    "Byron Irvin": "拜伦·欧文", "Dexter Westbrook": "德克斯特·威斯布鲁克",
    "Greg Anthony": "格雷格·安东尼", "Darrick Martin": "达里克·马丁",
    "Loy Vaught ": "洛伊·沃特", "P.J. Brown": "PJ·布朗",
    "Kerry Kittles": "凯里·基特尔斯", "Khalid Reeves": "哈立德·里夫斯",
    "Yari Korolev": "亚里·科罗列夫", "Joe Kleine": "乔·克莱恩",
    "Cliff Levingston": "克利夫·莱文斯顿", "Ed Nealy": "埃德·尼利",
    "Will Perdue": "威尔·珀杜", "Stacey King": "斯泰西·金",
    "BJ Armstrong": "BJ·阿姆斯特朗", "Craig Hodges": "克雷格·霍奇斯",
    "Scott Williams": "斯科特·威廉姆斯", "Randolph Keys": "伦道夫·基斯",
    "Keith Smart": "基思·斯马特", "Byron Dinkins": "拜伦·丁金斯",
    "Shelton Jones": "谢尔顿·琼斯", "Dave Hoppen": "戴夫·霍彭",
    "Rich Morton": "里奇·莫顿", "Jim Rowinski": "吉姆·罗温斯基",
    "Michael Ansley": "迈克尔·安斯利", "Anthony Bonner": "安东尼·邦纳",
    "Gerald Glass": "杰拉尔德·格拉斯", "Travis Mays": "特拉维斯·梅斯",
    "Litterial ": "利特里亚尔·格林", "Tod Murphy": "托德·墨菲",
    " Andrew Lang": "安德鲁·兰", "Christian Welp": "克里斯蒂安·韦尔普",
    "Dallas Comegys": "达拉斯·科梅吉斯", "Ronnie Murphy": "罗尼·墨菲",
    "Rick Fox": "里克·福克斯", "Cedric Sabourin": "塞德里克·萨布林",
    "Dwayne Schintzius": "德韦恩·辛齐厄斯", "Aleksandar Djordjevic": "亚历山大·乔尔杰维奇",
    "Brian Quinnett": "布莱恩·奎内特", "Mookie Blaylock": "穆基·布莱洛克",
    "Dana Barros ": "达纳·巴罗斯", "Brian Shaw": "布莱恩·肖",
    "Dee Brown": "迪·布朗", "Kevin Brooks": "凯文·布鲁克斯",
    "Conrad McRae": "康拉德·麦克雷", "Keith Askins": "基思·阿斯金斯",
    "Grant Gondrezick": "格兰特·冈德雷齐克", "Greg Grant": "格雷格·格兰特",
    "Tony Campbell": "托尼·坎贝尔", "Brad Lohaus ": "布拉德·洛豪斯",
    "Mark Blount": "马克·布朗特", "Acie Earl": "阿西·厄尔",
    "Lou Roe": "卢·罗", "Eric Montross": "埃里克·蒙特罗斯",
    "Cliff Rozier": "克利福德·罗齐尔", "Eric Riley": "埃里克·莱利",
    "Monty Williams": "蒙蒂·威廉姆斯", "Dontonio Wingfield": "东托尼奥·温菲尔德",
    "Eric Williams": "埃里克·威廉姆斯", "Bill Curley": "比尔·柯利",
    "Greg Minor": "格雷格·迈纳", "Donyell ": "多尼尔·马歇尔",
    "Alan Henderson": "阿兰·亨德森", "Predrag Danilovic": "普雷德拉格·达尼洛维奇",
    "Khalid ": "哈立德·里夫斯", " Cory Alexander": "科里·亚历山大",
    "Jerome Allen": "杰罗姆·艾伦", "Lawrence Moten": "劳伦斯·莫滕",
    "Kenny Fields": "肯尼·菲尔兹", "Greg Graham": "格雷格·格雷厄姆",
    "Corie Blount": "科里·布朗特", "Ashraf Amaya": "阿什拉夫·阿马亚",
    "Bryce Drew ": "布莱斯·德鲁", "Miles Simon": "迈尔斯·西蒙",
    "Cuttino Mobley": "卡蒂诺·莫布里", "Rashard Lewis": "拉沙德·刘易斯",
    "Mike Bibby": "迈克·毕比", "Jason Williams": "杰森·威廉姆斯",
    "Raef ": "拉夫·拉弗伦茨", "Robert Traylor": "罗伯特·特雷勒",
    "Dirk Nowitzki": "德克·诺维茨基", "Paul Pierce": "保罗·皮尔斯",
    "Vince Carter": "文斯·卡特", "Antawn Jamison": "安托万·贾米森",
    "Mike Miller": "迈克·米勒", "Quentin Richardson": "昆汀·理查德森",
    "Darius Miles": "达柳斯·迈尔斯", "Keyon Dooling": "基翁·杜林",
    "Stromile Swift": "斯特罗迈尔·斯威夫特", "Marcus Fizer": "马库斯·费泽尔",
    "Chris Mihm": "克里斯·米姆", "Courtney Alexander": "考特尼·亚历山大",
    "Morris Peterson": "莫里斯·皮特森", "Zach Randolph": "扎克·兰多夫",
    "Shane Battier": "肖恩·巴蒂尔", "Jason Richardson": "杰森·理查德森",
    "Troy Murphy": "特洛伊·墨菲", "Eddy Curry": "埃迪·库里",
    "Tyson Chandler": "泰森·钱德勒", "Pau Gasol": "保罗·加索尔",
    "Joe Johnson": "乔·约翰逊", "Richard Hamilton": "理查德·汉密尔顿",
    "Gilbert Arenas": "吉尔伯特·阿里纳斯", "Carlos Boozer": "卡洛斯·布泽尔",
    "Amare Stoudemire": "阿玛雷·斯塔德迈尔", "Caron Butler": "卡隆·巴特勒",
    "Dwyane Wade": "德维恩·韦德", "Chris Bosh": "克里斯·波什",
    "LeBron James": "勒布朗·詹姆斯", "Carmelo Anthony": "卡梅罗·安东尼",
    "Kirk Hinrich": "柯克·辛里奇", "Josh Howard": "约什·霍华德",
    "Luol Deng": "罗尔·邓", "Ben Gordon": "本·戈登",
    "Dwight Howard": "德怀特·霍华德", "Andre Iguodala": "安德烈·伊戈达拉",
    "Emeka Okafor": "埃梅卡·奥卡福", "Devin Harris": "德文·哈里斯",
    "Shaun Livingston": "肖恩·利文斯顿", "Al Jefferson": "艾尔·杰弗森",
    "Josh Smith": "约什·史密斯", "J.R. Smith": "JR·史密斯",
    "Deron Williams": "德隆·威廉姆斯", "Chris Paul": "克里斯·保罗",
    "Charlie Villanueva ": "查理·维拉纽瓦", "Andrew Bogut": "安德鲁·博古特",
    "Channing Frye": "钱宁·弗莱", "Danny Granger": "丹尼·格兰杰",
    "Raymond Felton": "雷蒙德·费尔顿", "Andrew Bynum": "安德鲁·拜纳姆",
    "Monta Ellis": "蒙塔·埃利斯", "Brandon Roy": "布兰登·罗伊",
    "LaMarcus Aldridge": "拉马库斯·阿尔德里奇", "Adam Morrison": "亚当·莫里森",
    "Tyrus Thomas": "泰伦斯·托马斯", "Shelden Williams": "谢尔顿·威廉姆斯",
    "Brandon Jennings": "布兰登·詹宁斯", "Stephen Curry": "斯蒂芬·库里",
    "James Harden": "詹姆斯·哈登", "Ricky Rubio": "里基·卢比奥",
    "DeMar DeRozan": "德马尔·德罗赞", "Blake Griffin": "布雷克·格里芬",
    "Hasheem Thabeet": "哈希姆·塔比特", "Jonny Flynn": "强尼·弗林",
    "Evans": "泰瑞克·埃文斯", "Brandon Knight": "布兰登·奈特",
    "Kemba Walker": "肯巴·沃克", "Klay Thompson": "克莱·汤普森",
    "Kawhi Leonard": "科怀·伦纳德", "Festus Ezeli": "费斯图斯·埃泽利",
    "Jimmy Butler": "吉米·巴特勒", "Kyrie Irving": "凯里·欧文",
    "Dion Waiters": "迪昂·维特斯", "Harrison Barnes": "哈里森·巴恩斯",
    "Damian Lillard": "达米安·利拉德", "Andre Drummond": "安德烈·德拉蒙德",
    "Anthony Davis": "安东尼·戴维斯", "Bradley Beal": "布拉德利·比尔",
    "Dion ": "迪昂·维特斯", "Cody Zeller": "科迪·泽勒",
    "Alex Len": "阿莱克斯·伦", "Nerlens Noel": "纳伦斯·诺埃尔",
    "Otto Porter": "奥托·波特", "Victor Oladipo": "维克托·奥拉迪波",
    "CJ McCollum": "CJ·麦科勒姆", "Steven Adams": "史蒂文·亚当斯",
    "Giannis Antetokounmpo": "扬尼斯·阿德托昆博", "Gary Harris": "加里·哈里斯",
    "Julius Randle": "朱利叶斯·兰德尔", "Dario Saric": "达里奥·萨里奇",
    "Domantas Sabonis": "多曼塔斯·萨博尼斯", "Buddy Hield": "巴迪·希尔德",
    "Jamal Murray": "贾马尔·穆雷", "Jaylen Brown": "杰伦·布朗",
    "Brandon Ingram": "布兰登·英格拉姆", "Jayson Tatum": "杰森·塔图姆",
    "Lonzo Ball": "朗佐·鲍尔", "De'Aaron Fox": "德阿龙·福克斯",
    "Josh Jackson": "约什·杰克逊", "Zach Collins": "扎克·科林斯",
    "Luka Doncic": "卢卡·东契奇", "Trae Young": "特雷·杨",
    "Deandre Ayton": "德安德烈·艾顿", "Marvin Bagley": "马文·巴格利",
    "Jaren Jackson": "贾伦·杰克逊", "Shai Gilgeous-Alexander": "谢伊·吉尔杰斯-亚历山大",
    "Zion Williamson": "锡安·威廉姆森", "Ja Morant": "贾·莫兰特",
    "RJ Barrett": "RJ·巴雷特", "Darius Garland": "达柳斯·加兰",
    "Cole Anthony": "科尔·安东尼", "LaMelo Ball": "拉梅洛·鲍尔",
    "Anthony Edwards": "安东尼·爱德华兹", "James Wiseman": "詹姆斯·怀斯曼",
    "Cade Cunningham": "凯德·坎宁安", "Jalen Green": "杰伦·格林",
    "Evan Mobley": "埃文·莫布利", "Scottie Barnes": "斯科蒂·巴恩斯",
    "Franz Wagner": "弗朗茨·瓦格纳", "Paolo Banchero": "保罗·班切罗",
    "Chet Holmgren": "切特·霍姆格伦", "Jabari Smith": "贾巴里·史密斯",
    "Keegan Murray": "基根·穆雷", "Victor Wembanyama": "维克托·文班亚马",
    "Scoot Henderson": "斯库特·亨德森", "Brandon Miller": "布兰登·米勒",
    "Ausar Thompson": "奥萨尔·汤普森", "Amen Thompson": "阿门·汤普森",

    # ===== 巅峰 o>=80 补漏（历史知名轮换/全明星，2026-09 校准批次） =====
    "Nene": "内内",
    "Jose Calderon": "何塞·卡尔德隆", "Andrea Bargnani": "安德烈亚·巴尼亚尼",
    "Spencer Hawes": "斯宾瑟·霍伊斯", "Anthony Randolph": "安东尼·兰多夫",
    "JJ Hickson": "JJ·希克森", "Greivis Vasquez": "格雷维斯·瓦斯奎兹",
    "Jared Sullinger": "贾里德·萨林杰", "Jahlil Okafor": "贾利尔·奥卡福",
    "Willie Cauley-Stein": "威利·考利-斯坦", "Rondae Hollis-Jefferson": "龙达·霍利斯-杰弗森",
    "Bo Outlaw": "博·奥特洛", "Chris Mullin": "克里斯·穆林",
    "Dominique Wilkins": "多米尼克·威尔金斯", "Rasho Nesterovic": "拉沙德·内斯特洛维奇",
    "Kenny Thomas": "肯尼·托马斯", "Samuel Dalembert": "塞缪尔·戴勒姆波特",
    "Bobby Simmons": "博比·西蒙斯", "Chris Andersen": "克里斯·安德森",
    "Nenad Krstic": "内纳德·科斯蒂奇", "Dan Gadzuric": "丹·加德祖里奇",
    "Andres Nocioni": "安德烈斯·诺西奥尼", "Sean May": "肖恩·梅",
    "Amir Johnson": "阿米尔·约翰逊", "Rodney Stuckey": "罗德尼·斯塔基",
    "Ramon Sessions": "雷蒙·塞申斯", "Darren Collison": "达伦·科里森",
    "Marcus Thornton": "马库斯·索顿", "Cole Aldrich": "科尔·阿尔德里奇",
    "Ish Smith": "伊什·史密斯", "Chandler Parsons": "钱德勒·帕森斯",
    "Jeremy Lamb": "杰里米·兰姆", "John Henson": "约翰·亨森",
    "Tyler Zeller": "泰勒·泽勒", "Gorgui Dieng": "戈尔吉·迪昂",
    "Marvin Bagley III": "马文·巴格利三世", "Kon Knueppel": "康·克努佩尔",
    "Derik Queen": "德里克·奎因", "Dino Radja": "迪诺·拉德加",
    "John Starks": "约翰·斯塔克斯", "Lorenzen Wright": "洛伦岑·赖特",
    "John Wallace": "约翰·华莱士", "Jerome Williams": "杰罗姆·威廉姆斯",
    "Malik Rose": "马利克·罗斯", "Erick Strickland": "埃里克·斯特里克兰",
    "Chucky Atkins": "查基·阿特金斯", "Aaron Williams": "亚伦·威廉姆斯",
    "Adonal Foyle": "阿多纳尔·福伊尔", "Alvin Williams": "阿尔文·威廉姆斯",
    "Earl Boykins": "厄尔·博伊金斯", "Todd MacCulloch": "托德·麦卡洛克",
    "Joel Przybilla": "乔尔·普尔兹比拉", "Chris Wilcox": "克里斯·威尔考克斯",
    "John Salmons": "约翰·萨尔蒙斯", "Zaza Pachulia": "扎扎·帕楚里亚",
    "Ian Mahinmi": "伊安·马辛米", "J.J. Barea": "JJ·巴里亚",
    "Brandan Wright": "布兰丹·赖特", "Omer Asik": "欧米尔·阿西克",
    "Lance Stephenson": "兰斯·史蒂芬森", "Tony Wroten": "托尼·罗腾",
    "Kent Bazemore": "肯特·贝兹莫尔", "Alan Williams": "阿兰·威廉姆斯",
    "Goga Bitadze": "戈加·比塔泽", "Saddiq Bey": "萨迪克·贝",
    "Scotty Pippen Jr.": "斯科蒂·皮蓬二世", "Tracy Murray": "特雷西·穆雷",
    "Chris Mills": "克里斯·米尔斯", "Billy Owens": "比利·欧文斯",
    "Jeff McInnis": "杰夫·麦金尼斯", "Tim Thomas": "蒂姆·托马斯",
    "Maurice Taylor": "莫里斯·泰勒", "Michael Dickerson": "迈克尔·迪克森",
    "Nazr Mohammed": "纳兹尔·穆罕默德", "Jahidi White": "贾希迪·怀特",
    "Tyrone Nesby": "蒂龙·内斯比", "Calvin Booth": "卡尔文·布斯",
    "Desmond Mason": "德斯蒙德·梅森", "Earl Watson": "厄尔·沃特森",
    "Nick Collison": "尼克·科里森", "Travis Outlaw": "特拉维斯·奥特洛",
    "Kendrick Perkins": "肯德里克·帕金斯", "JJ Redick": "JJ·雷迪克",
    "Ronnie Brewer": "罗尼·布鲁尔", "Jason Thompson": "杰森·汤普森",
    "DeJuan Blair": "德胡安·布莱尔", "Patrick Beverley": "帕特里克·贝弗利",
    "Reggie Williams": "雷吉·威廉姆斯", "Evan Turner": "埃文·特纳",
    "Delon Wright": "德隆·赖特", "Jae'Sean Tate": "杰肖恩·塔特",
    "Brandon Williams": "布兰登·威廉姆斯", "Cam Spencer": "卡姆·斯宾塞",
    "Dylan Harper": "迪伦·哈珀", "Bryant Stith": "布莱恩特·斯蒂斯",
    "Armen Gilliam": "阿门·吉利安", "Sam Mitchell": "萨姆·米切尔",
    "Carlos Rogers": "卡洛斯·罗杰斯", "Malik Sealy": "马利克·希利",
    "Vitaly Potapenko": "维塔利·波塔潘科", "Michael Stewart": "迈克尔·斯图尔特",
    "Mikki Moore": "米基·摩尔", "Brian Skinner": "布莱恩·斯金纳",
    "Dan Dickau": "丹·迪考", "Flip Murray": "弗利普·穆雷",
    "Darko Milicic": "达科·米利西奇", "Francisco Garcia": "弗朗西斯科·加西亚",
    "CJ Miles": "CJ·迈尔斯", "Jamario Moon": "贾马里奥·穆恩",
    "Jerryd Bayless": "杰拉德·贝勒斯", "Darrell Arthur": "达雷尔·亚瑟",
    "Rodrigue Beaubois": "罗德里格·博布瓦", "Jodie Meeks": "乔迪·米克斯",
    "Marcus Morris Sr.": "马库斯·莫里斯", "Jon Leuer": "乔恩·勒尤",
    "Davis Bertans": "戴维斯·贝尔坦斯", "Shabazz Muhammad": "沙巴兹·穆罕默德",
    "Justise Winslow": "贾斯蒂斯·温斯洛", "Hamidou Diallo": "哈米杜·迪亚洛",
    "Collin Gillespie": "科林·吉莱斯皮", "Jeremiah Fears": "杰里迈亚·费尔斯",
    "Maxime Raynaud": "马克西姆·雷诺", "Cedric Coward": "塞德里克·科沃德",
}

# ============ 名字组件词典 ============
FIRST_DICT = {
    # A
    "Aaron": "阿隆", "Abdul": "阿卜杜勒", "Adam": "亚当", "Alan": "阿兰", "Albert": "阿尔伯特",
    "Alec": "亚历克", "Alex": "亚历克斯", "Alexander": "亚历山大", "Alfonzo": "阿尔方索",
    "Al": "艾尔", "Ali": "阿里", "Allan": "阿兰", "Allen": "阿伦", "Alonzo": "阿朗佐",
    "Amare": "阿玛雷", "Andre": "安德烈", "Andrei": "安德烈", "Andrew": "安德鲁",
    "Anthony": "安东尼", "Antoine": "安托万", "Antawn": "安托万", "Antonio": "安东尼奥",
    "Ariel": "阿里尔", "Archie": "阿奇", "Armen": "阿门", "Arnold": "阿诺德", "Art": "阿特",
    "Austin": "奥斯汀", " Avery": "艾弗里", "Avery": "艾弗里",
    # B
    "Baron": "拜伦", "Barry": "巴里", "Beno": "贝诺", "Bernard": "伯纳德", "Bill": "比尔",
    "Billy": "比利", "Blake": "布雷克", "Bob": "鲍勃", "Bobby": "鲍比", "Bonzi": "邦奇",
    "Brad": "布拉德", "Bradley": "布拉德利", "Brandon": "布兰登", "Brendan": "布伦丹",
    "Brent": "布伦特", "Brevin": "布雷文", "Brian": "布莱恩", "Bruce": "布鲁斯",
    "Bryce": "布莱斯", "Bryn": "布林", "Buck": "巴克", "Buddy": "巴迪", "Byron": "拜伦",
    # C
    "Calbert": "卡尔伯特", "Calvin": "卡尔文", "Cameron": "卡梅隆", "Carl": "卡尔",
    "Carlos": "卡洛斯", "Caron": "卡隆", "Cedric": "塞德里克", "Channing": "钱宁",
    "Charles": "查尔斯", "Charlie": "查理", "Chase": "蔡斯", "Chris": "克里斯",
    "Christian": "克里斯蒂安", "Chuck": "查克", "Clarence": "克拉伦斯", "Clark": "克拉克",
    "Clifford": "克利福德", "Cliff": "克利夫", "Clyde": "克莱德", "Cody": "科迪",
    "Corey": "科里", "Corliss": "科利斯", "Craig": "克雷格", "Cuttino": "卡蒂诺",
    # D
    "Dale": "戴尔", "Damian": "达米安", "Damon": "达蒙", "Dan": "丹", "Daniel": "丹尼尔",
    "Danny": "丹尼", "Dante": "丹特", "Darius": "达柳斯", "Darko": "达科", "Darrell": "达雷尔",
    "Darren": "达伦", "Darryl": "达里尔", "Dave": "戴夫", "David": "大卫", "Dean": "迪恩",
    "DeAnd": "德安德", "DeAndre": "德安德烈", "DeMarcus": "德马库斯", "DeMar": "德马尔",
    "Dee": "迪", "Dell": "戴尔", "Del": "德尔", "Demarre": "德马尔", "Dennis": "丹尼斯",
    "Derek": "德里克", "Deron": "德隆", "DeSagana": "德萨加纳", "DeShawn": "德肖恩",
    "Devin": "德文", "Dion": "迪昂", "Dirk": "德克", "Doc": "道克", "Dominique": "多米尼克",
    "Don": "唐", "Donald": "唐纳德", "Donnell": "唐奈尔", "Donovan": "多诺万",
    "Doug": "道格", "Doyle": "多伊尔", "Duane": "杜安", "Drew": "德鲁", "Dudley": "达德利",
    "Duke": "杜克", "Dustin": "达斯汀", "Dwight": "德怀特", "Dwyane": "德维恩",
    # E
    "Earl": "厄尔", "Eddie": "埃迪", "Ed": "埃德", "Edward": "爱德华", "Elton": "埃尔顿",
    "Elvin": "埃尔文", "Emeka": "埃梅卡", "Emmett": "埃米特", "Eric": "埃里克",
    "Ernie": "厄尼", "Ersan": "厄尔桑", "Ethan": "伊桑", "Eugene": "尤金", "Evan": "埃文",
    # F
    "Felix": "菲利克斯", "Fernando": "费尔南多", "Frank": "弗兰克", "Fred": "弗雷德",
    "Freddie": "弗雷迪", "Furkan": "富尔坎",
    # G
    "Gary": "加里", "Gaston": "加斯顿", "Geoff": "杰夫", "George": "乔治", "Gerald": "杰拉尔德",
    "Gerald": "杰拉尔德", "Gilbert": "吉尔伯特", "Glen": "格伦", "Glenn": "格伦",
    "Gordon": "戈登", "Greg": "格雷格", "Grant": "格兰特", "Gregory": "格雷戈里",
    # H
    "Hakeem": "哈基姆", "Harold": "哈罗德", "Harrison": "哈里森", "Harry": "哈里",
    "Harvey": "哈维", "Hasheem": "哈希姆", "Haywood": "海伍德", "Heath": "希思",
    "Hedo": "赫多", "Henry": "亨利", "Herbert": "赫伯特", "Hersey": "赫西",
    "Hilton": "希尔顿", "Holden": "霍尔登", "Horace": "霍勒斯", "Howard": "霍华德",
    "Hubert": "休伯特", "Hugh": "休", "Hunt": "亨特",
    # I
    "Ike": "艾克", "Isaiah": "以赛亚", "Isiah": "伊赛亚", "Ivan": "伊万",
    # J
    "Jabari": "贾巴里", "Jae": "杰", "Jalen": "杰伦", "Jamaal": "贾马尔", "Jamar": "贾马尔",
    "Jameer": "贾米尔", "Jamal": "贾马尔", "Jame": "詹姆斯", "James": "詹姆斯",
    "Jamie": "杰米", "Jan": "扬", "Jared": "贾里德", "Jaren": "贾伦", "Jaron": "贾伦",
    "Jasan": "贾森", "Jason": "贾森", "Jasper": "贾斯珀", "Javaris": "贾瓦里斯",
    "Jay": "杰伊", "Jaylen": "杰伦", "Jayson": "杰森", "Jeff": "杰夫", "Jefferson": "杰弗森",
    "Jeffery": "杰弗里", "Jerald": "杰拉尔德", "Jermaine": "杰梅因", "Jerome": "杰罗姆",
    "Jerry": "杰里", "Jeryl": "杰里尔", "Jesse": "杰西", "Jim": "吉姆", "Jimmy": "吉米",
    "Jiri": "伊日", "JJ": "JJ", "Joe": "乔", "Joel": "乔尔", "Joey": "乔伊",
    "John": "约翰", "Johnny": "强尼", "Jonathan": "乔纳森", "Jordan": "乔丹",
    "Jorge": "豪尔赫", "Josen": "乔森", "Josh": "约什", "Joshua": "乔舒亚",
    "Juwan": "朱万", "Juwan": "朱万",
    # K
    "Kahlil": "卡利勒", "Kalen": "卡伦", "Kamil": "卡米尔", "Karl": "卡尔",
    "Keith": "基思", "Kelenna": "凯伦纳", "Kelly": "凯利", "Kelvin": "凯尔文",
    "Ken": "肯", "Kendall": "肯德尔", "Kenny": "肯尼", "Kent": "肯特", "Kentavious": "肯塔维奥斯",
    "Kenyon": "肯扬", "Kevin": "凯文", "Keyon": "基翁", "Khalid": "哈立德",
    "Kirk": "柯克", "Kiyoshi": "清", "Kobe": "科比", "Kris": "克里斯", "Kristaps": "克里斯塔普斯",
    "Kurt": "科特", "Kyle": "凯尔", "Kyrie": "凯里",
    # L
    "Lamar": "拉马尔", "Lamond": "拉蒙德", "Lance": "兰斯", "Larry": "拉里",
    "LaSalle": "拉萨勒", "Latavious": "拉塔维奥斯", "Latrell": "拉特里尔",
    "Lawrence": "劳伦斯", "Lazar": "拉扎尔", "Lee": "李", "Leon": "莱昂",
    "Leonard": "伦纳德", "Leonardo": "莱昂纳多", "Leron": "勒龙", "Leroy": "勒罗伊",
    "Lewis": "刘易斯", "Lincoln": "林肯", "Lionel": "莱昂内尔", "Lloyd": "劳埃德",
    "Lonzo": "朗佐", "Loren": "洛伦", "Lorenzo": "洛伦佐", "Louis": "路易斯",
    "Lou": "卢", "Lucas": "卢卡斯", "Luc": "卢克", "Luka": "卢卡", "Luke": "卢克",
    "Luther": "卢瑟", "Lynn": "林恩",
    # M
    "Maciej": "马切伊", "Malik": "马利克", "Manu": "马努", "Marc": "马克",
    "Marcus": "马库斯", "Mario": "马里奥", "Mark": "马克", "Marques": "马凯斯",
    "Marquis": "马奎斯", "Marshall": "马歇尔", "Martin": "马丁", "Marvin": "马文",
    "Mateen": "马汀", "Matt": "马特", "Matthew": "马修", "Maurice": "莫里斯",
    "Maurizio": "毛里齐奥", "Max": "马克斯", "Maybyner": "梅比纳", "Mehmet": "梅赫梅特",
    "Melvin": "梅尔文", "Michael": "迈克尔", "Micheal": "迈克尔", "Mike": "迈克",
    "Mikki": "米基", "Miles": "迈尔斯", "Milt": "米尔特", "Mitch": "米奇",
    "Mitchell": "米切尔", "Mo": "莫", "Mohamed": "穆罕默德", "Morris": "莫里斯",
    "Moses": "摩西", "Muggsy": "马格西", "Murray": "默里", "Mychal": "迈卡尔",
    "Myron": "迈伦",
    # N
    "Nate": "内特", "Nathan": "内森", "Nazar": "纳扎尔", "Nene": "内内",
    "Nick": "尼克", "Nicoloz": "尼科洛兹", "Nikola": "尼古拉", "Noah": "诺阿",
    "Norm": "诺姆", "Norris": "诺里斯",
    # O
    "Olden": "奥登", "Oliver": "奥利弗", "Omar": "奥马尔", "Orlando": "奥兰多",
    "Othyus": "奥修斯", "Otis": "奥蒂斯", "Otto": "奥托", "Ovie": "奥维",
    # P
    "Pablo": "巴勃罗", "Pat": "帕特", "Patrick": "帕特里克", "Paul": "保罗",
    "Perry": "佩里", "Pete": "皮特", "Peter": "彼得", "Phil": "菲尔", "Philip": "菲利普",
    "Pierre": "皮埃尔", "Predrag": "普雷德拉格", "Primoz": "普里莫兹",
    # Q
    "Quentin": "昆汀", "Quincy": "昆西",
    # R
    "Rafael": "拉斐尔", "Rafer": "拉夫", "Rajon": "拉简", "Ralph": "拉尔夫",
    "Randy": "兰迪", "Rasheed": "拉希德", "Rashard": "拉沙德", "Rasho": "拉索",
    "Ray": "雷", "Raymond": "雷蒙德", "Reggie": "雷吉", "Rene": "勒内",
    "Rex": "雷克斯", "Rich": "里奇", "Richard": "理查德", "Rick": "里克",
    "Ricky": "里基", "Rimas": "里马斯", "Robert": "罗伯特", "Roberto": "罗伯托",
    "Rodney": "罗德尼", "Rod": "罗德", "Roger": "罗杰", "Rolando": "罗兰多",
    "Ron": "罗恩", "Ronald": "罗纳德", "Rony": "罗尼", "Rory": "罗里",
    "Roscoe": "罗斯科", "Roy": "罗伊", "Ruben": "鲁本", "Rubio": "卢比奥",
    "Rudy": "鲁迪", "Rumeal": "鲁米尔", "Russell": "拉塞尔", "Rusty": "拉斯蒂",
    "Ryan": "瑞安", "Rylan": "赖兰",
    # S
    "Salim": "萨利姆", "Sam": "萨姆", "Samardo": "萨马多", "Samuel": "塞缪尔",
    "Sasha": "萨沙", "Scott": "斯科特", "Scottie": "斯科蒂", "Scot": "斯科特",
    "Sean": "肖恩", "Sedale": "塞达尔", "Sergio": "塞尔吉奥", "Seth": "塞斯",
    "Shaan": "沙恩", "Shandon": "香东", "Shane": "肖恩", "Shannon": "香农",
    "Shareef": "沙里夫", "Shawn": "肖恩", "Sheldon": "谢尔顿", "Shelvin": "谢尔文",
    "Sherman": "谢尔曼", "Sherrod": "谢罗德", "Slava": "斯拉瓦", "Smush": "斯穆什",
    "Sonic": "索尼克", "Stacey": "斯泰西", "Stanko": "斯坦科", "Stephon": "斯蒂芬",
    "Stephen": "斯蒂芬", "Steve": "史蒂夫", "Stromile": "斯特罗迈尔", "Stuart": "斯图尔特",
    "Sunny": "桑尼", "Sven": "斯文",
    # T
    "T.J.": "TJ", "TJ": "TJ", "Taurean": "陶里安", "Taurese": "陶里斯",
    "Teddy": "特迪", "Terk": "特克", "Terrence": "特伦斯", "Terrell": "特雷尔",
    "Terry": "特里", "Thaddeus": "萨迪斯", "Theo": "西奥", "Thomas": "托马斯",
    "Tim": "蒂姆", "Timofey": "季莫费", "Tobias": "托拜厄斯", "Todd": "托德",
    "Tom": "汤姆", "Tomas": "托马什", "Tony": "托尼", "Torrey": "托里",
    "Tracy": "特雷西", "Travis": "特拉维斯", "Tremaine": "特雷梅因", "Trey": "特雷",
    "Tristian": "特里斯坦", "Tristan": "特里斯坦", "Troy": "特洛伊", "Ty": "泰",
    "Tyler": "泰勒", "Tyreke": "泰瑞克", "Tyronn": "泰伦", "Tyrone": "泰隆",
    # U
    "Udonis": "乌杜尼斯", "Uros": "乌罗什",
    # V
    "Val": "瓦尔", "Vince": "文斯", "Vincent": "文森特", "Vladimir": "弗拉基米尔",
    "Von": "冯", "Vonteego": "冯蒂戈",
    # W
    "Walt": "沃尔特", "Walter": "沃尔特", "Wardell": "沃德尔", "Wayman": "韦曼",
    "Wayne": "韦恩", "Wes": "韦斯", "Wesley": "韦斯利", "Willy": "威利",
    "Will": "威尔", "William": "威廉", "Willie": "威利", "Willie": "威利",
    "Willis": "威利斯", "Wolve": "沃尔夫",
    # X
    "Xavier": "泽维尔",
    # Y
    "Yannick": "雅尼克", "Yao": "姚", "Yugott": "尤戈特",
    # Z
    "Zach": "扎克", "Zachary": "扎卡里", "Zeljko": "热利科", "Zoran": "佐兰",
}

LAST_DICT = {
    # A
    "Abdul-Aziz": "阿卜杜勒-阿齐兹", "Abdur-Rahim": "阿卜杜尔-拉希姆", "Abernathy": "阿伯内西",
    "Acker": "阿克", " Acres": "埃克斯", "Acres": "埃克斯", "Adams": "亚当斯",
    "Adubato": "阿杜巴托", "Aguirre": "阿吉雷", "Ainge": "安吉", "Akins": "阿金斯",
    "Alexander": "亚历山大", "Alford": "阿尔福德", "Allen": "艾伦", "Alley": "阿利",
    "Alston": "阿尔斯通", "Alt": "阿尔特", "Alzolol": "阿尔佐洛", "Amaya": "阿马亚",
    "Amick": "阿米克", "Anderson": "安德森", "Andrews": "安德鲁斯", "Ansley": "安斯利",
    "Anthony": "安东尼", "Apling": "阿普林", "Arizin": "阿里津", "Armstrong": "阿姆斯特朗",
    "Arroyo": "阿罗约", "Askins": "阿斯金斯", "Askew": "阿斯丘", "Aston": "阿斯顿",
    "Auriemma": "奥里埃马", "Austin": "奥斯汀", "Avent": "埃文特", "Avery": "艾弗里",
    "Ayanbadejo": "阿扬巴德乔", "Azubuike": "阿祖布克",
    # B
    "Bagley": "巴格利", "Bailey": "贝利", "Baker": "贝克", "Baldwin": "鲍德温",
    "Ball": "鲍尔", "Banks": "班克斯", "Barbosa": "巴博萨", "Barlow": "巴洛",
    "Barnes": "巴恩斯", "Barrett": "巴雷特", "Barros": "巴罗斯", "Barry": "巴里",
    "Bass": "巴斯", "Bates": "贝茨", "Battie": "巴蒂", "Battier": "巴蒂尔",
    "Baxter": "巴克斯特", "Bayless": "贝勒斯", "Beal": "比尔", "Beasley": "比斯利",
    "Beck": "贝克", "Bell": "贝尔", "Bellamy": "贝拉米", "Bender": "本德",
    "Benjamin": "本杰明", "Bennett": "贝内特", "Benoit": "贝努瓦", "Benson": "本森",
    "Beregowda": "贝雷戈达", "Berry": "贝里", "Best": "贝斯特", "Bibby": "毕比",
    "Bickerstaff": "比克斯塔夫", "Biedrins": "比德林斯", "Bigelow": "比格洛",
    "Billups": "比卢普斯", "Bingo": "宾戈", "Bird": "伯德", "Birkel": "伯克尔",
    "Bjorkgren": "比约克格伦", "Blackman": "布莱克曼", "Black": "布莱克",
    "Blanton": "布兰顿", "Blaudschun": "布劳德顺", "Blevins": "布莱文斯",
    "Blount": "布朗特", "Blaylock": "布莱洛克", "Bogues": "博格斯", "Bogut": "博古特",
    "Bohannon": "博汉农", "Boone": "布恩", "Bosh": "波什", "Bost": "博斯特",
    "Boucher": "布歇", "Boucek": "布切克", "Bouldin": "博尔丁", "Bowdler": "鲍德勒",
    "Bowie": "鲍维", "Bowness": "鲍内斯", "Boyd": "博伊德", "Bradley": "布拉德利",
    "Bradshaw": "布拉德肖", "Brailsford": "布雷斯福德", "Brand": "布兰德",
    "Brandon": "布兰登", "Brantley": "布兰特利", "Braswell": "布拉斯韦尔",
    "Bratz": "布拉茨", "Braun": "布劳恩", "Braverman": "布雷弗曼", "Breaux": "布罗",
    "Bremerton": "布雷默顿", "Brezec": "布雷泽茨", "Brickowski": "布里科夫斯基",
    "Bridges": "布里奇斯", "Briggs": "布里格斯", "Bright": "布莱特",
    "Bristow": "布里斯托", "Broadnax": "布罗德纳克斯", "Brookins": "布鲁金斯",
    "Brooks": "布鲁克斯", "Brown": "布朗", "Broy": "布罗伊", "Bruce": "布鲁斯",
    "Brundidge": "布伦迪奇", "Brunson": "布伦森", "Bryant": "布莱恩特",
    "Bryce": "布莱斯", "Buckner": "巴克纳", "Bucks": "雄鹿", "Buell": "比尔",
    "Buford": "布福德", "Bullard": "布拉德", "Bullen": "布伦", "Bunch": "邦奇",
    "Bunn": "邦恩", "Burch": "伯奇", "Burden": "伯登", "Burgess": "伯吉斯",
    "Burke": "伯克", "Burleson": "伯利森", "Burns": "伯恩斯", "Burris": "伯里斯",
    "Burton": "伯顿", "Buse": "布斯", "Butler": "巴特勒", "Butsch": "布奇",
    "Byars": "拜尔斯", "Byrd": "伯德",
    # C
    "Cabarkapa": "察巴尔卡帕", "Cable": "凯布尔", "Caboclo": "卡博克洛",
    "Caffey": "卡菲", "Cage": "凯奇", "Cain": "凯恩", "Calderon": "卡尔德隆",
    "Calhoun": "卡尔霍恩", "Callison": "卡利森", "Camanella": "卡马内拉",
    "Cameron": "卡梅伦", "Campbell": "坎贝尔", "Candler": "坎德勒", "Cannon": "坎农",
    "Canzeri": "坎泽里", "Capel": "卡佩尔", "Capocci": "卡波奇", "Carey": "凯里",
    "Carlisle": "卡莱尔", "Carlson": "卡尔森", "Carr": "卡尔", "Carrawell": "卡拉维尔",
    "Carroll": "卡罗尔", "Carson": "卡森", "Carter": "卡特", "Cartwright": "卡特赖特",
    "Caruso": "卡鲁索", "Casey": "凯西", "Cash": "卡什", "Cassell": "卡塞尔",
    "Casspi": "卡斯比", "Catledge": "卡特利奇", "Cato": "卡托", "Ceballos": "塞巴洛斯",
    "Cervantes": "塞万提斯", "Chalmers": "查尔默斯", "Chambers": "钱伯斯",
    "Chandler": "钱德勒", "Chapman": "查普曼", "Charles": "查尔斯",
    "Chilcutt": "奇尔卡特", "Childress": "柴尔德里斯", "Childs": "柴尔兹",
    "Christie": "克里斯蒂", "Churchwell": "丘奇韦尔", "Cioroch": "乔罗奇",
    "Clark": "克拉克", "Claxton": "克拉克斯顿", "Cleaves": "克利夫斯",
    "Clemens": "克莱门斯", "Clemente": "克莱门特", "Clemons": "克莱蒙斯",
    "Clifford": "克利福德", "Cline": "克莱恩", "Clifton": "克利夫顿", "Cobb": "科布",
    "Coffey": "科菲", "Cofield": "科夫菲尔德", "Cole": "科尔", "Coleman": "科尔曼",
    "Coles": "科尔斯", "Collins": "科林斯", "Collinsworth": "柯林斯沃斯",
    "Colson": "科尔森", "Combs": "库姆斯", "Comegys": "科梅吉斯", "Conlan": "康兰",
    "Conn": "康恩", "Conley": "康利", "Connally": "康纳利", "Conway": "康威",
    "Cook": "库克", "Coombs": "库姆斯", "Cooper": "库珀", "Copeland": "科普兰",
    "Corbin": "科尔宾", "Corley": "科利", "Cornelius": "科尼利厄斯", "Coro": "科罗",
    "Corzine": "科尔津", "Cosby": "科斯比", "Cosey": "科西", "Cotton": "科顿",
    "Cox": "考克斯", "Craft": "克拉夫特", "Craig": "克雷格", "Crawford": "克劳福德",
    "Cremmins": "克雷明斯", "Crittenton": "克里坦顿", "Croshere": "克罗希尔",
    "Crowder": "克劳德", "Cummings": "卡明斯", "Cunningham": "坎宁安",
    "Curley": "柯利", "Curry": "库里", "Curtis": "柯蒂斯", "Cutshall": "卡茨霍尔",
    "Czerwinski": "切尔温斯基",
    # D
    "D'Antoni": "德安东尼", "Dampier": "丹皮尔", "Daniels": "丹尼尔斯",
    "Danridge": "丹里奇", "Darden": "达登", "Darnell": "达内尔", "Darring": "达林",
    "Dash": "达什", "Daugaard": "道加德", "Daugherty": "多尔蒂", "Davidson": "戴维森",
    "Davis": "戴维斯", "Dawkins": "道金斯", "Dawson": "道森", "Day": "戴",
    "Daye": "戴耶", "Deane": "迪恩", "DeBisschop": "德比斯科普", "DeBuscher": "德布舍",
    "DeClercq": "德克勒克", "DeLancourt": "德兰考特", "DeMarcus": "德马库斯",
    "DeMatha": "德马萨", "Dampier": "丹皮尔", "Denmon": "德蒙", "Dennis": "丹尼斯",
    "Dent": "登特", "Denton": "登顿", "DePorre": "德波雷", "DeRozan": "德罗赞",
    "Derrick": "德里克", "DeSagana": "德萨加纳", "DeShay": "德谢", "Dethroned": "废黜",
    "Detroit": "底特律", "Dettmann": "德特曼", "Deuce": "杜斯", "Devlin": "德夫林",
    "Diener": "迪纳", "DiGregorio": "迪格雷戈里奥", "Dillard": "迪拉德",
    "Dillon": "狄龙", "Dinkins": "丁金斯", "Dinwiddie": "丁威迪", "Dipre": "迪普雷",
    "Diogu": "迪奥古", "Divac": "迪瓦茨", "Dixon": "迪克森", "Doback": "多巴克",
    "Doby": "多比", "Dodd": "多德", "Doleac": "多利奇", "Dombrowski": "多姆布罗夫斯基",
    "Dones": "多内斯", "Dong": "董", "Dooley": "杜利", "Dorsey": "多西",
    "Dorsey": "多西", "Douglas": "道格拉斯", "Douglas-Roberts": "道格拉斯-罗伯茨",
    "Draffen": "德拉芬", "Dragan": "德拉甘", "Draper": "德雷珀", "Drayden": "德雷登",
    "Dreiling": "德雷林", "Drew": "德鲁", "Drummond": "德拉蒙德", "Du": "杜",
    "Dubar": "杜巴尔", "Dudley": "达德利", "Dugan": "杜根", "Duhon": "杜洪",
    "Dumas": "杜马斯", "Dumars": "杜马斯", "Dunbar": "邓巴", "Duncan": "邓肯",
    "Dunleavy": "邓利维", "Dunn": "邓恩", "Dupree": "杜普里", "Durant": "杜兰特",
    "Durham": "德拉姆", "Dutcher": "达切尔", "Dutt": "达特", "Duvall": "杜瓦尔",
    "Dyson": "戴森",
    # E
    "Eackles": "伊克尔斯", "Ebanks": "班克斯", "Eaton": "伊顿", "Eaves": "伊夫斯",
    "Ebi": "埃比", "Ebone": "埃博内", "Edelin": "埃德林", "Edwards": "爱德华兹",
    "Eggleston": "埃格尔斯顿", "Ehlo": "埃洛", "Eissenberger": "艾森伯格",
    "Eisley": "艾斯利", "Ekeler": "埃克勒", "Eldridge": "埃尔德里奇", "Elliott": "埃利奥特",
    "Ellis": "埃利斯", "Ellison": "埃里森", "Elmore": "埃尔莫尔", "Elsner": "埃尔斯纳",
    "Embiid": "恩比德", "Embry": "恩布里", "English": "英格利什", "Enoch": "伊诺克",
    "Ensminger": "恩斯明格", "Erickson": "埃里克森", "Ersland": "厄斯兰",
    "Erving": "欧文", "Espinoza": "埃斯皮诺萨", "Esposito": "埃斯波西托",
    "Estes": "埃斯蒂斯", "Eubanks": "尤班克斯", "Evans": "埃文斯", "Evert": "埃弗特",
    "Ewing": "尤因",
    # F
    "Falk": "福尔克", "Farmer": "法默", "Farokhmanesh": "法罗赫马内什",
    "Farrakhan": "法拉汗", "Farrell": "法雷尔", "Faulk": "福尔克", "Faulkner": "福克纳",
    "Favors": "费弗斯", "Fayette": "费耶特", "Fazio": "法齐奥", "Feaster": "菲斯特",
    "Fede": "费德", "Felton": "费尔顿", "Ferguson": "弗格森", "Fernandez": "费尔南德斯",
    "Ferrari": "法拉利", "Ferrell": "费雷尔", "Fields": "菲尔兹", "Filer": "法勒",
    "Finley": "芬利", "Fisher": "费舍尔", "Fitch": "菲奇", "Fitzgerald": "菲茨杰拉德",
    "Fleming": "弗莱明", "Fletcher": "弗莱彻", "Flock": "弗洛克", "Fluellen": "弗吕伦",
    "Flynn": "弗林", "Foley": "福利", "Fondren": "方德伦", "Ford": "福特",
    "Foreman": "福尔曼", "Forte": "福特", "Foster": "福斯特", "Four": "福尔",
    "Fowlkes": "福尔克斯", "Fox": "福克斯", "Foye": "福耶", "Francis": "弗朗西斯",
    "Franklin": "富兰克林", "Fraser": "弗雷泽", "Fraud": "弗劳德", "Frazier": "弗雷泽",
    "Frederick": "弗雷德里克", "Freeman": "弗里曼", "Froehlich": "弗勒利希",
    "Frye": "弗莱", "Fultz": "富尔茨", "Funderburke": "丰德伯克", "Furman": "弗曼",
    # G
    "Gabor": "加博尔", "Gaddy": "加迪", "Gaffney": "加夫尼", "Gaines": "盖恩斯",
    "Gallagher": "加拉格尔", "Gallinari": "加里纳利", "Galloway": "加洛韦",
    "Gant": "甘特", "Garba": "加尔巴", "Garner": "加纳", "Garrett": "加勒特",
    "Garrettson": "加勒特森", "Garrity": "加里蒂", "Gathers": "加瑟斯", "Gatling": "加特林",
    "Gause": "高斯", "Gay": "盖伊", "Geiger": "盖格", "Geller": "盖勒",
    "Gerald": "杰拉尔德", "Gervin": "格文", "Gibson": "吉布森", "Gilgeous-Alexander": "吉尔杰斯-亚历山大",
    "Gill": "吉尔", "Gillespie": "吉莱斯皮", "Gilliat": "吉利亚特", "Gilmore": "吉尔摩",
    "Gilyard": "吉利亚德", "Ginobili": "吉诺比利", "Gist": "吉斯特", "Glen": "格伦",
    "Glick": "格利克", "Gloger": "格洛格", "Gminski": "格明斯基", "Gober": "戈贝尔",
    "Goddard": "戈达德", "Godfread": "戈德弗雷德", "Goeggel": "戈格尔", "Goff": "戈夫",
    "Goga": "戈加", "Goldwire": "戈德维尔", "Gomes": "戈麦斯", "Gondrezick": "冈德雷齐克",
    "Gonzalez": "冈萨雷斯", "Good": "古德", "Gooden": "古登", "Goodrich": "古德里奇",
    "Gordon": "戈登", "Gore": "戈尔", "Goree": "戈里", "Gorman": "戈尔曼",
    "Goss": "戈斯", "Gotkin": "戈特金", "Gottlieb": "戈特利布", "Gouard": "古阿尔德",
    "Goudelock": "古德洛克", "Gould": "古尔德", "Grabiner": "格拉比纳",
    "Graboski": "格拉博斯基", "Grace": "格雷斯", "Graham": "格雷厄姆", "Granger": "格兰杰",
    "Grant": "格兰特", "Graves": "格雷夫斯", "Gray": "格雷", "Greaser": "格里泽",
    "Great": "格里特", "Green": "格林", "Greene": "格林", "Greenwood": "格林伍德",
    "Gregory": "格雷戈里", "Greisen": "格雷森", "Griffin": "格里芬",
    "Grigsby": "格里格斯比", "Grillo": "格里洛", "Grimm": "格里姆", "Grine": "格林",
    "Griswold": "格里斯沃尔德", "Grosso": "格罗索", "Grothe": "格罗特",
    "Grows": "格罗斯", "Grunfeld": "格伦费尔德", "Grunwald": "格伦沃尔德",
    "Guarascio": "瓜拉西奥", "Guess": "格斯", "Gugliotta": "古格里奥塔",
    "Guidinger": "圭丁格", "Guiler": "吉勒", "Gulbas": "古尔巴斯", "Gundy": "甘迪",
    "Gunning": "冈宁", "Gunter": "冈特", "Gurley": "格利", "Gus": "格斯",
    "Guthridge": "格思里奇", "Gutierrez": "古铁雷斯", "Guzman": "古兹曼",
    # H
    "Haarsma": "哈斯马", "Haas": "哈斯", "Haase": "哈斯", "Hackett": "哈克特",
    "Haddix": "哈迪克斯", "Hagans": "哈根斯", "Hagemann": "哈格曼", "Hagins": "哈金斯",
    "Hahn": "哈恩", "Haith": "海斯", "Hakim": "哈基姆", "Halasz": "哈拉斯",
    "Halbrook": "哈尔布鲁克", "Hale": "黑尔", "Hall": "霍尔", "Hallman": "霍尔曼",
    "Halmon": "哈尔蒙", "Halpert": "哈尔珀特", "Halsey": "哈尔西", "Ham": "哈姆",
    "Hamilton": "汉密尔顿", "Hammond": "哈蒙德", "Hamm": "哈姆", "Hams": "哈姆斯",
    "Hampton": "汉普顿", "Han": "韩", "Hancock": "汉考克", "Hanley": "汉利",
    "Hanna": "汉纳", "Hansen": "汉森", "Hanson": "汉森", "Harangody": "哈兰戈迪",
    "Hardaway": "哈达威", "Harden": "哈登", "Hardin": "哈丁", "Harding": "哈丁",
    "Hardy": "哈迪", "Hargis": "哈吉斯", "Harlan": "哈兰", "Harler": "哈勒",
    "Harley": "哈利", "Harlow": "哈洛", "Harmon": "哈蒙", "Harney": "哈尼",
    "Harper": "哈珀", "Harpster": "哈普斯特", "Harrington": "哈灵顿", "Harris": "哈里斯",
    "Harrison": "哈里森", "Harrold": "哈罗德", "Harrow": "哈罗", "Hart": "哈特",
    "Hartfield": "哈特菲尔德", "Hartman": "哈特曼", "Hartsock": "哈特索克",
    "Hartstein": "哈特斯坦", "Harvey": "哈维", "Harward": "哈沃德", "Harwood": "哈伍德",
    "Haryasz": "哈里亚什", "Hasbrouck": "哈斯布鲁克", "Haslem": "哈斯勒姆",
    "Hassan": "哈桑", "Hassell": "哈塞尔", "Hastings": "黑斯廷斯", "Hatchell": "哈切尔",
    "Hatfield": "哈特菲尔德", "Haughton": "霍顿", "Haupt": "豪普特", "Hausen": "豪森",
    "Havlicek": "哈弗利切克", "Hawkins": "霍金斯", "Hawley": "霍利", "Haws": "豪斯",
    "Hayes": "海耶斯", "Haynes": "海恩斯", "Haynesworth": "海恩斯沃斯",
    "Haywood": "海伍德", "Hazzard": "哈扎德", "Head": "黑德", "Headen": "希登",
    "Healy": "希利", "Heath": "希思", "Heaverin": "希弗林", "Hecht": "赫克特",
    "Hecker": "赫克", "Hedke": "赫德克", "Heiden": "海登", "Heinsohn": "海因索恩",
    "Heitkotter": "海特科特", "Helms": "赫尔姆斯", "Heltzel": "赫尔策尔",
    "Hemenway": "海明威", "Hemingway": "海明威", "Hemphill": "亨普希尔",
    "Henderson": "亨德森", "Hendricks": "亨德里克斯", "Hendrix": "亨德里克斯",
    "Henning": "亨宁", "Henrikson": "亨里克森", "Henry": "亨利", "Herbert": "赫伯特",
    "Herbst": "赫布斯特", "Hereford": "赫里福德", "Herman": "赫尔曼", "Hernandez": "埃尔南德斯",
    "Hernton": "赫恩顿", "Herren": "赫伦", "Herrera": "埃雷拉", "Herron": "赫伦",
    "Hersha": "赫尔沙", "Hertel": "赫特尔", "Herzog": "赫尔佐格", "Heskett": "赫斯克特",
    "Hess": "赫斯", "Hester": "赫斯特", "Hetzel": "赫策尔", "Hickman": "希克曼",
    "Hicks": "希克斯", "Higgins": "希金斯", "Highsmith": "海史密斯", "Hightower": "海托华",
    "Hildebrand": "希尔德布兰德", "Hill": "希尔", "Hille": "希勒", "Hillhouse": "希尔豪斯",
    "Hilliard": "希利亚德", "Hillicoss": "希利科斯", "Hillis": "希利斯",
    "Hinrich": "辛里奇", "Hinton": "辛顿", "Hipes": "海普斯", "Hird": "赫德",
    "Hite": "海特", "Hlavacek": "赫拉瓦切克", "Hoiberg": "霍伊博格", "Hollins": "霍林斯",
    "Hollis": "霍利斯", "Holloway": "霍洛韦", "Holman": "霍尔曼", "Holmes": "霍姆斯",
    "Holt": "霍尔特", "Holtz": "霍尔特茨", "Honeycutt": "哈尼卡", "Hong": "洪",
    "Hoover": "胡佛", "Hoppen": "霍彭", "Hopson": "霍普森", "Horace": "霍勒斯",
    "Horgan": "霍根", "Horford": "霍福德", "Hornacek": "霍纳塞克", "Hornbeck": "霍恩贝克",
    "Horney": "霍尼", "Horry": "霍里", "Horsley": "霍斯利", "Horton": "霍顿",
    "Horvath": "霍瓦斯", "Hostetler": "霍斯特勒", "Hot Rod": "热罗德", "House": "豪斯",
    "Houston": "休斯顿", "Howard": "霍华德", "Howe": "豪", "Howell": "豪厄尔",
    "Howland": "豪兰", "Hoy": "霍伊", "Hoyas": "霍亚斯", "Hray": "赫雷",
    "Hubbard": "哈伯德", "Hudson": "哈德森", "Huffman": "赫夫曼", "Hughes": "休斯",
    "Hughley": "休利", "Hugley": "哈格利", "Huhn": "许恩", "Hull": "赫尔",
    "Humbles": "亨布尔斯", "Hume": "休姆", "Hummel": "哈默尔", "Hummer": "哈默",
    "Humphrey": "汉弗莱", "Humphries": "亨弗里斯", "Hundley": "亨德利",
    "Hunt": "亨特", "Hunter": "亨特", "Huntley": "亨特利", "Hurst": "赫斯特",
    "Huss": "胡斯", "Huston": "休斯顿", "Hutchins": "哈钦斯", "Hutchinson": "哈钦森",
    "Hutson": "哈特森", "Hutzel": "赫策尔", "Hyder": "海德", "Hyland": "海兰",
    "Hyman": "海曼",
    # I
    "Iavaroni": "亚瓦罗尼", "Iba": "伊巴", "Ibach": "伊巴赫", "Ibarra": "伊瓦拉",
    "Ibeh": "伊贝", "Iddings": "伊丁斯", "Idlebird": "伊德尔伯德", "Iguodala": "伊戈达拉",
    "Ilgauskas": "伊尔戈斯卡斯", "Ilic": "伊利奇", "Ingram": "英格拉姆",
    "Ingram": "英格拉姆", "Inman": "英曼", "Ircink": "伊尔辛克", "Irvin": "欧文",
    "Irving": "欧文", "Isaacs": "艾萨克斯", "Isbell": "伊斯贝尔", "Iverson": "艾弗森",
    "Ivey": "艾维", "Iwasko": "伊瓦斯科", "Iwuakor": "伊乌科尔",
    # J
    "Jabbar": "贾巴尔", "Jabari": "贾巴里", "Jaber": "贾贝尔", "Jack": "杰克",
    "Jackson": "杰克逊", "Jacob": "雅各布", "Jacobs": "雅各布斯", "Jacobson": "雅各布森",
    "Jadlow": "贾德洛", "Jaeger": "耶格", "Jaffe": "贾菲", "Jager": "贾格尔",
    "Jahnke": "扬克", "Jakobs": "雅各布斯", "James": "詹姆斯", "Jamierson": "贾米尔森",
    "Jamison": "贾米森", "Jamison": "贾米森", "Janan": "贾南", "Janatka": "贾纳特卡",
    "Janes": "简斯", "Jannero": "简内罗", "Janning": "简宁", "Janssen": "扬森",
    "Jaric": "贾里奇", "Jarrell": "贾雷尔", "Jarrett": "贾勒特", "Jarvis": "贾维斯",
    "Jasikevicius": "贾西科维丘斯", "Jaskulski": "亚斯库尔斯基", "Jasper": "贾斯珀",
    "Jaszewski": "亚舍夫斯基", "Jawann": "贾万", "Jaworski": "贾沃尔斯基",
    "Jean": "让", "Jefferson": "杰弗森", "Jeffers": "杰弗斯", "Jeffries": "杰弗里斯",
    "Jelinek": "耶利内克", "Jelinek": "耶利内克", "Jemison": "杰米森",
    "Jenkins": "詹金斯", "Jennings": "詹宁斯", "Jensen": "延森", "Jent": "简特",
    "Jerez": "赫雷斯", "Jerideau": "杰里多", "Jernigan": "杰尼根", "Jernstedt": "耶恩斯特",
    "Jeter": "杰特", "Jewell": "朱厄尔", "Ji": "吉", "Jick": "杰克", "Jimenez": "希门尼斯",
    "Jirsak": "伊尔萨克", "Johansen": "约翰森", "Johns": "约翰斯", "Johnson": "约翰逊",
    "Johnston": "约翰斯顿", "Johnstone": "约翰斯通", "Joiner": "乔伊纳",
    "Jokic": "约基奇", "Joles": "乔尔斯", "Jolly": "乔利", "Jonas": "乔纳斯",
    "Jones": "琼斯", "Jordan": "乔丹", "Jordison": "乔迪森", "Jorgensen": "约根森",
    "Joseph": "约瑟夫", "Jossell": "乔塞尔", "Jovanovski": "约瓦诺夫斯基",
    "Joyce": "乔伊斯", "Joyner": "乔伊纳", "Juarez": "华雷斯", "Judd": "贾德",
    "Judge": "贾奇", "Juger": "朱格", "Julien": "朱利安", "Jump": " Jump",
    "Junkin": "琼金", "Jurak": "尤拉克", "Jurich": "尤里奇", "Justus": "贾斯特斯",
    # K
    "Kaan": "卡恩", "Kaba": "卡巴", "Kadeem": "卡迪姆", "Kadlec": "卡德莱茨",
    "Kahle": "卡勒", "Kahn": "卡恩", "Kaiser": "凯泽", "Kalafa": "卡拉法",
    "Kalb": "卡尔布", "Kaler": "卡勒", "Kalid": "卡利德", "Kaman": "卡曼",
    "Kaminski": "卡明斯基", "Kamps": "坎普斯", "Kancey": "坎西", "Kander": "坎德",
    "Kane": "凯恩", "Kannel": "坎内尔", "Kanner": "坎纳", "Kap": "卡普",
    "Kaplowitz": "卡普洛维茨", "Kapono": "卡波诺", "Kappel": "卡佩尔",
    "Kappler": "卡普勒", "Kapsalis": "卡普萨利斯", "Karasev": "卡拉塞夫",
    "Kardous": "卡尔杜斯", "Kareem": "卡里姆", "Karges": "卡吉斯", "Karl": "卡尔",
    "Karol": "卡罗尔", "Kasibabu": "卡西巴布", "Kasparov": "卡斯帕罗夫",
    "Kasten": "卡斯滕", "Kasun": "卡孙", "Katterbach": "卡特巴赫", "Katz": "卡茨",
    "Kauffman": "考夫曼", "Kaufman": "考夫曼", "Kavakian": "卡瓦基安", "Kavalleris": "卡瓦列里斯",
    "Kay": "凯", "Keady": "基迪", "Keagle": "基格尔", "Keane": "基恩",
    "Kearney": "卡尼", "Kearse": "基尔斯", "Keating": "基廷", "Keatts": "基茨",
    "Keck": "凯克", "Kedra": "凯德拉", "Keefe": "基夫", "Keegan": "基根",
    "Keeley": "基利", "Keen": "基恩", "Keenan": "基南", "Keener": "基纳",
    "Keeton": "基顿", "Keesh": "基什", "Keeter": "基特", "Kehler": "凯勒",
    "Kelbick": "凯尔比克", "Kelley": "凯利", "Kelly": "凯利", "Kelm": "凯尔姆",
    "Kelso": "凯尔索", "Kelton": "凯尔顿", "Kemp": "坎普", "Kendall": "肯德尔",
    "Kendig": "肯迪格", "Kendrick": "肯德里克", "Kener": "凯纳", "Kenney": "肯尼",
    "Kenon": "凯农", "Kensmil": "肯斯米尔", "Kent": "肯特", "Kenyon": "肯扬",
    "Kenyotta": "肯约塔", "Keplinger": "凯普林格", "Kerber": "克伯", "Kerl": "克尔",
    "Kerner": "克纳", "Kerr": "科尔", "Kerse": "克尔斯", "Kersten": "克斯滕",
    "Kessler": "凯斯勒", "Ketcham": "凯查姆", "Ketchen": "凯琴", "Ketter": "凯特",
    "Kettles": "凯特尔斯", "Kettner": "凯特纳", "Keupper": "科伊普", "Key": "基",
    "Keys": "基斯", "Khan": "汗", "Kharma": "卡尔马", "Kiefer": "基弗",
    "Kiggins": "基金斯", "Kight": "凯特", "Kilcoyne": "基尔科因", "Kiley": "基利",
    "Killian": "基利安", "Kilpatrick": "基尔帕特里克", "Kimball": "金博尔",
    "Kimble": "金布尔", "Kinard": "基纳德", "Kindler": "金德勒", "King": "金",
    "Kingston": "金斯顿", "Kinkel": "金克尔", "Kinsey": "金赛", "Kinsey": "金赛",
    "Kintzel": "金泽尔", "Kinzer": "金泽", "Kip": "基普", "Kiper": "基珀",
    "Kiphart": "基帕特", "Kirby": "柯比", "Kirchner": "基什纳", "Kirkpatrick": "柯克帕特里克",
    "Kirsch": "基尔施", "Kirshon": "基尔雄", "Kirwan": "柯万", "Kiser": "凯泽",
    "Kithcart": "基思卡特", "Kitts": "基茨", "Klaffky": "克拉夫基", "Klais": "克莱斯",
    "Klann": "克兰", "Klay": "克莱", "Klecka": "克莱卡", "Kleese": "克利塞",
    "Klein": "克莱因", "Klementich": "克莱门蒂奇", "Klepfisz": "克莱普菲什",
    "Klesmit": "克莱斯米特", "Klick": "克利克", "Klimchak": "克利姆查克",
    "Kline": "克莱恩", "Klink": "克林克", "Kloeppel": "克勒佩尔", "Kloppenburg": "克洛彭堡",
    "Klose": "克洛泽", "Klucas": "克卢卡斯", "Klug": "克鲁格", "Kluka": "克卢卡",
    "Knake": "克纳克", "Knapke": "克纳普克", "Knebel": "克内贝尔", "Kneeland": "尼兰",
    "Kneller": "克内勒", "Knigga": "克尼加", "Knight": "奈特", "Knipp": "克尼普",
    "Knoblauch": "克瑙布劳赫", "Knoch": "克诺克", "Knorr": "诺尔", "Koehl": "科尔",
    "Koelling": "科林", "Koeppe": "科佩", "Koger": "科杰", "Kohn": "科恩",
    "Kolich": "科利奇", "Kollar": "科拉尔", "Kolodzik": "科洛兹齐克", "Kolter": "科尔特",
    "Koncel": "康塞尔", "Kondrat": "孔德拉特", "Konency": "科内尼", "Konieczny": "科涅奇尼",
    "Konkel": "孔克尔", "Koonce": "孔斯", "Kopec": "科佩克", "Kopicki": "科皮基",
    "Kopriva": "科普里瓦", "Korb": "科布", "Korcheck": "科尔切克", "Korver": "科沃尔",
    "Koser": "科泽", "Koshman": "科什曼", "Koss": "科斯", "Kostecka": "科斯特卡",
    "Kostka": "科斯特卡", "Kot": "科特", "Kotilinek": "科蒂利内克", "Kotler": "科特勒",
    "Kott": "科特", "Koufos": "库弗斯", "Kovach": "科瓦奇", "Koval": "科瓦尔",
    "Kovar": "科瓦尔", "Kowal": "科瓦尔", "Kraatz": "克拉茨", "Kraft": "克拉夫特",
    "Kral": "克拉尔", "Kramer": "克雷默", "Kramp": "克兰普", "Kranyak": "克兰亚克",
    "Kratky": "克拉特基", "Krause": "克劳斯", "Kravitz": "克拉维茨", "Krawczyk": "克拉夫奇克",
    "Krebs": "克雷布斯", "Krecklow": "克雷克洛", "Krejci": "克雷伊奇", "Kremer": "克雷默",
    "Krenz": "克伦茨", "Kreps": "克雷普斯", "Krestian": "克雷斯蒂安", "Kreuser": "克罗伊泽",
    "Kreuzer": "克罗伊泽", "Krichbaum": "克里奇鲍姆", "Kriel": "克里尔", "Kriger": "克里格",
    "Kring": "克林", "Krings": "克林斯", "Krippel": "克里佩尔", "Krisilich": "克里西利奇",
    "Kristek": "克里斯特克", "Krizek": "克里泽克", "Kroenke": "克伦克", "Kroetch": "克罗奇",
    "Kroll": "克罗尔", "Krombach": "克罗姆巴赫", "Krone": "克罗内", "Kropf": "克罗普夫",
    "Krstic": "克尔斯蒂奇", "Krueger": "克鲁格", "Krug": "克鲁格", "Kruse": "克鲁泽",
    "Kuberski": "库贝尔斯基", "Kubat": "库巴特", "Kubiak": "库比亚克", "Kuchta": "库赫塔",
    "Kuester": "库斯特", "Kuhar": "库哈尔", "Kuhnau": "库瑙", "Kuiper": "库伊珀",
    "Kulhavy": "库尔哈维", "Kulig": "库利格", "Kumrow": "库姆罗", "Kunce": "昆斯",
    "Kundson": "昆德森", "Kunes": "库内斯", "Kunkel": "昆克尔", "Kuper": "库珀",
    "Kupisch": "库皮施", "Kurth": "库尔特", "Kusleika": "库斯莱卡", "Kustok": "库斯托克",
    "Kutas": "库塔斯", "Kurowski": "库罗夫斯基", "Kus": "库斯", "Kuzma": "库兹马",
    "Kuzmic": "库兹米奇", "Kvac": "克瓦奇", "Kwiatek": "克维亚特克",
    # L
    "Laatsch": "拉奇", "Labaj": "拉巴伊", "Labin": "拉宾", "LaBlanc": "拉布朗",
    "Lackey": "拉克", "Laczkowski": "拉奇科夫斯基", "Ladd": "拉德", "Lademann": "拉德曼",
    "Ladowski": "拉多夫斯基", "Lafave": "拉法夫", "LaFlambo": "拉弗拉博",
    "LaFrentz": "拉弗伦茨", "Lagarde": "拉加德", "Lagaspi": "拉加斯皮", "Lagrou": "拉格鲁",
    "Laing": "莱恩", "Laipply": "莱普利", "Laird": "莱尔德", "Lajeske": "拉杰斯基",
    "Laketa": "拉凯塔", "Lamb": "拉姆", "Lambert": "兰伯特", "Lammers": "拉默斯",
    "Lampe": "兰佩", "Lampley": "兰普利", "Lanane": "拉南", "Lancaster": "兰开斯特",
    "Lance": "兰斯", "Land": "兰德", "Landers": "兰德斯", "Landers": "兰德斯",
    "Landford": "兰德福", "Landis": "兰迪斯", "Landry": "兰德里", "Lanford": "兰德福",
    "Langan": "兰根", "Langdon": "兰登", "Langanke": "兰根克", "Langford": "兰福德",
    "Langholz": "兰霍尔茨", "Langley": "兰利", "Langlois": "朗格卢瓦", "Languis": "兰吉斯",
    "Lanhart": "兰哈特", "Lanning": "兰宁", "Lanpher": "兰弗", "Lansford": "兰斯福德",
    "Lanter": "兰特", "LaPoint": "拉波因特", "Lappas": "拉帕斯", "Laprade": "拉普拉德",
    "Larabee": "阿拉比", "Laravie": "拉拉维", "Lard": "拉德", "Larish": "拉里什",
    "Larkin": "拉金", "Larranaga": "拉拉尼亚加", "Larrea": "拉雷亚", "Larrick": "拉里克",
    "Larson": "拉森", "Larsson": "拉松", "Lasater": "拉萨特", "Lascelles": "拉斯塞尔斯",
    "Lash": "拉什", "Lashbrook": "拉什布鲁克", "Lashley": "拉什利", "Laskowski": "拉斯科夫斯基",
    "Lasonde": "拉松德", "Latimer": "拉蒂默", "Latsko": "拉茨科", "Lattin": "拉丁",
    "Lattimore": "拉蒂莫尔", "Latzo": "拉佐", "Lauda": "劳达", "Laudano": "劳达诺",
    "Lauderdale": "劳德代尔", "Lauer": "劳尔", "Laughlin": "劳夫林", "Laun": "劳恩",
    "Launspach": "劳恩斯帕赫", "Laur": "劳尔", "Laurent": "洛朗", "Laurich": "劳里奇",
    "Laurila": "劳里拉", "Lautenschlager": "劳滕施拉格", "Lavador": "拉瓦多",
    "Lavine": "拉文", "Lavin": "拉文", "Lavine": "拉文", "Lawing": "劳因",
    "Lawrenz": "劳伦茨", "Lawson": "劳森", "Layden": "雷登", "Layman": "莱曼",
    "Lazor": "拉佐", "Lazovich": "拉佐维奇", "Lea": "利", "Leach": "利奇",
    "Leake": "利克", "Leary": "利里", "Leatherman": "莱瑟曼", "Leatzow": "利佐",
    "LeBeau": "勒博", "Lebherz": "勒伯茨", "Leblanc": "勒布朗", "Lebo": "莱博",
    "Lechleitner": "莱克莱特纳", "Lechner": "莱希纳", "Leckband": "莱克班德",
    "Leckrone": "莱克罗恩", "Ledsinger": "莱辛格", "Lee": "李", "Leen": "莱恩",
    "LeFevre": "勒费夫尔", "Leffew": "莱弗", "Leffler": "莱夫勒", "LeForce": "勒福斯",
    "Leftwich": "莱夫特威奇", "LeGate": "勒盖特", "Legleiter": "莱莱特", "Lehmann": "莱曼",
    "Lehnen": "伦恩", "Lehrke": "莱尔克", "Leibold": "利博尔德", "Leiferman": "利弗曼",
    "Leighton": "莱顿", "Leija": "莱哈", "Leis": "莱斯", "Leister": "莱斯特",
    "Leland": "利兰", "Lemar": "勒马尔", "Lemarsh": "勒马什", "Lemasters": "勒马斯特斯",
    "Lembke": "伦克", "Lemke": "莱姆克", "Lemons": "莱蒙斯", "Lemons": "莱蒙斯",
    "Lempka": "伦普卡", "Lencyk": "伦奇克", "Lendowsky": "伦多夫斯基", "Lentz": "伦茨",
    "Lenz": "伦茨", "Lenzmeier": "伦茨迈尔", "Leone": "莱昂内", "Leonhard": "伦哈德",
    "Leonisio": "莱奥尼西奥", "Lepeley": "莱佩利", "Lepinski": "莱平斯基", "Lerch": "勒奇",
    "Lerg": "勒格", "Leriger": "莱里格", "Les": "莱斯", "Leslie": "莱斯利",
    "Lesniewski": "莱希涅夫斯基", "Lester": "莱斯特", "Lestishen": "莱斯申", "Letcher": "莱彻",
    "Lethbridge": "莱思布里奇", "Leussink": "勒辛克", "Leutzinger": "勒辛格",
    "Lever": "莱弗", "Levesque": "莱韦斯克", "Levin": "莱文", "Levine": "莱文",
    "Levings": "莱文斯", "Levins": "莱文斯", "Levy": "利维", "Lewis": "刘易斯",
    "Ley": "利", "Lichliter": "利奇利特", "Licht": "利希特", "Lichterman": "利希特曼",
    "Lichty": "利希蒂", "Lickiss": "利基斯", "Lickteig": "利克泰格", "Liddell": "利德尔",
    "Liddon": "利登", "Liddle": "利德尔", "Lidstrom": "利德斯特伦", "Liebelt": "利贝尔特",
    "Liegel": "利格尔", "Lietz": "利茨", "Lietzow": "利佐", "Liffick": "利菲克",
    "Lifson": "利夫森", "Lightfoot": "莱特富特", "Lighty": "莱蒂", "Ligon": "利贡",
    "Lilavois": "利拉沃伊斯", "Lillard": "利拉德", "Lilley": "利利", "Lillis": "利利斯",
    "Lilly": "利利", "Limerick": "利默里克", "Limon": "利蒙", "Lin": "林",
    "Lincoln": "林肯", "Lindauer": "林道尔", "Lindberg": "林德伯格", "Lindblom": "林德布洛姆",
    "Linde": "林德", "Lindeman": "林德曼", "Lindeman": "林德曼", "Lindley": "林德利",
    "Lindner": "林德纳", "Lindquist": "林德奎斯特", "Lindsey": "林赛", "Lindstrom": "林德斯特伦",
    "Ling": "林", "Link": "林克", "Linkletter": "林克莱特", "Linn": "林恩",
    "Linsenbigler": "林森比格勒", "Linsmeier": "林斯迈尔", "Lintner": "林特纳",
    "Lintz": "林茨", "Linville": "林维尔", "Lipscomb": "利普斯科姆", "Lipuma": "利普马",
    "Lisk": "利斯克", "Lister": "利斯特", "Litherland": "利瑟兰", "Litke": "利特克",
    "Little": "利特尔", "Litzenberger": "利岑伯格", "Liu": "刘", "Livaudais": "利沃代",
    "Livesay": "利夫赛", "Liviakis": "利维亚基斯", "Livingston": "利文斯顿",
    "Lizarraga": "利萨拉加", "Llaneras": "利亚内拉斯", "Llanes": "利亚内斯",
    "Llewellyn": "卢埃林", "Lloyd": "劳埃德", "Loch": "洛克", "Lock": "洛克",
    "Locke": "洛克", "Lockhart": "洛克哈特", "Locklear": "洛克利尔", "Lockridge": "洛克里奇",
    "Lockwood": "洛克伍德", "Loder": "洛德", "Loeber": "洛伯", "Loeffler": "洛夫勒",
    "Lofton": "洛夫顿", "Loftus": "洛夫特斯", "Logan": "洛根", "Logel": "洛格尔",
    "Logsdon": "洛格斯登", "Lohaus": "洛豪斯", "Lohner": "洛纳", "Lohse": "洛斯",
    "Lojeski": "洛耶斯基", "Lola": "洛拉", "Lollar": "洛拉尔", "Lollar": "洛拉尔",
    "Lombard": "隆巴德", "Lombardi": "隆巴迪", "Lomax": "洛马克斯", "Long": "朗",
    "Longstreet": "朗斯特里特", "Lonowski": "洛诺夫斯基", "Looney": "鲁尼",
    "Loop": "卢普", "Loos": "卢斯", "Loosle": "卢斯尔", "Loper": "洛珀",
    "Lopresti": "洛普雷斯蒂", "Lorang": "洛兰", "Lorant": "洛朗", "Lord": "洛德",
    "Lorenz": "洛伦兹", "Lorenzen": "洛伦岑", "Loring": "洛林", "Loritsch": "洛里奇",
    "Lorman": "洛曼", "Loseke": "洛泽克", "Losey": "洛西", "Lotspeich": "洛茨佩奇",
    "Lotts": "洛茨", "Loudon": "劳登", "Loughlin": "洛夫林", "Loughran": "洛夫兰",
    "Loundy": "隆迪", "Loupos": "卢波斯", "Lourdem": "卢尔德姆", "Louth": "劳思",
    "Lovato": "洛瓦托", "Lovell": "洛弗尔", "Lovely": "拉夫利", "Lovett": "洛维特",
    "Lovich": "洛维奇", "Lowder": "劳德", "Lowe": "洛", "Lowery": "洛厄里",
    "Lowhorn": "洛霍恩", "Lowis": "洛伊斯", "Lowman": "洛曼", "Lowrance": "洛伦斯",
    "Lowry": "洛瑞", "Loy": "洛伊", "Loyer": "洛耶", "Lozanoff": "洛扎诺夫",
    "Lozada": "洛萨达", "Lozano": "洛萨诺", "Luba": "卢巴", "Lubarsky": "卢巴尔斯基",
    "Lube": "卢布", "Lucas": "卢卡斯", "Lucas": "卢卡斯", "Luce": "卢斯",
    "Lucero": "卢塞罗", "Luchsinger": "卢辛格", "Lucian": "卢西安", "Luck": "拉克",
    "Luckenbill": "卢肯比尔", "Lucky": "拉基", "Lukenbill": "卢肯比尔", "Luker": "卢克",
    "Luke": "卢克", "Lukens": "卢肯斯", "Lukes": "卢克斯", "Lukomski": "卢科姆斯基",
    "Luksha": "卢克沙", "Lukasavage": "卢卡萨维奇", "Lull": "卢尔", "Luman": "卢曼",
    "Lumb": "拉姆", "Lumbra": "伦布拉", "Lumpp": "伦普", "Luna": "卢纳",
    "Lunceford": "伦斯福德", "Lundy": "伦迪", "Lunger": "伦格", "Lunn": "伦",
    "Lunt": "伦特", "Luoma": "卢奥马", "Luper": "卢珀", "Lush": "勒什",
    "Lussky": "卢斯基", "Lutes": "卢茨", "Luther": "卢瑟", "Lutovsky": "卢托夫斯基",
    "Luttrell": "拉特雷尔", "Lutz": "卢茨", "Luu": "卢", "Lyall": "莱尔",
    "Lybbert": "利伯特", "Lyda": "莱达", "Lydon": "利登", "Lye": "莱",
    "Lykins": "利金斯", "Lyle": "莱尔", "Lynch": "林奇", "Lyness": "莱尼斯",
    "Lynn": "林恩", "Lyon": "莱昂", "Lyons": "莱昂斯", "Lytle": "莱特尔",
    # M-Z 组件见下方（长尾姓氏覆盖）
}

# ============ 组合规则 ============
def compose_zh(full_name):
    """尝试将英文名组合为中文译名；失败返回 None"""
    if not full_name or not isinstance(full_name, str):
        return None
    name = full_name.strip()
    if name in FULL_EXTRA:
        return FULL_EXTRA[name]
    # 拆分名/姓（处理 O'Neal / Van Horn 等复合姓：取最后一段为姓，其余为名）
    parts = name.replace(".", "").split()
    if len(parts) < 2:
        return None
    last = parts[-1]
    first = parts[0]
    zh_first = FIRST_DICT.get(first)
    zh_last = LAST_DICT.get(last)
    if zh_first and zh_last:
        return zh_first + "·" + zh_last
    return None
