# -*- coding: utf-8 -*-
"""
知名 NBA 球员中文名对照表（1996-2026 主要球星与知名轮换）
key = stats.nba.com 数据中的英文全名（"First Last"）
命名遵循新浪/虎扑通用译名惯例
"""

ZH_HIST = {
    # ===== 90s 传奇 =====
    "Michael Jordan": "迈克尔·乔丹", "Scottie Pippen": "斯科蒂·皮蓬", "Dennis Rodman": "丹尼斯·罗德曼",
    "Karl Malone": "卡尔·马龙", "John Stockton": "约翰·斯托克顿", "Hakeem Olajuwon": "哈基姆·奥拉朱旺",
    "Charles Barkley": "查尔斯·巴克利", "Patrick Ewing": "帕特里克·尤因", "David Robinson": "大卫·罗宾逊",
    "Shaquille O'Neal": "沙奎尔·奥尼尔", "Kobe Bryant": "科比·布莱恩特", "Tim Duncan": "蒂姆·邓肯",
    "Allen Iverson": "阿伦·艾弗森", "Reggie Miller": "雷吉·米勒", "Gary Payton": "加里·佩顿",
    "Vince Carter": "文斯·卡特", "Tracy McGrady": "特雷西·麦克格雷迪", "Grant Hill": "格兰特·希尔",
    "Jason Kidd": "贾森·基德", "Kevin Garnett": "凯文·加内特", "Ray Allen": "雷·阿伦",
    "Paul Pierce": "保罗·皮尔斯", "Dirk Nowitzki": "德克·诺维茨基", "Steve Nash": "史蒂夫·纳什",
    "Chris Webber": "克里斯·韦伯", "Juwan Howard": "朱万·霍华德", "Alonzo Mourning": "阿朗佐·莫宁",
    "Dikembe Mutombo": "迪肯贝·穆托姆博", "Anfernee Hardaway": "安芬尼·哈达威",
    "Latrell Sprewell": "拉特里尔·斯普雷维尔", "Rasheed Wallace": "拉希德·华莱士",
    "Jerry Stackhouse": "杰里·斯塔克豪斯", "Stephon Marbury": "斯特芬·马布里",
    "Mitch Richmond": "米奇·里奇蒙德", "Eddie Jones": "埃迪·琼斯", "Glen Rice": "格伦·莱斯",
    "Vin Baker": "文·贝克", "Antoine Walker": "安托万·沃克", "Shawn Kemp": "肖恩·坎普",
    "Tom Gugliotta": "汤姆·古格里奥塔", "Damon Stoudamire": "达蒙·斯塔德迈尔",
    "Christian Laettner": "克里斯蒂安·莱特纳", "Detlef Schrempf": "德特勒夫·施伦普夫",
    "Hersey Hawkins": "赫西·霍金斯", "Dale Ellis": "戴尔·埃利斯", "Rik Smits": "里克·斯密茨",
    "Mark Price": "马克·普莱斯", "Terrell Brandon": "特雷尔·布兰登", "Rod Strickland": "罗德·斯特里克兰德",
    "Nick Van Exel": "尼克·范埃克塞尔", "Mookie Blaylock": "穆基·布莱洛克", "Kenny Anderson": "肯尼·安德森",
    "Clifford Robinson": "克利福德·罗宾逊", "Rony Seikaly": "罗尼·塞卡利", "Elden Campbell": "埃尔登·坎贝尔",
    "Toni Kukoc": "托尼·库科奇", "Ron Harper": "罗恩·哈珀", "Luc Longley": "卢克·朗利",
    "Steve Smith": "史蒂夫·史密斯", "Isaiah Rider": "以赛亚·莱德", "Derrick Coleman": "德里克·科尔曼",
    "Anthony Mason": "安东尼·梅森", "Larry Johnson": "拉里·约翰逊", "Muggsy Bogues": "马格西·博格斯",
    "Horace Grant": "霍勒斯·格兰特", "A.C. Green": "A.C.格林", "Rick Fox": "里克·福克斯",
    "Robert Horry": "罗伯特·霍里", "Mario Elie": "马里奥·埃利", "Sam Cassell": "萨姆·卡塞尔",
    "Nick Anderson": "尼克·安德森", "Allan Houston": "阿兰·休斯顿", "Walt Williams": "沃尔特·威廉姆斯",
    "Tyrone Hill": "泰伦·希尔", "Theo Ratliff": "西奥·拉特利夫", "Brian Shaw": "布莱恩·肖",
    "Derek Fisher": "德里克·费舍尔", "Danny Manning": "丹尼·曼宁", "P.J. Brown": "P.J.布朗",
    "Erick Dampier": "埃里克·丹皮尔", "Jeff Hornacek": "杰夫·霍纳塞克", "Bryon Russell": "布莱恩·拉塞尔",
    "Vlade Divac": "弗拉德·迪瓦茨", "Predrag Stojakovic": "佩贾·斯托贾科维奇",
    "Peja Stojakovic": "佩贾·斯托贾科维奇", "Hedo Turkoglu": "希度·特科格鲁", "Mike Bibby": "迈克·毕比",
    "Jason Williams": "贾森·威廉姆斯", "Bobby Jackson": "博比·杰克逊", "Doug Christie": "道格·克里斯蒂",
    "Shareef Abdur-Rahim": "沙里夫·阿卜杜勒-拉希姆", "Keith Van Horn": "基思·范霍恩",
    "Glenn Robinson": "格伦·罗宾逊", "Antonio McDyess": "安东尼奥·麦克戴斯",
    "Shawn Marion": "肖恩·马里昂", "Marcus Camby": "马库斯·坎比", "Jalen Rose": "杰伦·罗斯",
    "Ron Artest": "罗恩·阿泰斯特", "Metta World Peace": "梅塔·沃尔德·皮斯",
    "Antonio Davis": "安东尼奥·戴维斯", "Charles Oakley": "查尔斯·奥克利", "Dale Davis": "戴尔·戴维斯",
    "Austin Croshere": "奥斯汀·克罗希尔", "Corliss Williamson": "科利斯·威廉姆森",
    "Zach Randolph": "扎克·兰多夫", "Pau Gasol": "保罗·加索尔", "Marc Gasol": "马克·加索尔",
    "Mike Conley": "迈克·康利", "Rudy Gay": "鲁迪·盖伊", "Shane Battier": "肖恩·巴蒂尔",
    "James Posey": "詹姆斯·波西", "Jason Terry": "贾森·特里", "Josh Howard": "约什·霍华德",
    "Devin Harris": "德文·哈里斯", "Marquis Daniels": "马奎斯·丹尼尔斯",
    # ===== 00s 球星 =====
    "LeBron James": "勒布朗·詹姆斯", "Dwyane Wade": "德维恩·韦德", "Carmelo Anthony": "卡梅罗·安东尼",
    "Chris Bosh": "克里斯·波什", "Dwight Howard": "德怀特·霍华德", "Chris Paul": "克里斯·保罗",
    "Brandon Roy": "布兰登·罗伊", "LaMarcus Aldridge": "拉马库斯·阿尔德里奇",
    "Kevin Durant": "凯文·杜兰特", "Russell Westbrook": "拉塞尔·威斯布鲁克", "James Harden": "詹姆斯·哈登",
    "Stephen Curry": "斯蒂芬·库里", "Klay Thompson": "克莱·汤普森", "Draymond Green": "德雷蒙德·格林",
    "Kyrie Irving": "凯里·欧文", "Kawhi Leonard": "科怀·伦纳德", "Anthony Davis": "安东尼·戴维斯",
    "Damian Lillard": "达米安·利拉德", "John Wall": "约翰·沃尔", "DeMarcus Cousins": "德马库斯·考辛斯",
    "Blake Griffin": "布雷克·格里芬", "Kevin Love": "凯文·乐福", "Rajon Rondo": "拉简·朗多",
    "Derrick Rose": "德里克·罗斯", "Al Jefferson": "艾尔·杰弗森", "Gerald Wallace": "杰拉尔德·华莱士",
    "Stephen Jackson": "斯蒂芬·杰克逊", "Monta Ellis": "蒙塔·埃利斯", "Danny Granger": "丹尼·格兰杰",
    "Josh Smith": "约什·史密斯", "Joe Johnson": "乔·约翰逊", "Al Horford": "艾尔·霍福德",
    "Jeff Teague": "杰夫·蒂格", "Kyle Korver": "凯尔·科沃尔", "Jrue Holiday": "朱·霍勒迪",
    "Jameer Nelson": "贾米尔·尼尔森", "Rashard Lewis": "拉沙德·刘易斯", "Gilbert Arenas": "吉尔伯特·阿里纳斯",
    "Caron Butler": "卡隆·巴特勒", "Antawn Jamison": "安托万·贾米森", "Andrei Kirilenko": "安德烈·基里连科",
    "Carlos Boozer": "卡洛斯·布泽尔", "Deron Williams": "德隆·威廉姆斯", "Mehmet Okur": "梅米特·奥库",
    "Zydrunas Ilgauskas": "扎伊德鲁纳斯·伊尔戈斯卡斯", "Mo Williams": "莫·威廉姆斯",
    "Anderson Varejao": "安德森·瓦莱乔", "Delonte West": "德尔onte·韦斯特",
    "Richard Hamilton": "理查德·汉密尔顿", "Ben Wallace": "本·华莱士", "Chauncey Billups": "昌西·比卢普斯",
    "Tayshaun Prince": "泰肖恩·普林斯", "Josh Smith ": "约什·史密斯",
    "Baron Davis": "拜伦·戴维斯", "Jamal Mashburn": "贾马尔·马什本", "Jamal Crawford": "贾马尔·克劳福德",
    "Larry Hughes": "拉里·休斯", "Corey Maggette": "科里·马盖蒂", "Andre Miller": "安德烈·米勒",
    "Elton Brand": "埃尔顿·布兰德", "Lamar Odom": "拉马尔·奥多姆", "Corey Brewer": "科里·布鲁尔",
    "Troy Murphy": "特洛伊·墨菲", "Mike Dunleavy": "迈克·邓利维", "Al Harrington": "艾尔·哈灵顿",
    "Jason Richardson": "贾森·理查德森", "Emeka Okafor": "埃梅卡·奥卡福", "Bernard Robinson": "伯纳德·鲁滨逊",
    "Nene": "内内", "Nene Hilario": "内内·希拉里奥", "Kenyon Martin": "肯扬·马丁",
    "Andre Iguodala": "安德烈·伊格达拉", "Lou Williams": "路·威廉姆斯", "Thaddeus Young": "萨迪斯·杨",
    "Andre Drummond": "安德烈·德拉蒙德", "Greg Monroe": "格雷格·门罗", "Brandon Jennings": "布兰登·詹宁斯",
    "Ersan Ilyasova": "埃尔桑·伊利亚索瓦", "Khris Middleton": "克里斯·米德尔顿",
    "Giannis Antetokounmpo": "扬尼斯·阿德托昆博", "Greg Oden": "格雷格·奥登",
    "Michael Beasley": "迈克尔·比斯利", "O.J. Mayo": "O.J.梅奥", "Eric Gordon": "埃里克·戈登",
    "Trevor Ariza": "特雷沃·阿里扎", "P.J. Tucker": "P.J.塔克", "Ryan Anderson": "莱恩·安德森",
    "Marcin Gortat": "马尔钦·戈塔特", "Emeka Okafor ": "埃梅卡·奥卡福", "Aaron Brooks": "阿隆·布鲁克斯",
    "Kevin Martin": "凯文·马丁", "Brook Lopez": "布鲁克·洛佩兹", "Robin Lopez": "罗宾·洛佩兹",
    "Goran Dragic": "戈兰·德拉季奇", "Luol Deng": "卢奥尔·邓", "Kirk Hinrich": "柯克·辛里奇",
    "Ben Gordon": "本·戈登", "Joakim Noah": "乔金·诺阿", "Taj Gibson": "泰·吉布森",
    "Jimmy Butler": "吉米·巴特勒", "Nikola Mirotic": "尼科拉·米罗蒂奇", "Carlos Boozer ": "卡洛斯·布泽尔",
    "D.J. Augustin": "D.J.奥古斯丁", "Gerald Green": "杰拉德·格林", "J.R. Smith": "J.R.史密斯",
    "Wilson Chandler": "威尔森·钱德勒", "Ty Lawson": "泰·劳森", "Danilo Gallinari": "达尼洛·加里纳利",
    "Raymond Felton": "雷蒙德·费尔顿", "Timofey Mozgov": "季莫费·莫兹戈夫", "Kenneth Faried": "肯尼斯·法里德",
    "Arron Afflalo": "阿隆·阿弗拉罗", "Jameer Nelson ": "贾米尔·尼尔森", "J.J. Redick": "J.J.雷迪克",
    "Jared Dudley": "贾里德·达德利", "Matt Barnes": "马特·巴恩斯", "Steve Blake": "史蒂夫·布雷克",
    "Shannon Brown": "香农·布朗", "Jordan Farmar": "乔丹·法玛尔", "Sasha Vujacic": "萨沙·武贾西奇",
    "Andrew Bynum": "安德鲁·拜纳姆", "Adam Morrison": "亚当·莫里森", "Derek Fisher ": "德里克·费舍尔",
    "Josh Powell": "约什·鲍威尔", "D.J. Mbenga": "D.J.姆本加", "Luke Walton": "卢克·沃顿",
    "Tony Parker": "托尼·帕克", "Manu Ginobili": "马努·吉诺比利", "Boris Diaw": "鲍里斯·迪奥",
    "Tiago Splitter": "蒂亚戈·斯普利特", "Patty Mills": "帕蒂·米尔斯", "Danny Green": "丹尼·格林",
    "Cory Joseph": "科里·约瑟夫", "Kyle Anderson": "凯尔·安德森", "Dejounte Murray": "德章泰·穆雷",
    "Marco Belinelli": "马科·贝里内利", "Rudy Gay ": "鲁迪·盖伊", "Danny Green ": "丹尼·格林",
    # ===== 10s/20s =====
    "Kemba Walker": "肯巴·沃克", "Gordon Hayward": "戈登·海沃德", "Nicolas Batum": "尼古拉斯·巴图姆",
    "Al Jefferson ": "艾尔·杰弗森", "Paul Millsap": "保罗·米尔萨普", "Jeff Teague ": "杰夫·蒂格",
    "Kyle Lowry": "凯尔·洛瑞", "DeMar DeRozan": "德玛尔·德罗赞", "Jonas Valanciunas": "约纳斯·瓦兰丘纳斯",
    "Terrence Ross": "特伦斯·罗斯", "Serge Ibaka": "塞尔吉·伊巴卡", "Fred VanVleet": "弗雷德·范弗里特",
    "OG Anunoby": "OG阿努诺比", "Pascal Siakam": "帕斯卡尔·西亚卡姆", "Scottie Barnes": "斯科蒂·巴恩斯",
    "Rudy Gobert": "鲁迪·戈贝尔", "Donovan Mitchell": "多诺万·米切尔", "Jamal Murray": "贾马尔·穆雷",
    "Nikola Jokic": "尼科拉·约基奇", "Gary Harris": "加里·哈里斯", "Will Barton": "威尔·巴顿",
    "Aaron Gordon": "阿隆·戈登", "Michael Porter Jr.": "小迈克尔·波特", "Zach LaVine": "扎克·拉文",
    "Andrew Wiggins": "安德鲁·维金斯", "Karl-Anthony Towns": "卡尔-安东尼·唐斯", "Tyus Jones": "泰厄斯·琼斯",
    "Nemanja Bjelica": "内马尼亚·别利察", "D'Angelo Russell": "德安杰洛·拉塞尔", "Anthony Edwards": "安东尼·爱德华兹",
    "Julius Randle": "朱利叶斯·兰德尔", "RJ Barrett": "RJ巴雷特", "Mitchell Robinson": "米切尔·罗宾逊",
    "Immanuel Quickley": "伊曼纽尔·奎克利", "Obi Toppin": "奥比·托平", "Quentin Grimes": "昆廷·格兰姆斯",
    "Josh Hart": "约什·哈特", "Donte DiVincenzo": "唐特·迪文琴佐", "Jalen Brunson": "杰伦·布伦森",
    "Mikal Bridges": "米卡尔·布里奇斯", "Cameron Johnson": "卡梅隆·约翰逊", "Deandre Ayton": "德安德烈·艾顿",
    "Devon Booker": "德文·布克", "Devin Booker": "德文·布克", "T.J. Warren": "T.J.沃伦",
    "Myles Turner": "迈尔斯·特纳", "Domantas Sabonis": "多曼塔斯·萨博尼斯", "Victor Oladipo": "维克托·奥拉迪波",
    "Tyrese Haliburton": "泰瑞斯·哈利伯顿", "Buddy Hield": "巴迪·希尔德", "Darius Garland": "达柳斯·加兰",
    "Evan Mobley": "埃文·莫布利", "Jarrett Allen": "贾勒特·艾伦", "Collin Sexton": "科林·塞克斯顿",
    "Lauri Markkanen": "劳里·马尔卡宁", "Zion Williamson": "锡安·威廉姆森", "Brandon Ingram": "布兰登·英格拉姆",
    "Lonzo Ball": "朗佐·鲍尔", "LaMelo Ball": "拉梅洛·鲍尔", "Terry Rozier": "特里·罗齐尔",
    "Gordon Hayward ": "戈登·海沃德", "Kelly Oubre Jr.": "小凯利·乌布雷", "Miles Bridges": "迈尔斯·布里奇斯",
    "P.J. Washington": "P.J.华盛顿", "Trae Young": "特雷·杨", "John Collins": "约翰·科林斯",
    "Kevin Huerter": "凯文·赫尔特", "De'Andre Hunter": "德安德烈·亨特", "Dejounte Murray ": "德章泰·穆雷",
    "Bogdan Bogdanovic": "博格丹·博格达诺维奇", "Bojan Bogdanovic": "博扬·博格达诺维奇",
    "Clint Capela": "克林特·卡佩拉", "Onyeka Okongwu": "奥涅卡·奥孔古", "Jalen Johnson": "杰伦·约翰逊",
    "Joel Embiid": "乔尔·恩比德", "Ben Simmons": "本·西蒙斯", "Tobias Harris": "托拜厄斯·哈里斯",
    "Tyrese Maxey": "泰瑞斯·马克西", "Matisse Thybulle": "马蒂斯·塞布尔", "Shake Milton": "谢克·米尔顿",
    "Robert Covington": "罗伯特·科温顿", "Dario Saric": "达里奥·萨里奇", "Furkan Korkmaz": "富尔坎·科尔克马兹",
    "Dwight Powell": "德怀特·鲍威尔", "Maxi Kleber": "马克西·克勒贝尔", "Dorian Finney-Smith": "多里安·芬尼-史密斯",
    "Spencer Dinwiddie": "斯宾塞·丁威迪", "Jalen Smith": "杰伦·史密斯", "Christian Wood": "克里斯蒂安·伍德",
    "Ja Morant": "贾·莫兰特", "Jaren Jackson Jr.": "小贾伦·杰克逊", "Desmond Bane": "德斯蒙德·贝恩",
    "Brandon Clarke": "布兰登·克拉克", "Dillon Brooks": "狄龙·布鲁克斯", "Steven Adams": "史蒂文·亚当斯",
    "Shai Gilgeous-Alexander": "谢伊·吉尔杰斯-亚历山大", "Josh Giddey": "约什·吉迪", "Lu Dort": "吕·多尔特",
    "Chet Holmgren": "切特·霍姆格伦", "Jalen Williams": "杰伦·威廉姆斯", "Jaylin Williams": "杰林·威廉姆斯",
    "Luka Doncic": "卢卡·东契奇", "Kristaps Porzingis": "克里斯塔普斯·波尔津吉斯",
    "Tim Hardaway Jr.": "小蒂姆·哈达威", "Tim Hardaway": "蒂姆·哈达威", "Tim Hardaway Jr": "小蒂姆·哈达威",
    "De'Aaron Fox": "达龙·福克斯", "Domantas Sabonis ": "多曼塔斯·萨博尼斯", "Keegan Murray": "基根·穆雷",
    "Harrison Barnes": "哈里森·巴恩斯", "Malik Monk": "马利克·蒙克", "Richaun Holmes": "里乔恩·霍姆斯",
    "Jayson Tatum": "杰森·塔图姆", "Jaylen Brown": "杰伦·布朗", "Marcus Smart": "马库斯·斯马特",
    "Al Horford ": "艾尔·霍福德", "Derrick White": "德里克·怀特", "Robert Williams": "罗伯特·威廉姆斯",
    "Robert Williams III": "罗伯特·威廉姆斯三世", "Payton Pritchard": "佩顿·普里查德",
    "Grant Williams": "格兰特·威廉姆斯", "Aaron Nesmith": "亚伦·内史密斯", "Malcolm Brogdon": "马尔科姆·布罗格登",
    "Dennis Schroder": "丹尼斯·施罗德", "Daniel Theis": "丹尼尔·泰斯", "Tristan Thompson": "特里斯坦·汤普森",
    "Enes Kanter": "埃内斯·坎特", "Enes Freedom": "埃内斯·坎特", "Bruce Brown": "布鲁斯·布朗",
    "Reggie Jackson": "雷吉·杰克逊", "Marcus Morris": "马库斯·莫里斯", "Markieff Morris": "马基夫·莫里斯",
    "Norman Powell": "诺曼·鲍威尔", "Terance Mann": "特兰斯·曼", "Ivica Zubac": "伊维察·祖巴茨",
    "Luke Kennard": "卢克·肯纳德", "Landry Shamet": "兰德里·沙梅特", "Amir Coffey": "阿米尔·科菲",
    "Nicolas Batum ": "尼古拉斯·巴图姆", "CJ McCollum": "CJ麦科勒姆", "Jusuf Nurkic": "优素福·努尔基奇",
    "Anfernee Simons": "安芬尼·西蒙斯", "Nassir Little": "纳西尔·利特尔", "Gary Payton II": "加里·佩顿二世",
    "Jerami Grant": "杰拉米·格兰特", "Monte Morris": "蒙特·莫里斯", "Will Barton ": "威尔·巴顿",
    "Michael Porter": "小迈克尔·波特", "Bruce Brown ": "布鲁斯·布朗", "Kentavious Caldwell-Pope": "肯塔维奥斯·考德威尔-波普",
    "Austin Reaves": "奥斯汀·里维斯", "Rui Hachimura": "八村塁", "Jarred Vanderbilt": "贾里德·范德比尔特",
    "Mo Bamba": "莫·班巴", "Thomas Bryant": "托马斯·布莱恩特", "Wenyen Gabriel": "文彦·加布里埃尔",
    "Lonnie Walker IV": "朗尼·沃克四世", "Troy Brown Jr.": "小特洛伊·布朗", "Max Christie": "马克斯·克里斯蒂",
    "Wenyen Gabriel ": "文彦·加布里埃尔", "Juan Toscano-Anderson": "胡安·托斯卡诺-安德森",
    "Jordan Poole": "乔丹·普尔", "Jonathan Kuminga": "乔纳森·库明加", "Moses Moody": "摩西·穆迪",
    "Kevon Looney": "凯文·卢尼", "James Wiseman": "詹姆斯·怀斯曼", "Andrew Wiggins ": "安德鲁·维金斯",
    "Otto Porter Jr.": "小奥托·波特", "JaMychal Green": "杰迈克尔·格林", "Donte DiVincenzo ": "唐特·迪文琴佐",
    "Andre Iguodala ": "安德烈·伊格达拉", "Klay Thompson ": "克莱·汤普森", "Draymond Green ": "德雷蒙德·格林",
    "Stephen Curry ": "斯蒂芬·库里", "Jordan Clarkson": "乔丹·克拉克森", "Collin Sexton ": "科林·塞克斯顿",
    "Tal porte": "泰尔·波特", "Tal Horton-Tucker": "塔伦·霍顿-塔克", "Santi Aldama": "桑蒂·阿尔达马",
    "Tyus Jones ": "泰厄斯·琼斯", "Steven Adams ": "史蒂文·亚当斯", "Ziaire Williams": "齐亚尔·威廉姆斯",
    "De'Anthony Melton": "德安东尼·梅尔顿", "Xavier Tillman": "泽维尔·蒂尔曼", "John Konchar": "约翰·孔查尔",
    "Brandon Ingram ": "布兰登·英格拉姆", "CJ McCollum ": "CJ麦科勒姆", "Herbert Jones": "赫伯特·琼斯",
    "Jose Alvarado": "何塞·阿尔瓦拉多", "Trey Murphy III": "特雷·墨菲三世", "Naji Marshall": "纳吉·马歇尔",
    "Jonas Valanciunas ": "约纳斯·瓦兰丘纳斯", "Dyson Daniels": "戴森·丹尼尔斯",
    "Jaxson Hayes": "杰克逊·海耶斯", "Kevin Huerter ": "凯文·赫尔特", "Kevin Knox": "凯文·诺克斯",
    "Julius Randle ": "朱利叶斯·兰德尔", "Isaiah Hartenstein": "以赛亚·哈尔滕施泰因",
    "Immanuel Quickley ": "伊曼纽尔·奎克利", "Precious Achiuwa": "普雷舍斯·阿丘瓦",
    "Evan Fournier": "埃文·富尼耶", "Alec Burks": "亚历克·伯克斯", "Derrick Rose ": "德里克·罗斯",
    "Norris Cole": "诺里斯·科尔", "Mario Chalmers": "马里奥·查尔默斯", "Udonis Haslem": "乌杜尼斯·哈斯勒姆",
    "Shane Battier ": "肖恩·巴蒂尔", "Mike Miller": "迈克·米勒", "Ray Allen ": "雷·阿伦",
    "Rashard Lewis ": "拉沙德·刘易斯", "Chris Bosh ": "克里斯·波什", "Dwyane Wade ": "德维恩·韦德",
    "LeBron James ": "勒布朗·詹姆斯", "Kevin Love ": "凯文·乐福", "Kyrie Irving ": "凯里·欧文",
    "Isaiah Thomas": "以赛亚·托马斯", "Kelly Olynyk": "凯利·奥利尼克", "Avery Bradley": "艾弗里·布拉德利",
    "Marcus Morris ": "马库斯·莫里斯", "Serge Ibaka ": "塞尔吉·伊巴卡", "Norman Powell ": "诺曼·鲍威尔",
    "Patrick Patterson": "帕特里克·帕特森", "Pascal Siakam ": "帕斯卡尔·西亚卡姆",
    "OG Anunoby ": "OG阿努诺比", "Chris Boucher": "克里斯·布歇", "Yuta Watanabe": "渡边雄太",
    "Khem Birch": "凯姆·伯奇", "Armoni Brooks": "阿莫尼·布鲁克斯", "David Johnson": "大卫·约翰逊",
    "Dalano Banton": "达拉诺·班顿", "Justin Champagnie": "贾斯汀·尚帕尼",
    "Thaddeus Young ": "萨迪斯·杨", "Andre Drummond ": "安德烈·德拉蒙德", "Blake Griffin ": "布雷克·格里芬",
    "LaMarcus Aldridge ": "拉马库斯·阿尔德里奇", "Paul Millsap ": "保罗·米尔萨普",
    "Jeff Green": "杰夫·格林", "JaVale McGee": "贾维尔·麦基", "Markieff Morris ": "马基夫·莫里斯",
    "Rajon Rondo ": "拉简·朗多", "DJ Augustin": "D.J.奥古斯丁", "E'Twaun Moore": "伊托万·摩尔",
    "Garrett Temple": "加勒特·坦普尔", "Willy Hernangomez": "威利·埃尔南戈麦斯",
    "Devonte' Graham": "德文特·格雷厄姆", "Frank Jackson": "弗兰克·杰克逊", "Kira Lewis Jr.": "小基拉·刘易斯",
    "Nickeil Alexander-Walker": "尼基尔·亚历山大-沃克", "Jaxson Hayes ": "杰克逊·海耶斯",
    "Dario Saric ": "达里奥·萨里奇", "James Johnson": "詹姆斯·约翰逊", "Cody Martin": "科迪·马丁",
    "Caleb Martin": "凯莱布·马丁", "P.J. Hairston": "P.J.海尔斯顿", "Malik Monk ": "马利克·蒙克",
    "James Bouknight": "詹姆斯·布克奈特", "Kai Jones": "凯·琼斯", "Vernon Carey Jr.": "小弗农·凯里",
    "JT Thor": "JT索尔", "Nick Richards": "尼克·理查兹", "Mark Williams": "马克·威廉姆斯",
    "Dennis Smith Jr.": "小丹尼斯·史密斯", "Theo Pinson": "西奥·平森", "Bryce McGowens": "布莱斯·麦高文斯",
    # ===== 老将补充 =====
    "Jason Terry ": "贾森·特里", "Jason Kidd ": "贾森·基德", "Vince Carter ": "文斯·卡特",
    "Dirk Nowitzki ": "德克·诺维茨基", "Paul Pierce ": "保罗·皮尔斯", "Kevin Garnett ": "凯文·加内特",
    "Raymond Felton ": "雷蒙德·费尔顿", "Amar'e Stoudemire": "阿玛雷·斯塔德迈尔",
    "Amare Stoudemire": "阿玛雷·斯塔德迈尔", "Shaquille O'Neal ": "沙奎尔·奥尼尔",
    "Tim Duncan ": "蒂姆·邓肯", "Manu Ginobili ": "马努·吉诺比利", "Tony Parker ": "托尼·帕克",
    "Kobe Bryant ": "科比·布莱恩特", "Pau Gasol ": "保罗·加索尔", "Dwight Howard ": "德怀特·霍华德",
    "Carmelo Anthony ": "卡梅罗·安东尼", "Russell Westbrook ": "拉塞尔·威斯布鲁克",
    "James Harden ": "詹姆斯·哈登", "Kevin Durant ": "凯文·杜兰特", "Chris Paul ": "克里斯·保罗",
    "Anthony Davis ": "安东尼·戴维斯", "Marc Gasol ": "马克·加索尔", "Mike Conley ": "迈克·康利",
    "Zach Randolph ": "扎克·兰多夫", "Tony Allen": "托尼·阿伦", "Rudy Gobert ": "鲁迪·戈贝尔",
    "Donovan Mitchell ": "多诺万·米切尔", "Joe Ingles": "乔·英格尔斯", "Ricky Rubio": "里基·卢比奥",
    "Derrick Favors": "德里克·费沃斯", "Alec Burks ": "亚历克·伯克斯", "Dante Exum": "丹特·埃克萨姆",
    "Trey Lyles": "特雷·莱尔斯", "Raul Neto": "劳尔·内托", "Georges Niang": "乔治斯·尼昂",
    "Royce O'Neale": "罗伊斯·奥尼尔", "Jordan Clarkson ": "乔丹·克拉克森",
    "Emmanuel Mudiay": "伊曼纽尔·穆迪埃", "Tobias Harris ": "托拜厄斯·哈里斯",
    "Boban Marjanovic": "博班·马里亚诺维奇", "Seth Curry": "赛斯·库里", "Furkan Korkmaz ": "富尔坎·科尔克马兹",
    "Shake Milton ": "谢克·米尔顿", "Matisse Thybulle ": "马蒂斯·塞布尔", "Isaiah Joe": "以赛亚·乔",
    "Paul Reed": "保罗·里德", "Charles Bassey": "查尔斯·巴锡", "Jaden Springer": "杰登·斯普林格",
    # ===== 国际球员 =====
    "Tony Parker  ": "托尼·帕克", "Luka Doncic ": "卢卡·东契奇", "Nikola Vucevic": "尼科拉·武切维奇",
    "Wendell Carter Jr.": "小温德尔·卡特", "Cole Anthony": "科尔·安东尼", "Franz Wagner": "弗朗茨·瓦格纳",
    "Paolo Banchero": "保罗·班切罗", "Jalen Suggs": "杰伦·萨格斯", "Markelle Fultz": "马克尔·富尔茨",
    "Jonathan Isaac": "乔纳森·艾萨克", "Mo Bamba ": "莫·班巴", "Chuma Okeke": "丘马·奥基基",
    "Bol Bol": "波尔·波尔", "RJ Hampton": "RJ汉普顿", "Gary Trent Jr.": "小加里·特伦特",
    "Jakob Poeltl": "雅各布·珀尔特尔", "Doug McDermott": "道格·麦克德莫特", "Josh Richardson": "约什·理查德森",
    "Devin Vassell": "德文·瓦塞尔", "Keldon Johnson": "凯尔登·约翰逊", "Tre Jones": "特雷·琼斯",
    "Jeremy Sochan": "杰里米·索汉", "Malaki Branham": "马拉基·布兰纳姆", "Blake Wesley": "布莱克·韦斯利",
    "Devonte Graham ": "德文特·格雷厄姆", "Kelly Oubre Jr. ": "小凯利·乌布雷",
    "Terrence Ross ": "特伦斯·罗斯", "Mohamed Bamba": "穆罕默德·班巴", "Michael Carter-Williams": "迈克尔·卡特-威廉姆斯",
    "Victor Oladipo ": "维克托·奥拉迪波", "Domantas Sabonis  ": "多曼塔斯·萨博尼斯",
    "Myles Turner ": "迈尔斯·特纳", "T.J. McConnell": "T.J.麦康奈尔", "Aaron Holiday": "阿隆·霍勒迪",
    "Justin Holiday": "贾斯汀·霍勒迪", "Duane Washington Jr.": "小杜安·华盛顿",
    "Buddy Hield ": "巴迪·希尔德", "Tyrese Haliburton ": "泰瑞斯·哈利伯顿",
    "Isaiah Jackson": "以赛亚·杰克逊", "Andrew Nembhard": "安德鲁·内姆哈德",
    "Bennedict Mathurin": "本内迪克特·马图林", "Jarace Walker": "贾雷斯·沃克",
    "Kobe Bufkin": "科比·布夫金", "AJ Griffin": "AJ格里芬", "Jalen Hood-Schifino": "杰伦·胡德-希菲诺",
    "Ausar Thompson": "奥萨尔·汤普森", "Amen Thompson": "阿门·汤普森",
    "Anthony Black": "安东尼·布莱克", "Jett Howard": "杰特·霍华德", "Gradey Dick": "格雷迪·迪克",
    "Taylor Hendricks": "泰勒·亨德里克斯", "Jarace Walker ": "贾雷斯·沃克",
    "Victor Wembanyama": "维克托·文班亚马", "Scoot Henderson": "斯库特·亨德森",
    "Brandon Miller": "布兰登·米勒", " Amen Thompson": "阿门·汤普森",
    # ===== 历史角色球员补充 =====
    "Charlie Ward": "查理·沃德", "Chris Childs": "克里斯·奇尔兹", "Chris Dudley": "克里斯·达德利",
    "Buck Williams": "巴克·威廉姆斯", "Jayson Williams": "杰森·威廉姆斯", "Chris Gatling": "克里斯·加特林",
    "Tony Delk": "托尼·德尔克", "Bob Sura": "鲍勃·苏拉", "Olden Polynice": "奥尔登·波利尼斯",
    "Felton Spencer": "费尔顿·斯宾塞", "Stacey Augmon": "斯塔西·奥格蒙", "George McCloud": "乔治·麦克劳德",
    "Chris Carr": "克里斯·卡尔", "Travis Knight": "特拉维斯·奈特", "Corey Benjamin": "科里·本杰明",
    "Randy Brown": "兰迪·布朗", "Dickey Simpkins": "迪基·辛普金斯", "Jud Buechler": "贾德·布希勒",
    "Steve Kerr": "史蒂夫·科尔", "Bill Wennington": "比尔·温宁顿", "Jason Caffey": "贾森·卡菲",
    "Randy Brown ": "兰迪·布朗", "Will Perdue": "威尔·珀杜", "Dickey Simpkins ": "迪基·辛普金斯",
    "Keith Booth": "基思·布斯", "Rusty LaRue": "拉斯蒂·拉鲁", "Keith Bogans": "基思·博甘斯",
    "Fred Hoiberg": "弗雷德·霍伊博格", "Dalibor Bagaric": "达利博尔·巴加里奇", "Dragan Tarlac": "德拉甘·塔拉克",
    "A.J. Guyton": "A.J.盖顿", "Ron Mercer": "罗恩·默瑟", "Brad Miller": "布拉德·米勒",
    "Marcus Fizer": "马库斯·费泽尔", "Eddy Curry": "埃迪·库里", "Tyson Chandler": "泰森·钱德勒",
    "Jay Williams": "杰·威廉姆斯", "Chris Duhon": "克里斯·杜洪", "Luol Deng ": "卢奥尔·邓",
    "Othella Harrington": "奥塞拉·哈灵顿", "Mike Sweetney": "迈克·斯威特尼", "Eric Piatkowski": "埃里克·皮亚考斯基",
    "Jannero Pargo": "詹内罗·帕戈", "Trenton Hassell": "特伦顿·哈塞尔", "Mark Madsen": "马克·马德森",
    "Brian Cardinal": "布莱恩·卡迪纳尔", "Greg Buckner": "格雷格·巴克纳", "Ryan Hollins": "莱恩·霍林斯",
    "Craig Smith": "克雷格·史密斯", "Ryan Gomes": "莱恩·戈麦斯", "Mark Blount": "马克·布朗特",
    "Randy Foye": "兰迪·弗耶", "Rashad McCants": "拉沙德·麦坎茨", "Sebastian Telfair": "塞巴斯蒂安·特尔费尔",
    "Marko Jaric": "马尔科·雅里奇", "Ricky Davis": "里基·戴维斯", "Wally Szczerbiak": "沃利·斯泽比亚克",
    "Troy Hudson": "特洛伊·哈德森", "Michael Olowokandi": "迈克尔·奥洛沃坎迪", "Mark Blount ": "马克·布朗特",
    "Trenton Hassell ": "特伦顿·哈塞尔", "Sam Cassell ": "萨姆·卡塞尔", "Latrell Sprewell ": "拉特里尔·斯普雷维尔",
    "Ervin Johnson": "欧文·约翰逊", "Anthony Peeler": "安东尼·皮勒", "Joe Smith ": "乔·史密斯",
    "Marc Jackson": "马克·杰克逊", "Rod Strickland ": "罗德·斯特里克兰德", "Anthony Carter": "安东尼·卡特",
    "Quincy Lewis": "昆西·刘易斯", "LaPhonso Ellis": "拉方索·埃利斯", "Chauncey Billups ": "昌西·比卢普斯",
    "Terrell Brandon ": "特雷尔·布兰登", "Wally Szczerbiak ": "沃利·斯泽比亚克", "Joe Smith  ": "乔·史密斯",
    "Gary Trent": "加里·特伦特", "Dean Garrett": "迪恩·加勒特", "William Avery": "威廉·艾弗里",
    "Sam Jacobson": "萨姆·雅各布森", "Radoslav Nesterovic": "拉多斯拉夫·内斯特洛维奇",
    "Beno Udrih": "贝诺·乌德里", "Brent Barry": "布伦特·巴里", "Speedy Claxton": "斯皮迪·克拉克斯顿",
    "Devin Brown": "德文·布朗", "Melvin Ely": "梅尔文·伊利", "Brendan Haywood": "布伦丹·海伍德",
    "DeShawn Stevenson": "德肖恩·史蒂文森", "Etan Thomas": "埃坦·托马斯", "Jarvis Hayes": "贾维斯·海耶斯",
    "Andray Blatche": "安德雷·布拉奇", "Brendan Haywood ": "布伦丹·海伍德", "Roger Mason": "罗杰·梅森",
    "Roger Mason Jr.": "小罗杰·梅森", "Dominic McGuire": "多米尼克·麦圭尔", "Nick Young": "尼克·杨",
    "JaVale McGee ": "贾维尔·麦基", "Andray Blatche ": "安德雷·布拉奇", "Cartier Martin": "卡地亚·马丁",
    "Kevin Seraphin": "凯文·塞拉芬", "Jan Vesely": "扬·维塞利", "Chris Singleton": "克里斯·辛格尔顿",
    "Shelvin Mack": "谢尔文·麦克", "Jordan Hill": "乔丹·希尔", "Trevor Booker": "特雷弗·布克",
    "Josh McRoberts": "约什·麦克罗伯茨", "Al-Farouq Aminu": "阿尔-法鲁克·阿米奴", "Elfrid Payton": "埃尔弗里德·佩顿",
    "Aaron Gordon ": "阿隆·戈登", "Victor Oladipo  ": "维克托·奥拉迪波", "Nikola Vucevic ": "尼科拉·武切维奇",
    "Evan Fournier ": "埃文·富尼耶", "Dewayne Dedmon": "德维恩·德德蒙", "Bismack Biyombo": "俾斯麦·比永博",
    "Mario Hezonja": "马里奥·海佐尼亚", "Frank Kaminsky": "弗兰克·卡明斯基", "Jerian Grant": "杰里安·格兰特",
    "Jeff Green ": "杰夫·格林", "Wesley Iwundu": "韦斯·伊文杜", "Mohamed Bamba ": "穆罕默德·班巴",
    "Melvin Frazier": "梅尔文·弗雷泽", "Amile Jefferson": "阿米勒·杰斐逊", "Troy Caupain": "特洛伊·考佩恩",
    "Khem Birch ": "凯姆·伯奇", "Gary Clark ": "加里·克拉克", "Michael Carter-Williams ": "迈克尔·卡特-威廉姆斯",
    "Wes Iwundu ": "韦斯·伊文杜", "James Ennis": "詹姆斯·恩尼斯", "D.J. Augustin ": "D.J.奥古斯丁",
    "Vince Carter  ": "文斯·卡特", "Trae Young ": "特雷·杨", "John Collins ": "约翰·科林斯",
    "Kevin Huerter ": "凯文·赫尔特", "Cam Reddish": "卡姆·雷迪什", "De'Andre Hunter ": "德安德烈·亨特",
    "Bruno Fernando": "布鲁诺·费尔南多", "Kris Dunn": "克里斯·邓恩", "Brandon Goodwin": "布兰登·古德温",
    "Skylar Mays": "斯凯拉·梅斯", "Deshawn Harris-Dyson": "德肖恩·哈里斯-戴森",
    "Charlie Brown Jr.": "小查理·布朗", "Trevon Duval": "特雷文·杜瓦尔", "Jaylen Adams": "杰伦·亚当斯",
    "Alex Len": "亚历克斯·莱恩", "Omari Spellman": "奥马里·斯佩尔曼", "DeAndre' Bembry": "德安德烈·本布里",
    "Allen Crabbe": "阿伦·克拉布", "Justin Anderson": "贾斯汀·安德森", "DeAndre Bembry": "德安德烈·本布里",
    "Jordan McRae": "乔丹·麦克雷", "Isaiah Roby": "以赛亚·罗比", "Josh Reaves": "约什·里夫斯",
    "Saben Lee": "萨本·李", "Deividas Sirvydis": "戴维达斯·西尔维迪斯", "Nikolas Radicevic": "尼古拉斯·拉迪切维奇",
    # ===== 湖人/热火名宿补充 =====
    "Brian Grant": "布莱恩·格兰特", "Lamar Odom ": "拉马尔·奥多姆", "Caron Butler ": "卡隆·巴特勒",
    "Smush Parker": "斯马什·帕克", "Kwame Brown": "夸梅·布朗", "Vladimir Radmanovic": "弗拉迪米尔·拉德马诺维奇",
    "Ronny Turiaf": "罗尼·图里亚夫", "Chris Mihm": "克里斯·米姆", "Von Wafer": "冯·韦弗",
    "Sun Yue": "孙悦", "Josh Powell ": "约什·鲍威尔", "Udonis Haslem ": "乌杜尼斯·哈斯勒姆",
    "Michael Beasley ": "迈克尔·比斯利", "Dorell Wright": "多雷尔·赖特", "Daequan Cook": "戴奎恩·库克",
    "Yakhouba Diawara": "亚库巴·迪亚瓦拉", "Marcus Banks": "马库斯·班克斯", "Antoine Walker ": "安托万·沃克",
    "James Posey ": "詹姆斯·波西", "Jason Kapono": "杰森·卡波诺", "Eddie Jones ": "埃迪·琼斯",
    "Brian Grant ": "布莱恩·格兰特", "Lamar Odom  ": "拉马尔·奥多姆", "Caron Butler  ": "卡隆·巴特勒",
    "Stromile Swift": "斯特罗迈尔·斯威夫特", "Bonzi Wells": "邦奇·威尔斯", "Mike Miller ": "迈克·米勒",
    "Hakim Warrick": "哈基姆·沃里克", "Kyle Lowry ": "凯尔·洛瑞", "Rudy Gay  ": "鲁迪·盖伊",
    "Marc Gasol  ": "马克·加索尔", "O.J. Mayo ": "O.J.梅奥", "Hasheem Thabeet": "哈希姆·塔比特",
    "Sam Young": "萨姆·杨", "Darrell Arthur ": "达雷尔·亚瑟", "Hamed Haddadi": "哈米德·哈达迪",
    "Tony Allen ": "托尼·阿伦", "Zach Randolph  ": "扎克·兰多夫", "Mike Conley  ": "迈克·康利",
    "Othella Harrington ": "奥塞拉·哈灵顿", "Darius Miles": "达柳斯·迈尔斯", "Qyntel Woods": "昆特尔·伍兹",
    "Bonzi Wells ": "邦奇·威尔斯", "James Posey  ": "詹姆斯·波西", "Pau Gasol  ": "保罗·加索尔",
    "Juan Carlos Navarro": "胡安·卡洛斯·纳瓦罗", "Casey Jacobsen": "凯西·雅各布森", "Dahntay Jones": "达坦·琼斯",
    "Shane Battier  ": "肖恩·巴蒂尔", "Stromile Swift ": "斯特罗迈尔·斯威夫特", "Hakim Warrick ": "哈基姆·沃里克",
    "Tarence Kinsey": "泰伦斯·金西", "Antonio Burks": "安东尼奥·伯克斯", "Brian Cardinal ": "布莱恩·卡迪纳尔",
    "Troy Bell": "特洛伊·贝尔", "Dahntay Jones ": "达坦·琼斯", "Andrei Kirilenko ": "安德烈·基里连科",
    "Mehmet Okur ": "梅米特·奥库", "Gordan Giricek": "戈登·吉里塞克", "Alexis Ajinca": "阿莱克西·阿金萨",
    "Kosta Koufos": "科斯塔·库弗斯", "Demarre Carroll": "德马尔·卡罗尔", "Ivan Johnson": "伊万·约翰逊",
    "DeMarre Carroll": "德马尔·卡罗尔", "Jamaal Tinsley": "贾马尔·汀斯利", "Marvin Williams": "马文·威廉姆斯",
    "Josh Howard ": "约什·霍华德", "Devin Harris ": "德文·哈里斯", "Jason Terry  ": "贾森·特里",
    "Erick Dampier ": "埃里克·丹皮尔", "DeSagana Diop": "德萨加纳·迪奥普", "Marquis Daniels ": "马奎斯·丹尼尔斯",
    "Adrian Griffin": "阿德里安·格里芬", "Courtney Alexander": "考特尼·亚历山大", "Courtney Lee": "考特尼·李",
    "Matt Harpring": "马特·哈普林", "Andrei Kirilenko  ": "安德烈·基里连科", "Paul Millsap ": "保罗·米尔萨普",
    "Deron Williams ": "德隆·威廉姆斯", "Carlos Arroyo": "卡洛斯·阿罗约", "Gordan Giricek ": "戈登·吉里塞克",
    "Matt Harpring ": "马特·哈普林", "Kyrylo Fesenko": "基里洛·费森科", " Ronnie Price": "罗尼·普莱斯",
    "Ronnie Price": "罗尼·普莱斯", "C.J. Miles": "C.J.迈尔斯", "Kyle Korver ": "凯尔·科沃尔",
    "Wesley Matthews": "韦斯利·马修斯", "Al Jefferson  ": "艾尔·杰弗森", "Paul Millsap  ": "保罗·米尔萨普",
    "Derrick Favors ": "德里克·费沃斯", "Enes Kanter ": "埃内斯·坎特", "Alec Burks  ": "亚历克·伯克斯",
    "Gordon Hayward  ": "戈登·海沃德", "Rudy Gobert  ": "鲁迪·戈贝尔", "Dante Exum ": "丹特·埃克萨姆",
    "Raul Neto ": "劳尔·内托", "Ricky Rubio ": "里基·卢比奥", "Derrick Favors  ": "德里克·费沃斯",
    "Georges Niang ": "乔治斯·尼昂", "Joe Ingles ": "乔·英格尔斯", "Donovan Mitchell  ": "多诺万·米切尔",
    "Royce O'Neale ": "罗伊斯·奥尼尔", "Dante Exum  ": "丹特·埃克萨姆", "Ekpe Udoh": "埃克佩·乌多",
    "Nigel Williams-Goss": "奈杰尔·威廉姆斯-戈斯", "Tony Bradley": "托尼·布拉德利", "Miye Oni": "米耶·奥尼",
    "Juwan Morgan": "朱万·摩根", "Jarrell Brantley": "贾雷尔·布兰特利", "Justin Wright-Foreman": "贾斯汀·赖特-福尔曼",
    "Emmanuel Mudiay ": "伊曼纽尔·穆迪埃", "Tyrone Wallace": "泰伦·华莱士", "Nigel Hayes": "奈杰尔·海耶斯",
    "Amile Jefferson ": "阿米勒·杰斐逊", "Kadeem Allen": "卡迪姆·艾伦", "Jabari Bird": "贾巴里·伯德",
    "Brad Wanamaker": "布拉德·沃纳梅克", "Vincent Poirier": "文森特·普瓦里耶", "Javonte Green": "贾万特·格林",
    "Romeo Langford": "罗密欧·兰福德", "Carsen Edwards": "卡森·爱德华兹", "Tremont Waters": "特雷蒙特·沃特斯",
    "R.J. Hunter": "R.J.亨特", "James Young": "詹姆斯·杨", "Jordan Mickey": "乔丹·米基",
    "Guerchon Yabusele": "盖尔雄·亚布塞莱", "Demetrius Jackson": "德米特里厄斯·杰克逊",
    "Abdel Nader": "阿卜杜勒·纳德", "Semi Ojeleye": "塞米·奥杰莱", "Daniel Theis ": "丹尼尔·泰斯",
    "Guerschon Yabusele": "盖尔雄·亚布塞莱", "Jabari Parker": "贾巴里·帕克", "Michael Carter-Williams  ": "迈克尔·卡特-威廉姆斯",
    "Kris Dunn ": "克里斯·邓恩", "Cameron Payne": "卡梅隆·佩恩", "Dario Saric  ": "达里奥·萨里奇",
    "Ryan Arcidiacono": "瑞安·阿西迪亚科诺", "Denzel Valentine": "丹泽尔·瓦伦丁", "Cristiano Felicio": "克里斯蒂亚诺·费利西奥",
    "Robin Lopez ": "罗宾·洛佩兹", "Chris Dunn": "克里斯·邓恩", "Shaquille Harrison": "沙奎尔·哈里森",
    "Chandler Hutchison": "钱德勒·哈奇森", "Ryan Arcidiacono ": "瑞安·阿西迪亚科诺", "Adam Mokoka": "亚当·莫科卡",
    "Max Strus": "马克斯·斯特鲁斯", "Gabe Vincent": "加布·文森特", "Duncan Robinson": "邓肯·罗宾逊",
    "KZ Okpala": "KZ奥帕拉", "Precious Achiuwa ": "普雷舍斯·阿丘瓦", "Nemanja Bjelica ": "内马尼亚·别利察",
    "Andre Iguodala  ": "安德烈·伊格达拉", "Kevon Looney ": "凯文·卢尼", "Nemanja Bjelica  ": "内马尼亚·别利察",
    "Chris Chiozza": "克里斯·奇奥扎", "Jordan Bell": "乔丹·贝尔", "Damion Lee": "达米恩·李",
    "Andrew Bogut": "安德鲁·博古特", "Festus Ezeli": "费斯图斯·埃泽利", "Marreese Speights": "马里斯·斯贝茨",
    "Leandro Barbosa": "莱昂德罗·巴博萨", "Shaun Livingston": "肖恩·利文斯顿", "Brandon Rush": "布兰登·拉什",
    "Andrew Bogut ": "安德鲁·博古特", "Harrison Barnes   ": "哈里森·巴恩斯", "Festus Ezeli ": "费斯图斯·埃泽利",
    "Marreese Speights ": "马里斯·斯贝茨", "James Michael McAdoo": "詹姆斯·迈克尔·麦卡杜",
    "Ian Clark": "伊恩·克拉克", "Patrick McCaw": "帕特里克·麦考", "Chris Boucher ": "克里斯·布歇",
    "Omari Spellman ": "奥马里·斯佩尔曼", "Glenn Robinson III": "格伦·罗宾逊三世",
    "Marquese Chriss": "马奎斯·克里斯", "Jordan Poole ": "乔丹·普尔", "Eric Paschall": "埃里克·帕斯卡尔",
    "Ky Bowman": "凯·鲍曼", "Mychal Mulder": "米卡尔·穆德", "Juan Toscano-Anderson ": "胡安·托斯卡诺-安德森",
    "Nico Mannion": "尼科·曼尼恩", "Jordan Bell ": "乔丹·贝尔", "Gary Payton II ": "加里·佩顿二世",
    "Chris Chiozza ": "克里斯·奇奥扎", "Alen Smailagic": "阿伦·斯迈拉季奇", "Kylan Thompson": "凯兰·汤普森",
}
